# ==============================================================================
# GitGalaxy v2
# Copyright (c) 2026 Joe Esquibel
#
# This source code is licensed under the PolyForm Noncommercial License 1.0.0.
# You may not use this file except in compliance with the License.
# A copy of the license can be found in the LICENSE file in the root directory
# of this project, or at [https://polyformproject.org/licenses/noncommercial/1.0.0/](https://polyformproject.org/licenses/noncommercial/1.0.0/)
# ==============================================================================
import datetime
import hashlib
import os
import sys
import time

# ==============================================================================
# ASYMMETRIC PUBLIC KEY (Zero-Dependency RSA)
# These massive integers form your Public Key. They can only verify signatures.
# It is mathematically impossible to use them to generate a new valid license.
# Replace RSA_N with the output generated by your gg_key_minter.py script.
# ==============================================================================
RSA_N = 26246426591052891386893360014060848669249039703486471370619690169888703101486249681403954353816532326779849225335705294107639596728626354082552817865001467441053501572461845842571536261194069477635080858097816727197338141635538575333237858100766961309440633177485981055750925168080927021041197775882210942451780414362692590542565258668753401794408633433934057883838766034032873943501312118580786431503874315430445202970310517373086451368642149809238848464100732225425864743074396496142228597753786345783479499353521754427224783854308664241093649206204749644023166728185633076694315652496035018497273095207825227630859  # <-- PASTE YOUR MASSIVE N NUMBER HERE
RSA_E = 65537


def _validate_offline_key(license_key: str) -> str:
    """
    Mathematically verifies an offline license key using pure Python RSA.
    Returns specific states: "VALID", "EXPIRED", "MISSING", "MALFORMED", or "FORGED".

    MALFORMED means the key couldn't even be parsed into a well-formed candidate
    (wrong segment count, wrong prefix, non-hex signature, unparseable date) --
    consistent with a copy-paste error, not evidence of tampering. FORGED is
    reserved for a well-formed key whose cryptographic signature doesn't verify,
    which (short of breaking RSA) can't happen without the private key -- i.e.
    genuine tampering evidence. Keep these separate: enforce_licensing_guard()
    routes them to differently-worded messages and friction levels, and
    conflating them means a fat-fingered paste gets accused of forgery.
    """
    if not license_key:
        return "MISSING"

    try:
        parts = license_key.split("-")

        # Key must contain exactly 5 segments: GG - TIER - CUSTOMER - EXPDATE - SIGNATURE
        if len(parts) != 5 or parts[0] != "GG":
            return "MALFORMED"

        tier, customer, exp_date_str, signature_hex = (
            parts[1],
            parts[2],
            parts[3],
            parts[4],
        )

        # 1. RECONSTRUCT PAYLOAD & HASH
        # We recreate the exact string the minter signed, then hash it.
        payload = f"{tier}-{customer}-{exp_date_str}".encode()
        payload_hash = hashlib.sha256(payload).digest()

        # Convert the raw bytes of the SHA-256 hash into a Python integer
        hash_int = int.from_bytes(payload_hash, byteorder="big")

        # 2. PURE PYTHON RSA VERIFICATION (Authenticate BEFORE checking dates)
        try:
            signature_int = int(signature_hex, 16)
            # RSA Math: (Signature ^ E) mod N
            decrypted_hash_int = pow(signature_int, RSA_E, RSA_N)
        except ValueError:
            # Not valid hex -- a copy-paste error, not evidence of tampering.
            return "MALFORMED"

        # A well-formed, correctly hex-encoded signature that doesn't verify
        # against this exact payload cannot be produced without the private
        # key -- this is the one branch that actually represents forgery.
        if hash_int != decrypted_hash_int:
            return "FORGED"

        # 3. VERIFY EXPIRATION DATE (Only reached if the key is cryptographically authentic)
        try:
            exp_date = datetime.datetime.strptime(exp_date_str, "%Y%m%d")
            if datetime.datetime.now() > exp_date:
                return "EXPIRED"
        except ValueError:
            # Signature checks out but the date field itself doesn't parse.
            # In practice unreachable without the private key, but still not
            # tampering evidence, so route it with the other malformed cases.
            return "MALFORMED"

        return "VALID"

    except Exception:
        # Any other unexpected parsing failure -- treat as malformed input,
        # not as evidence of tampering.
        return "MALFORMED"


def enforce_licensing_guard(tool_name: str = "GitGalaxy Engine v2"):
    """
    Evaluates runtime environment for PolyForm compliance.
    Injects operational friction or audit tripwires for unverified environments.
    """
    # --- ZERO-DEPENDENCY .ENV LOADER ---
    # Python doesn't read .env files natively. This parses it manually
    # so we don't force users to pip install python-dotenv.
    #
    # #466: This MUST be scoped to GitGalaxy's own user config location, never
    # to os.getcwd(). The documented CI usage pattern is `cd <scan-target> &&
    # galaxyscope .`, which makes cwd the (often third-party, untrusted)
    # repository being scanned -- reading its .env would merge whatever keys
    # that repo's own .env defines into this process's environment via
    # setdefault(), a trust-boundary crossing this project flags in other
    # codebases. The documented ways to supply GITGALAXY_LICENSE_KEY (README,
    # action.yml) already set it as a real environment variable, not via a
    # cwd-relative .env, so this loader is purely a local-dev convenience and
    # never needs to see the scan target's files at all.
    env_path = os.path.join(os.path.expanduser("~"), ".config", "gitgalaxy", ".env")
    if os.path.exists(env_path):
        try:
            with open(env_path, encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    # Ignore comments and empty lines, ensure it's a key=value pair
                    if line and not line.startswith("#") and "=" in line:
                        key, val = line.split("=", 1)
                        # Only inject if it's not already set in the system environment
                        os.environ.setdefault(key.strip(), val.strip().strip("\"'"))
        except Exception:  # noqa: S110 -- deliberately silent, see comment below
            pass  # Fail gracefully if the .env file is locked by OS permissions
    # -----------------------------------

    license_key = os.environ.get("GITGALAXY_LICENSE_KEY", "").strip()

    # ==============================================================================
    # 1. THE HONOR SYSTEM GATE (Community Free Tier)
    # ==============================================================================
    if license_key == "COMMUNITY_FREE_TIER":
        print("\n" + "=" * 80, file=sys.stderr)
        print(f" 🪐 {tool_name.upper()} ONLINE — COMMUNITY FREE TIER", file=sys.stderr)
        print("=" * 80, file=sys.stderr)
        print(
            " LEGAL AUDIT TRIPWIRE: Executing under PolyForm Noncommercial License 1.0.0.",
            file=sys.stderr,
        )
        print(
            " WARNING: This key is NOT a legitimate license for commercial enterprise use.",
            file=sys.stderr,
        )
        print(
            " If this engine is running in a corporate CI/CD pipeline, you are out of compliance.",
            file=sys.stderr,
        )
        print(
            " Contact joe@gitgalaxy.io to acquire a commercial enterprise key.",
            file=sys.stderr,
        )
        print("=" * 80 + "\n", file=sys.stderr)
        sys.stderr.flush()
        return

    # Verify the cryptographic status of the provided key
    key_status = _validate_offline_key(license_key)

    # 2. THE FULLY LICENSED CLEAN ROOM
    if key_status == "VALID":
        return

    # 3. THE STANDARD FRICTION TRAP (Expired, Missing, or Malformed - 5 Seconds)
    if key_status in ["EXPIRED", "MISSING", "MALFORMED"]:
        print("\n" + "=" * 80, file=sys.stderr)
        print(f" 🪐 {tool_name.upper()} ONLINE", file=sys.stderr)
        print("=" * 80, file=sys.stderr)
        if key_status == "EXPIRED":
            print(
                " ⚠️  LICENSE EXPIRED: Your GitGalaxy commercial license has lapsed.",
                file=sys.stderr,
            )
            print(
                " You are no longer authorized to use this software for commercial purposes.",
                file=sys.stderr,
            )
        elif key_status == "MALFORMED":
            print(
                " ⚠️  LICENSE KEY MALFORMED: Could not parse the provided key.",
                file=sys.stderr,
            )
            print(
                " Double-check for a copy-paste error -- missing/extra characters or segments.",
                file=sys.stderr,
            )
            print(
                " Executing under PolyForm Noncommercial License 1.0.0.",
                file=sys.stderr,
            )
        else:
            print(
                " ⚠️  LICENSE MISSING: No commercial key detected in the environment.",
                file=sys.stderr,
            )
            print(
                " Executing under PolyForm Noncommercial License 1.0.0.",
                file=sys.stderr,
            )
            print(
                " Commercial use in corporate networks or CI/CD pipelines requires a valid license.",
                file=sys.stderr,
            )
        print(" Contact joe@gitgalaxy.io to acquire a commercial key.", file=sys.stderr)
        print(
            "\n >>> Enforcing 5-second synchronization delay for compliance visibility...",
            file=sys.stderr,
        )
        print("=" * 80 + "\n", file=sys.stderr)
        sys.stderr.flush()
        time.sleep(5.0)
        return

    # 4. THE FORGERY HAMMER (Cryptographically Tampered - 10 Seconds)
    # Reached only for key_status == "FORGED": a well-formed key whose signature
    # doesn't verify, i.e. a genuinely bad cryptographic match rather than a
    # copy-paste error (those are MALFORMED and routed above, tier 3).
    print("\n" + "=" * 80, file=sys.stderr)
    print(f" 🪐 {tool_name.upper()} ONLINE", file=sys.stderr)
    print("=" * 80, file=sys.stderr)
    print(
        " 🚨 LICENSE FORGERY DETECTED: Cryptographic signature does not match.",
        file=sys.stderr,
    )
    print(
        " Tampering with GitGalaxy enterprise keys is a violation of the license agreement.",
        file=sys.stderr,
    )
    print(
        " This check runs entirely offline -- nothing is logged or transmitted anywhere.",
        file=sys.stderr,
    )
    print(
        " Executing under maximum compliance friction.",
        file=sys.stderr,
    )
    print(" Contact joe@gitgalaxy.io to acquire a valid commercial key.", file=sys.stderr)
    print(
        "\n >>> Enforcing 10-second synchronization delay for compliance visibility...",
        file=sys.stderr,
    )
    print("=" * 80 + "\n", file=sys.stderr)
    sys.stderr.flush()
    time.sleep(10.0)
