galaxyscope:
  SARIF_IGNORED_PATHS:
    - "tests/"
    - "mocks/"
    - "vendor/"
    - "gitgalaxy/standards/"
    - "gitgalaxy/security/"
  SARIF_IGNORED_RULES:
    - "GH-1022"
    - "squid-protocol"