"""#4507: Db2 rows generated from the tables' declarations, and what Db2 answered each side.

Pinned without a corpus or a Db2, on DDL written like the estates' own (CBSA's CRETB01 + CREI101, GenApp's db2cre
with its identities and foreign keys, CardDemo's composite key, a DCLGEN's DECLARE TABLE): columns, NOT NULL and
keys are read; every boundary and a NULL reach the rows; keys stay unique and foreign keys find their parent; the
same seed makes the same rows; a scenario key `from` a table, with `miss`, is sometimes a key it does not hold. The
outcome logs of both sides (ggsql.c's, EquivalenceDb2Config's) fold to the same statements, and a difference in a
SQLCODE, a SQLSTATE, a row count or a table's column is named field by field.

The end-to-end proof (cbsa-updacc-generated) needs Docker, Db2 and a JDK: EQUIVALENCE_E2E=1.
"""

import os
import random
import sys
from decimal import Decimal
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))
import equivalence_db2 as db2  # noqa: E402

CBSA = """
CREATE TABLE IBMUSER.ACCOUNT (
    ACCOUNT_EYECATCHER CHAR(4),
    ACCOUNT_SORTCODE CHAR(6) NOT NULL,
    ACCOUNT_NUMBER CHAR(8) NOT NULL,
    ACCOUNT_INTEREST_RATE DECIMAL(6, 2),
    ACCOUNT_OPENED DATE,
    ACCOUNT_OVERDRAFT_LIMIT INTEGER,
    ACCOUNT_BALANCE DECIMAL(12, 2)
);
CREATE UNIQUE INDEX IBMUSER.ACCTINDX
  ON IBMUSER.ACCOUNT(ACCOUNT_SORTCODE,ACCOUNT_NUMBER);
"""

GENAPP = """
CREATE TABLE GENASA1.customer (
     customerNumber INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
                     (START WITH 1000001, INCREMENT BY 1, CACHE 20),
     firstName      CHAR(10),
     dateOfBirth    DATE,
   PRIMARY KEY(customerNumber));
CREATE TABLE GENASA1.policy (
     policyNumber     INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
                       (START WITH 5, INCREMENT BY 2, CACHE 20),
     customerNumber   INTEGER NOT NULL,
     lastChanged      TIMESTAMP NOT NULL WITH DEFAULT,
     commission       SMALLINT,
   PRIMARY KEY(policyNumber),
   FOREIGN KEY(customerNumber)
          REFERENCES GENASA1.customer (customerNumber)
          ON DELETE CASCADE);
"""

CARDDEMO = """
CREATE TABLE CARDDEMO.TRANSACTION_TYPE_CATEGORY
(   TRC_TYPE_CODE                  CHAR(2) NOT NULL,
    TRC_TYPE_CATEGORY              CHAR(4) NOT NULL,
    TRC_CAT_DATA                   VARCHAR(50) NOT NULL,
    PRIMARY KEY(TRC_TYPE_CODE,TRC_TYPE_CATEGORY),
    FOREIGN KEY TRC_TYPE_CODE (TRC_TYPE_CODE)
    REFERENCES CARDDEMO.TRANSACTION_TYPE (TR_TYPE) ON DELETE RESTRICT);
CREATE TABLE CARDDEMO.TRANSACTION_TYPE
(   TR_TYPE                        CHAR(2) NOT NULL,
    TR_DESCRIPTION                 VARCHAR(50) NOT NULL,
    PRIMARY KEY(TR_TYPE));
"""


def _case(compare, **gen):
    return {"db2": {"ddl": [], "seed": "@generate", "compare": list(compare), "generate": {"seed": 7, **gen}}}


def test_ddl_columns_types_nulls_and_keys_are_read():
    t = db2.parse_tables(CBSA)["IBMUSER.ACCOUNT"]
    cols = {c["name"]: c for c in t["columns"]}
    assert cols["ACCOUNT_SORTCODE"]["type"] == "CHAR" and cols["ACCOUNT_SORTCODE"]["length"] == 6
    assert not cols["ACCOUNT_SORTCODE"]["nullable"] and cols["ACCOUNT_EYECATCHER"]["nullable"]
    assert (cols["ACCOUNT_INTEREST_RATE"]["precision"], cols["ACCOUNT_INTEREST_RATE"]["scale"]) == (6, 2)
    assert t["keys"] == [["ACCOUNT_SORTCODE", "ACCOUNT_NUMBER"]]  # the unique index
    g = db2.parse_tables(GENAPP)
    assert g["GENASA1.CUSTOMER"]["columns"][0]["identity"] == {"start": 1000001, "increment": 1}
    assert g["GENASA1.POLICY"]["fks"] == [{"columns": ["CUSTOMERNUMBER"], "parent": "GENASA1.CUSTOMER",
                                           "parent_columns": ["CUSTOMERNUMBER"]}]  # fmt: skip
    c = db2.parse_tables(CARDDEMO)["CARDDEMO.TRANSACTION_TYPE_CATEGORY"]
    assert c["keys"][0] == ["TRC_TYPE_CODE", "TRC_TYPE_CATEGORY"]
    assert c["fks"][0]["parent_columns"] == ["TR_TYPE"]


def test_a_dclgen_declare_table_is_read_too():
    t = db2.parse_tables("DECLARE CARDDEMO.TRANSACTION_TYPE TABLE\n( TR_TYPE CHAR(2) NOT NULL,\n"
                         "  TR_DESCRIPTION VARCHAR(50) NOT NULL\n) ;")["CARDDEMO.TRANSACTION_TYPE"]  # fmt: skip
    assert [(c["name"], c["type"], c["length"], c["nullable"]) for c in t["columns"]] == [
        ("TR_TYPE", "CHAR", 2, False), ("TR_DESCRIPTION", "VARCHAR", 50, False)]  # fmt: skip


def test_rows_reach_every_boundary_and_a_null_and_keys_stay_unique():
    tables = db2.parse_tables(CBSA)
    rows, pools = db2.generate_rows(_case(["IBMUSER.ACCOUNT"], rows=20), Path("."), tables)
    assert len(rows) == 20
    got = {c: [r[c] for _, r in rows] for c in rows[0][1]}
    rate = got["ACCOUNT_INTEREST_RATE"]
    for edge in (Decimal("9999.99"), Decimal("-9999.99"), Decimal("0.01"), Decimal("-0.01"), Decimal(0), None):
        assert edge in rate
    assert {2**31 - 1, -(2**31), 0, None} <= set(got["ACCOUNT_OVERDRAFT_LIMIT"])
    assert {"0001-01-01", "9999-12-31", "2024-02-29", None} <= set(got["ACCOUNT_OPENED"])
    assert {"ZZZZ", "", None} <= set(got["ACCOUNT_EYECATCHER"])  # full length, blank, NULL
    assert None not in got["ACCOUNT_SORTCODE"] and None not in got["ACCOUNT_NUMBER"]  # NOT NULL
    keys = [(r["ACCOUNT_SORTCODE"], r["ACCOUNT_NUMBER"]) for _, r in rows]
    assert len(set(keys)) == len(keys)
    assert sorted(pools["IBMUSER.ACCOUNT.ACCOUNT_NUMBER"]) == sorted(r["ACCOUNT_NUMBER"] for _, r in rows)
    again, _ = db2.generate_rows(_case(["IBMUSER.ACCOUNT"], rows=20), Path("."), tables)
    assert again == rows  # the seed decides


def test_a_case_steers_columns_and_keys_stay_unique_under_few_values():
    tables = db2.parse_tables(CBSA)
    case = _case([], tables={"IBMUSER.ACCOUNT": {"rows": 12, "columns": {
        "ACCOUNT_SORTCODE": {"values": ["987654", "123456"]}, "ACCOUNT_NUMBER": {"digits": True},
        "ACCOUNT_OPENED": {"null": False}}}})  # fmt: skip
    rows, _ = db2.generate_rows(case, Path("."), tables)
    assert {r["ACCOUNT_SORTCODE"] for _, r in rows} == {"987654", "123456"}
    assert all(r["ACCOUNT_NUMBER"].isdigit() and len(r["ACCOUNT_NUMBER"]) == 8 for _, r in rows)
    assert None not in [r["ACCOUNT_OPENED"] for _, r in rows]
    with pytest.raises(ValueError, match="no column"):
        db2.generate_rows(_case([], tables={"IBMUSER.ACCOUNT": {"columns": {"NOPE": {}}}}), Path("."), tables)


def test_foreign_keys_find_their_parent_and_identities_are_left_to_db2():
    tables = db2.parse_tables(GENAPP)
    rows, pools = db2.generate_rows(_case(["GENASA1.POLICY"], rows=6), Path("."), tables)
    order = [t for t, _ in rows]
    assert order.index("GENASA1.CUSTOMER") < order.index("GENASA1.POLICY")  # the parent first, added unasked
    assert all("CUSTOMERNUMBER" not in r for t, r in rows if t == "GENASA1.CUSTOMER")  # Db2's identity
    assert pools["GENASA1.CUSTOMER.CUSTOMERNUMBER"] == list(range(1000001, 1000007))
    assert pools["GENASA1.POLICY.POLICYNUMBER"] == [5, 7, 9, 11, 13, 15]  # START WITH 5, INCREMENT BY 2
    assert {r["CUSTOMERNUMBER"] for t, r in rows if t == "GENASA1.POLICY"} <= set(range(1000001, 1000007))
    seed = "".join(f"INSERT INTO {t} ({', '.join(r)}) VALUES ({', '.join(db2.literal(v) for v in r.values())});"
                   for t, r in rows)  # fmt: skip
    assert "INSERT INTO GENASA1.POLICY (CUSTOMERNUMBER, LASTCHANGED, COMMISSION)" in seed
    assert "'9999-12-31-23.59.59.999999'" in seed and "32767" in seed and "-32768" in seed
    rows2, _ = db2.generate_rows(_case(["CARDDEMO.TRANSACTION_TYPE_CATEGORY"], rows=10), Path("."),
                                 db2.parse_tables(CARDDEMO))  # fmt: skip
    parents = {r["TR_TYPE"] for t, r in rows2 if t == "CARDDEMO.TRANSACTION_TYPE"}
    kids = [r for t, r in rows2 if t == "CARDDEMO.TRANSACTION_TYPE_CATEGORY"]
    assert {r["TRC_TYPE_CODE"] for r in kids} <= parents
    assert len({(r["TRC_TYPE_CODE"], r["TRC_TYPE_CATEGORY"]) for r in kids}) == len(kids)
    assert {"", "Z" * 50, "B  "} <= {r["TR_DESCRIPTION"] for t, r in rows2 if t == "CARDDEMO.TRANSACTION_TYPE"}


def test_literals():
    assert db2.literal(None) == "NULL" and db2.literal("O'K") == "'O''K'"
    assert db2.literal(Decimal("-0.01")) == "-0.01" and db2.literal(Decimal("1E+2")) == "100"


def test_a_scenario_key_from_a_table_misses_when_asked():
    import equivalence_inputs as ei

    rng = random.Random(1)
    pool = ["00000001", "00000002", "00000003"]
    for _ in range(20):
        v = ei._missing(rng, pool, {"bytes": 8})
        assert len(v) == 8 and v.isdigit() and int(v) not in (1, 2, 3)
    assert ei._missing(rng, ["AB", "CD"], {"bytes": 2}) not in ("AB", "CD")


def test_both_sides_outcome_logs_fold_to_the_same_statements():
    cobol = db2.cobol_outcomes(
        "SELECT1 - SELECT 0 00000 0 0\n"  # a row
        "EXEC - UPDATE 0 00000 1 0\n"
        "COMMIT - COMMIT 0 00000 0 0\n"  # the program's own: not compared
        "SELECT1 - SELECT 100 02000 -1 0\n"  # no row
        "SELECT1 - SELECT -305 22002 0 0\n"  # a NULL with no indicator: Db2 returned the row
        "EXEC - DELETE 100 02000 0 0\n"
        "OPEN C1 SELECT 0 00000 0 0\nFETCH C1 SELECT 0 00000 0 0\nFETCH C1 SELECT 0 00000 0 0\n"
        "FETCH C1 SELECT 100 02000 0 0\nCLOSE C1 SELECT 0 00000 0 0\n"
        "EXEC - INSERT -803 23505 0 0\n"
    )
    java = db2.java_outcomes(
        "SELECT 0 00000 1 1 Q\nUPDATE 0 00000 1 0 U\nSELECT 0 00000 0 1 Q\nSELECT 0 00000 1 1 Q\n"
        "DELETE 0 00000 0 0 U\nSELECT 0 00000 2 1 Q\nINSERT -803 23505 0 0 U\n"
    )
    assert [(x["verb"], x["sqlcode"], x["sqlstate"], x["rows"]) for x in cobol] == [
        ("SELECT", 0, "00000", 1), ("UPDATE", 0, "00000", 1), ("SELECT", 100, "02000", 0),
        ("SELECT", 0, "00000", 1), ("DELETE", 100, "02000", 0), ("SELECT", 0, "00000", 2),
        ("INSERT", -803, "23505", None)]  # fmt: skip
    d = db2.compare_outcomes(cobol, java)
    assert d["equal"] == d["statements"] == 7 and not d["diffs"]


def test_a_differing_answer_is_named_field_by_field():
    cobol = db2.cobol_outcomes("SELECT1 - SELECT 100 02000 -1 0\nEXEC - INSERT -530 23503 0 0\n")
    java = db2.java_outcomes("SELECT 0 00000 1 1 Q\nINSERT 0 00000 1 0 U\nUPDATE 0 00000 1 0 U\n")
    d = db2.compare_outcomes(cobol, java)
    assert d["statements"] == 3 and d["equal"] == 0
    assert d["diffs"][0]["fields"] == [{"field": "sqlcode", "cobol": 100, "java": 0},
                                       {"field": "sqlstate", "cobol": "02000", "java": "00000"},
                                       {"field": "rows", "cobol": 0, "java": 1}]  # fmt: skip
    assert {f["field"] for f in d["diffs"][1]["fields"]} == {"sqlcode", "sqlstate"}
    assert d["diffs"][2]["missing"] == "cobol"


def test_a_table_dump_difference_is_named_by_column():
    head = "A|B|C\n"
    left = (head + "[1]|[x|y]|NULL\n[2]|[b]|[c]\n").encode()
    right = (head + "[1]|[x|y]|[0]\n[2]|[b]|[c]\n").encode()
    assert db2.split_row("[1]|[x|y]|NULL") == ["[1]", "[x|y]", "NULL"]
    d = db2.diff_dump(left, right)
    assert d["equal"] == 1 and d["diffs"] == [{"record": 1, "fields": [{"field": "C", "cobol": "NULL", "java": "[0]"}]}]


@pytest.mark.skipif(os.environ.get("EQUIVALENCE_E2E") != "1", reason="needs Docker (GnuCOBOL, Db2) and a JDK + Maven")
def test_the_updacc_port_holds_on_generated_db2_rows(tmp_path):
    """CBSA's UPDACC (CICS, Db2) proves on 30 generated ACCOUNT rows and 40 generated LINKs: every task's
    statements answered alike on both sides, the table alike after every task."""
    import json
    import shutil
    import subprocess

    if not shutil.which("docker"):
        pytest.skip("no docker")
    tool = Path(__file__).resolve().parents[1] / "tools" / "equivalence.py"
    proc = subprocess.run([sys.executable, str(tool), "run", "cbsa-updacc-generated", "--keep", str(tmp_path)],  # noqa: S603
                          capture_output=True, text=True, check=False)  # fmt: skip
    assert proc.returncode == 0, proc.stdout[-3000:] + proc.stderr[-3000:]
    report = json.loads((tmp_path / "report.json").read_text())
    assert report["proven"] is True and report["db2_generated"] == {"IBMUSER.ACCOUNT": 30}
    sql = [o["sql"] for o in report["outputs"].values()]
    assert len(sql) == 40 and all(q["statements"] and q["equal"] == q["statements"] for q in sql)
    assert {x["sqlcode"] for q in sql for x in q["cobol"]} >= {0, 100}
