"""
The Java side of the equivalence harness (#3624; see equivalence.py).

The case's corpus goes through the refractor and cobol-to-java (target config `h2`,
java_target_matrix's own helpers), the case's hand-ported sources (`port/`, laid out
under com/gitgalaxy/modernized) replace the generated ones, and a generated JUnit test
-- EquivalenceRunTest -- runs the step in a Spring context on H2:

  1. each input dataset with an `entity` is loaded record by record through that
     entity's generated codec (fromRecord) into its repository;
  2. the program's service runs `runBatch(dds, parm)`, the DDs mapped by the generated
     DatasetResolver to files under the work directory, the clock pinned by
     `gitgalaxy.clock`;
  3. each compared output is dumped: a VSAM store from its repository in key order
     through toRecord, a sequential dataset as the file the step wrote.

Maven runs offline when the local repository already holds the build's artifacts
(the compile matrix fills it), else online.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

import java_target_matrix as jtm

CASES = Path(__file__).resolve().parents[1] / "equivalence"  # == equivalence.CASES
PKG = "com.gitgalaxy.modernized"
PKG_DIR = PKG.replace(".", "/")


def _service_class(program: str) -> str:
    from gitgalaxy.tools.cobol_to_java.cobol_to_java_names import java_class_base

    return java_class_base(program) + "Service"


def _clock(case: dict[str, Any]) -> str:
    """The case's COB_CURRENT_DATE (`YYYY/MM/DD hh:mm:ss.cc`) as an ISO local date-time."""
    date, _, time = case["clock"].partition(" ")
    return f"{date.replace('/', '-')}T{time}"


def equivalence_test(case: dict[str, Any]) -> str:
    """The generated JUnit test that loads, runs and dumps one case (see the module docstring)."""
    svc = _service_class(case["program"])
    var = svc[0].lower() + svc[1:]
    fields, loads, dumps = [], [], []
    for dd, spec in case["datasets"].items():
        ent = spec.get("entity")
        if ent:
            fields.append(f"    @Autowired {PKG}.repository.vsam.{ent}Repository {ent[0].lower()}{ent[1:]}Repository;")
        if ent and "input" in spec:
            loads.append(
                f'        load("{dd}", {spec["reclen"]}, {ent}::fromRecord, {ent[0].lower()}{ent[1:]}Repository);'
            )
        if spec.get("compare") and ent:
            dumps.append(f'        dump("{dd}", {ent[0].lower()}{ent[1:]}Repository.findAll().stream()'
                         f'.map(r -> r.toRecord(TEXT)).sorted(java.util.Arrays::compare).toList());')  # fmt: skip
        elif spec.get("compare"):
            dumps.append(f'        if (Files.exists(datasets.resolve("{dd}"))) {{  // a stub may write nothing\n'
                         f'            Files.copy(datasets.resolve("{dd}"), out.resolve("{dd}.out"), '
                         "java.nio.file.StandardCopyOption.REPLACE_EXISTING);\n        }")  # fmt: skip
    dds = ", ".join(f'new Dd("{dd}", "{dd}", null, null, null)' for dd in case["datasets"])
    parm = f'"{case["parm"]}"' if case.get("parm") is not None else "null"
    imports = "".join(
        f"import {PKG}.entity.vsam.{s['entity']};\n" for s in case["datasets"].values() if s.get("entity")
    )
    return f"""package {PKG};

import {PKG}.batch.Dd;
{imports}import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.function.BiFunction;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.jpa.repository.JpaRepository;

/** #3624: the equivalence run of {case["program"]} ({case["name"]}) -- generated by tests/tools/equivalence_java.py. */
@SpringBootTest(properties = {{"spring.jpa.show-sql=false", "gitgalaxy.clock={_clock(case)}",
        "gitgalaxy.datasets.directory=${{equivalence.datasets}}"}})
class EquivalenceRunTest {{

    static final Charset TEXT = StandardCharsets.ISO_8859_1;
    final Path in = Path.of(System.getProperty("equivalence.in"));
    final Path out = Path.of(System.getProperty("equivalence.out"));
    final Path datasets = Path.of(System.getProperty("equivalence.datasets"));

    @Autowired {PKG}.service.{svc} {var};
{chr(10).join(fields)}

    @Test
    void run() throws IOException {{
{chr(10).join(loads)}
        int rc = {var}.runBatch(List.of({dds}), {parm});
        Files.writeString(out.resolve("RETURN-CODE"), Integer.toString(rc));
{chr(10).join(dumps)}
    }}

    <E> void load(String dd, int reclen, BiFunction<byte[], Charset, E> fromRecord, JpaRepository<E, ?> repo)
            throws IOException {{
        byte[] data = Files.readAllBytes(in.resolve(dd + ".in"));
        List<E> rows = new ArrayList<>();
        for (int i = 0; i + reclen <= data.length; i += reclen) {{
            rows.add(fromRecord.apply(java.util.Arrays.copyOfRange(data, i, i + reclen), TEXT));
        }}
        repo.saveAll(rows);
    }}

    void dump(String dd, List<byte[]> records) throws IOException {{
        try (var o = Files.newOutputStream(out.resolve(dd + ".out"))) {{
            for (byte[] r : records) {{
                o.write(r);
            }}
        }}
    }}
}}
"""


def run_java(
    case: dict[str, Any], corpus: Path, work: Path, inputs: Path, port: bool = True, port_dir: Path | None = None
) -> dict[str, bytes]:
    """Generate, overlay, run; {dd: output bytes}. `inputs` holds the COBOL side's `<DD>.in`
    fixed-length files -- the very bytes the COBOL program read. `port` False runs the generated
    service as generated (the stub), the baseline the port is measured against."""
    work.mkdir(parents=True, exist_ok=True)
    clean = jtm.refactor(corpus, work, scan=True)
    project = jtm.generate(clean, "h2", jtm.MATRIX["h2"], work)
    port_dir = port_dir or CASES / case["name"] / "port"  # #3753: any candidate port, laid out the same way
    for f in port_dir.rglob("*.java") if port else []:
        dest = project / "src/main/java" / PKG_DIR / f.relative_to(port_dir)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(f, dest)
    test = project / "src/test/java" / PKG_DIR / "EquivalenceRunTest.java"
    test.parent.mkdir(parents=True, exist_ok=True)
    test.write_text(equivalence_test(case), encoding="utf-8")
    out, datasets = work / "out", work / "datasets"
    for d in (out, datasets):
        d.mkdir(parents=True, exist_ok=True)
    for dd, spec in case["datasets"].items():  # a sequential input is a file the program opens itself
        if "input" in spec and not spec.get("entity"):
            shutil.copy(inputs / f"{dd}.in", datasets / dd)
    env = dict(os.environ, JAVA_HOME=jtm._jdk(17))
    env["PATH"] = str(Path(env["JAVA_HOME"]) / "bin") + os.pathsep + env["PATH"]
    cmd = ["mvn", "-q", "-B", "test", "-Dtest=EquivalenceRunTest", "-Dsurefire.failIfNoSpecifiedTests=false",
           f"-DargLine=-Dequivalence.in={inputs} -Dequivalence.out={out} -Dequivalence.datasets={datasets}"]  # fmt: skip
    proc = subprocess.run(cmd, cwd=project, env=env, capture_output=True, text=True, check=False)  # noqa: S603
    (work / "maven.log").write_text(proc.stdout + proc.stderr, encoding="utf-8")
    if proc.returncode != 0:
        tail = "\n".join((proc.stdout + proc.stderr).splitlines()[-60:])
        raise RuntimeError(f"Java side failed (see {work / 'maven.log'}):\n{tail}")
    outs = {dd: out / f"{dd}.out" for dd, spec in case["datasets"].items() if spec.get("compare")}
    outs["RETURN-CODE"] = out / "RETURN-CODE"
    read = {dd: f.read_bytes() for dd, f in outs.items() if f.is_file()}  # a stub may write nothing
    if "RETURN-CODE" in read:
        read["RETURN-CODE"] = read["RETURN-CODE"].strip()  # a number, not a record: whitespace is not data
    return read
