/* generated from gitgalaxy/standards/cics by `python -m gitgalaxy.standards.cics regen`; do not edit */
#ifndef GGCICS_SPEC_H
#define GGCICS_SPEC_H

/* IBM CICS TS, RESP values (DFHRESP): the condition name -> its RESP number */
enum {
    DFHRESP_NORMAL = 0,
    DFHRESP_ERROR = 1,
    DFHRESP_RDATT = 2,
    DFHRESP_WRBRK = 3,
    DFHRESP_EOF = 4,
    DFHRESP_EODS = 5,
    DFHRESP_EOC = 6,
    DFHRESP_INBFMH = 7,
    DFHRESP_ENDINPT = 8,
    DFHRESP_NONVAL = 9,
    DFHRESP_NOSTART = 10,
    DFHRESP_TERMIDERR = 11,
    DFHRESP_FILENOTFOUND = 12,
    DFHRESP_DSIDERR = 12,
    DFHRESP_NOTFND = 13,
    DFHRESP_DUPREC = 14,
    DFHRESP_DUPKEY = 15,
    DFHRESP_INVREQ = 16,
    DFHRESP_IOERR = 17,
    DFHRESP_NOSPACE = 18,
    DFHRESP_NOTOPEN = 19,
    DFHRESP_ENDFILE = 20,
    DFHRESP_ILLOGIC = 21,
    DFHRESP_LENGERR = 22,
    DFHRESP_QZERO = 23,
    DFHRESP_SIGNAL = 24,
    DFHRESP_QBUSY = 25,
    DFHRESP_ITEMERR = 26,
    DFHRESP_PGMIDERR = 27,
    DFHRESP_TRANSIDERR = 28,
    DFHRESP_ENDDATA = 29,
    DFHRESP_INVTSREQ = 30,
    DFHRESP_EXPIRED = 31,
    DFHRESP_RETPAGE = 32,
    DFHRESP_RTEFAIL = 33,
    DFHRESP_RTESOME = 34,
    DFHRESP_TSIOERR = 35,
    DFHRESP_MAPFAIL = 36,
    DFHRESP_INVERRTERM = 37,
    DFHRESP_INVMPSZ = 38,
    DFHRESP_IGREQID = 39,
    DFHRESP_OVERFLOW = 40,
    DFHRESP_INVLDC = 41,
    DFHRESP_NOSTG = 42,
    DFHRESP_JIDERR = 43,
    DFHRESP_QIDERR = 44,
    DFHRESP_NOJBUFSP = 45,
    DFHRESP_DSSTAT = 46,
    DFHRESP_SELNERR = 47,
    DFHRESP_FUNCERR = 48,
    DFHRESP_UNEXPIN = 49,
    DFHRESP_NOPASSBKRD = 50,
    DFHRESP_NOPASSBKWR = 51,
    DFHRESP_SYSIDERR = 53,
    DFHRESP_ISCINVREQ = 54,
    DFHRESP_ENQBUSY = 55,
    DFHRESP_ENVDEFERR = 56,
    DFHRESP_IGREQCD = 57,
    DFHRESP_SESSIONERR = 58,
    DFHRESP_SYSBUSY = 59,
    DFHRESP_SESSBUSY = 60,
    DFHRESP_NOTALLOC = 61,
    DFHRESP_CBIDERR = 62,
    DFHRESP_INVEXITREQ = 63,
    DFHRESP_INVPARTNSET = 64,
    DFHRESP_INVPARTN = 65,
    DFHRESP_PARTNFAIL = 66,
    DFHRESP_USERIDERR = 69,
    DFHRESP_NOTAUTH = 70,
    DFHRESP_VOLIDERR = 71,
    DFHRESP_SUPPRESSED = 72,
    DFHRESP_RESIDERR = 75,
    DFHRESP_NOSPOOL = 80,
    DFHRESP_TERMERR = 81,
    DFHRESP_ROLLEDBACK = 82,
    DFHRESP_END = 83,
    DFHRESP_DISABLED = 84,
    DFHRESP_ALLOCERR = 85,
    DFHRESP_STRELERR = 86,
    DFHRESP_OPENERR = 87,
    DFHRESP_SPOLBUSY = 88,
    DFHRESP_SPOLERR = 89,
    DFHRESP_NODEIDERR = 90,
    DFHRESP_TASKIDERR = 91,
    DFHRESP_TCIDERR = 92,
    DFHRESP_DSNNOTFOUND = 93,
    DFHRESP_LOADING = 94,
    DFHRESP_MODELIDERR = 95,
    DFHRESP_OUTDESCRERR = 96,
    DFHRESP_PARTNERIDERR = 97,
    DFHRESP_PROFILEIDERR = 98,
    DFHRESP_NETNAMEIDERR = 99,
    DFHRESP_LOCKED = 100,
    DFHRESP_RECORDBUSY = 101,
    DFHRESP_UOWNOTFOUND = 102,
    DFHRESP_UOWLNOTFOUND = 103,
    DFHRESP_CONTAINERERR = 110,
    DFHRESP_CHANNELERR = 122,
    DFHRESP_CCSIDERR = 123,
    DFHRESP_TIMEDOUT = 124,
    DFHRESP_CODEPAGEERR = 125,
    DFHRESP_INCOMPLETE = 126,
    DFHRESP_APPNOTFOUND = 127,
    DFHRESP_BUSY = 128
};

/* The abend code of an unhandled condition (IBM's AEIx / AEYx / AEZx abend codes, the AEIA topic); "????" for
   one the spec has none for. */
static const char *condition_abcode(int resp) {
    switch (resp) {
    case DFHRESP_NOTFND: return "AEIM";
    case DFHRESP_LENGERR: return "AEIV";
    case DFHRESP_ITEMERR: return "AEIZ";
    case DFHRESP_QIDERR: return "AEYH";
    case DFHRESP_MAPFAIL: return "AEI9";
    case DFHRESP_ENDDATA: return "AEI2";
    case DFHRESP_PGMIDERR: return "AEI0";
    case DFHRESP_INVREQ: return "AEIP";
    case DFHRESP_CONTAINERERR: return "AEZJ";
    case DFHRESP_CHANNELERR: return "AEZV";
    default: return "????";
    }
}

#endif
