# ==============================================================================
# GitGalaxy Core: DB2 DECLARE TABLE / DCLGEN schemas (#3344, roadmap #3249)
#
# PURPOSE:
# The counted rules say THAT a COBOL or PL/I file embeds SQL (`EXEC SQL` is an
# io/db hit). They never say WHICH table shape the program binds to. DB2's
# precompiler checks every host-language statement against an
#
#     EXEC SQL DECLARE <table> TABLE ( <column> <type> [NOT NULL ...] , ... )
#
# statement -- written by hand inline in the program, or generated by DCLGEN
# into a copybook/include member that the program pulls in with
# `EXEC SQL INCLUDE`. That statement is the SQL-side schema of the system: the
# table name, and per column its SQL type, length/precision, scale and
# nullability, in DB2 column order. This module is the fact channel for it; it
# rides out of `mainframe_boundary.extract_boundary` as the `sql_tables` key and
# lands in `sql_table_data`.
#
# WHY NOT record_data:
# A DCLGEN member carries TWO schemas. Its COBOL `01 DCL...` host structure is a
# record layout and already lands in record_data (#3246). The DECLARE TABLE is
# the DB2 side: SQL types, length/scale and NOT NULL have no home in record_data's
# level/PIC/USAGE/OCCURS/REDEFINES columns, and forcing them into `attributes`
# would make every record consumer (the forge, the record differential) see
# phantom data items that are not storage. So it is its own per-file child table.
#
# SCOPE AND NON-SCOPE:
#   - Same-file only (the copybook precedent, #3246): a DCLGEN member carries its
#     own DECLARE TABLE and is extracted when the member itself is scanned. A
#     program that `EXEC SQL INCLUDE`s it gets the edge (copy_deps); assembling
#     the two is a consumer's job.
#   - Reads the PRISM CODE STREAM, so a commented-out DECLARE produces nothing.
#   - `DECLARE GLOBAL TEMPORARY TABLE` (a runtime work table) and `DECLARE ...
#     CURSOR` are not table declarations and do not match.
#   - No DDL: a `CREATE TABLE` in a `.sql`/db2_sql file is a different language
#     and a different channel (#3249's SQL/ORM row).
#
# BOUNDED SCANNING (how_to_add_a_language.md's rules apply to extractors too):
# the header regex has only bounded whitespace runs; the column list is walked
# by hand to its balancing `)` under a hard `_BODY_LIMIT`, so no pattern ever
# spans the body.
# ==============================================================================
import re
from typing import Any, Optional

# An SQL identifier: a delimited "..." name (kept verbatim) or an ordinary one
# (folded to upper case, as DB2 does). DB2 names carry `_`; `@#$` appear in
# older mainframe naming. A COBOL hyphen is NOT an SQL name character.
_IDENT = r'(?:"[^"\n]{1,128}"|[A-Z@#$][A-Z0-9_@#$]{0,127})'
# `table`, `owner.table`, `location.owner.table`.
_QNAME = _IDENT + r"(?:[ \t]{0,8}\.[ \t]{0,8}" + _IDENT + r"){0,2}"

# The statement header up to the column list's opening parenthesis. The leading
# lookbehind is the mainframe hyphen boundary (a `-` is a COBOL name character,
# so `MY-EXEC SQL` must not anchor here).
_DECLARE_TABLE = re.compile(
    r"(?<![A-Z0-9_@#$-])EXEC[ \t\r\n]{1,200}SQL[ \t\r\n]{1,200}DECLARE[ \t\r\n]{1,200}"
    r"(" + _QNAME + r")[ \t\r\n]{1,200}TABLE[ \t\r\n]{0,200}\(",
    re.I,
)
# Cheap prefilters: nearly every file has no DECLARE ... TABLE at all (and every
# PL/I file has a DECLARE, so the keyword alone is not enough).
_HAS_DECLARE = re.compile(r"DECLARE[ \t\r\n]", re.I)
_HAS_TABLE = re.compile(r"TABLE[ \t\r\n(]", re.I)

# The longest column list read. DB2 caps a table at 750 columns; at ~50 chars
# per real DCLGEN column line that is ~37k, so 64k leaves room without ever
# letting an unbalanced `(` swallow the rest of a large program.
_BODY_LIMIT = 65536

# Fixed-format sequence fields. Columns 1-6 of a COBOL line (`000500`, `R2    `)
# and columns 73-80 of a COBOL or PL/I line (`00050000`). PRISM keeps both on a
# code line, and inside a multi-line column list they would read as column
# names. Blanked in place so offsets and line numbers are unchanged.
_COBOL_SEQ_AREA = re.compile(r"[0-9A-Z ]{6}(?=[ \-])", re.I)
_TRAILING_SEQ = re.compile(r"[ \t]*[A-Z]{0,4}[0-9]{2,8}[ \t]*", re.I)

# An element of the list that is a table constraint rather than a column. DB2's
# DECLARE TABLE grammar has none, but a hand-written one copied from DDL can.
_CONSTRAINT = re.compile(
    r"(?:PRIMARY[ \t\r\n]+KEY|FOREIGN[ \t\r\n]+KEY|UNIQUE[ \t\r\n]*\(|CONSTRAINT[ \t\r\n]|CHECK[ \t\r\n]*\()", re.I
)
_NAME_AT = re.compile(_IDENT, re.I)
_WORD = re.compile(r"[A-Z][A-Z0-9_]{0,63}", re.I)
# Words that end the data type and start a column option.
_OPTION_WORDS = frozenset(
    {
        "NOT",
        "NULL",
        "WITH",
        "FOR",
        "DEFAULT",
        "CCSID",
        "GENERATED",
        "IMPLICITLY",
        "INLINE",
        "CONSTRAINT",
        "PRIMARY",
        "UNIQUE",
        "REFERENCES",
        "CHECK",
        "AS",
        "FIELDPROC",
        "AUTO",
    }
)
# `TIMESTAMP [(p)] WITH|WITHOUT TIME ZONE` -- part of the type, not an option.
_TIME_ZONE = re.compile(r"[ \t\r\n]*(WITH(?:OUT)?)[ \t\r\n]+TIME[ \t\r\n]+ZONE(?![A-Z0-9_])", re.I)
# `(n)`, `(p, s)`, `(1M)`, `(32 K OCTETS)`: the length/precision, an optional
# K/M/G multiplier (LOB lengths), and the scale.
_TYPE_ARGS = re.compile(r"[ \t\r\n]*(\d{1,10})[ \t\r\n]*([KMG])?(?![A-Z0-9_])[^,]{0,40}(?:,[ \t\r\n]*(\d{1,3}))?", re.I)
_MULTIPLIER = {"K": 1024, "M": 1024 * 1024, "G": 1024 * 1024 * 1024}
_NOT_NULL = re.compile(r"(?<![A-Z0-9_])NOT[ \t\r\n]+NULL(?![A-Z0-9_])", re.I)
_WS = re.compile(r"[ \t\r\n]+")


def _blank_sequence_fields(code_stream: str, dialect: str) -> str:
    """The code stream with fixed-format sequence fields blanked, offsets unchanged."""
    lines = code_stream.split("\n")
    for idx, line in enumerate(lines):
        body = line.rstrip("\r")
        if 72 < len(body.rstrip()) <= 80 and _TRAILING_SEQ.fullmatch(body[72:]):
            body = body[:72] + " " * (len(body) - 72)
        # COBOL only: PL/I has no cols 1-6 sequence area. A real sequence area has
        # a digit in it; `EXEC S`/`( EMPN` do not, so free-format code is left alone.
        if dialect == "cobol" and len(body) > 6 and any(c.isdigit() for c in body[:6]) and _COBOL_SEQ_AREA.match(body):
            body = " " * 6 + body[6:]
        lines[idx] = body + line[len(line.rstrip("\r")) :]
    return "\n".join(lines)


def _inside_literal(text: str, offset: int) -> bool:
    """Whether `offset` sits inside a quoted literal opened earlier on its own line.

    `DISPLAY 'EXEC SQL DECLARE T TABLE (' ...` is not a declaration. Quote state
    is per line, never across one (a COBOL/PL/I literal does not span a physical
    line without a continuation, and an unbalanced apostrophe in real source
    would otherwise swallow the file -- the #3210 trap)."""
    quote = None
    for ch in text[text.rfind("\n", 0, offset) + 1 : offset]:
        if quote is None:
            if ch in "'\"":
                quote = ch
        elif ch == quote:
            quote = None
    return quote is not None


def _strip_sql_comments(body: str) -> str:
    """`--` SQL comments blanked to end of line (outside quotes), offsets kept."""
    out = []
    quote = None
    i = 0
    n = len(body)
    while i < n:
        ch = body[i]
        if ch == "\n":
            quote = None
            out.append(ch)
        elif quote:
            if ch == quote:
                quote = None
            out.append(ch)
        elif ch in "'\"":
            quote = ch
            out.append(ch)
        elif ch == "-" and body.startswith("--", i):
            end = body.find("\n", i)
            end = n if end < 0 else end
            out.append(" " * (end - i))
            i = end
            continue
        else:
            out.append(ch)
        i += 1
    return "".join(out)


def _balanced_close(text: str, open_at: int) -> int:
    """Index of the `)` balancing the `(` at `open_at`, or -1 within `_BODY_LIMIT`."""
    depth = 0
    quote = None
    stop = min(len(text), open_at + _BODY_LIMIT)
    for i in range(open_at, stop):
        ch = text[i]
        if quote:
            if ch == quote or ch == "\n":
                quote = None
        elif ch in "'\"":
            quote = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return i
    return -1


def _split_top_level(body: str) -> list[tuple[int, str]]:
    """(offset, text) of each comma-separated element outside parentheses and quotes."""
    parts: list[tuple[int, str]] = []
    depth = 0
    quote = None
    start = 0
    for i, ch in enumerate(body):
        if quote:
            if ch == quote or ch == "\n":
                quote = None
        elif ch in "'\"":
            quote = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch == "," and depth == 0:
            parts.append((start, body[start:i]))
            start = i + 1
    parts.append((start, body[start:]))
    return parts


def _sql_name(token: str) -> str:
    """A delimited name loses its quotes and keeps its case; an ordinary one is upper-cased."""
    token = token.strip()
    if token.startswith('"') and token.endswith('"') and len(token) >= 2:
        return token[1:-1]
    return token.upper()


def _qualified_name(text: str) -> str:
    return ".".join(_sql_name(m.group(0)) for m in _NAME_AT.finditer(text))


def _column(element: str) -> Optional[dict[str, Any]]:
    """One column definition -> {name, sql_type, length, scale, nullable, attributes}, or None."""
    lead = len(element) - len(element.lstrip())
    text = element[lead:]
    if not text or _CONSTRAINT.match(text):
        return None
    name_match = _NAME_AT.match(text)
    if not name_match:
        return None
    rest = text[name_match.end() :]

    # The data type: up to four words before the first option word or `(`.
    pos = 0
    words: list[str] = []
    while len(words) < 4:
        ws = _WS.match(rest, pos)
        probe = ws.end() if ws else pos
        word = _WORD.match(rest, probe)
        if not word or word.group(0).upper() in _OPTION_WORDS:
            break
        words.append(word.group(0).upper())
        pos = word.end()
    if not words:
        return None

    length = scale = None
    ws = _WS.match(rest, pos)
    probe = ws.end() if ws else pos
    if probe < len(rest) and rest[probe] == "(":
        close = rest.find(")", probe)
        if close < 0:
            return None
        args = _TYPE_ARGS.match(rest[probe + 1 : close])
        if args:
            length = int(args.group(1)) * _MULTIPLIER.get((args.group(2) or "").upper(), 1)
            scale = int(args.group(3)) if args.group(3) is not None else None
        pos = close + 1
    zone = _TIME_ZONE.match(rest, pos)
    if zone:
        words += [zone.group(1).upper(), "TIME", "ZONE"]
        pos = zone.end()

    attributes = _WS.sub(" ", rest[pos:]).strip() or None
    return {
        "name": _sql_name(name_match.group(0)),
        "sql_type": " ".join(words),
        "length": length,
        "scale": scale,
        "nullable": not (attributes and _NOT_NULL.search(attributes)),
        "attributes": attributes,
        "offset": lead,
    }


def extract_sql_tables(code_stream: str, dialect: str = "cobol") -> list[dict[str, Any]]:
    """Every `EXEC SQL DECLARE <table> TABLE (...)` column in one COBOL/PL/I file.

    A flat list in source order, one dict per column:

        {table, table_line, colno, name, sql_type, length, scale, nullable,
         attributes, line}

    `colno` is the 1-based column position in its table (DB2's SYSCOLUMNS.COLNO).
    `sql_type` is the type as written, upper-cased and whitespace-collapsed
    (`DECIMAL`, `VARCHAR`, `TIMESTAMP WITH TIME ZONE`); `length` is the length or
    precision with any LOB K/M/G multiplier applied, `scale` the DECIMAL scale;
    both are None when the source writes none (DB2's defaults are not invented).
    `attributes` is every column option after the type (`NOT NULL WITH DEFAULT`,
    `FOR BIT DATA`), None when there is none; `nullable` is False exactly when it
    says NOT NULL. `line`/`table_line` are real source lines (the code stream
    keeps lines 1:1).
    """
    if not code_stream or not _HAS_DECLARE.search(code_stream) or not _HAS_TABLE.search(code_stream):
        return []
    text = _blank_sequence_fields(code_stream, dialect)
    newline_offsets = [i for i, ch in enumerate(text) if ch == "\n"]

    def _line_of(offset: int) -> int:
        lo, hi = 0, len(newline_offsets)
        while lo < hi:
            mid = (lo + hi) // 2
            if newline_offsets[mid] < offset:
                lo = mid + 1
            else:
                hi = mid
        return lo + 1

    out: list[dict[str, Any]] = []
    pos = 0
    while True:
        m = _DECLARE_TABLE.search(text, pos)
        if not m:
            break
        pos = m.end()
        if _inside_literal(text, m.start()):
            continue
        open_at = m.end() - 1
        close = _balanced_close(text, open_at)
        if close < 0:
            continue
        pos = close + 1
        table = _qualified_name(m.group(1))
        table_line = _line_of(m.start())
        body_start = open_at + 1
        body = _strip_sql_comments(text[body_start:close])
        colno = 0
        for offset, element in _split_top_level(body):
            col = _column(element)
            if col is None:
                continue
            colno += 1
            line = _line_of(body_start + offset + col.pop("offset"))
            out.append({"table": table, "table_line": table_line, "colno": colno, **col, "line": line})
    return out
