#!/usr/bin/env python3
# ==============================================================================
# GitGalaxy Tool: Zero-Trust JCL Generator
#
# PURPOSE:
# Generates deterministic Job Control Language (JCL) scripts directly from
# extracted COBOL structural intent.
#
# ARCHITECTURAL DECISION:
# Modernizing mainframe workloads requires mapping legacy file assignments
# (SELECT/ASSIGN) to modern cloud infrastructure. This generator enforces
# a Zero-Trust data allocation model by strictly matching the JCL definitions
# to the mathematically verified I/O intent extracted during static analysis,
# preventing over-permissioned datasets.
# ==============================================================================
import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

_FILE_ASSIGN_ANCHOR = re.compile(
    r"SELECT\s+([A-Z0-9\-]+)\s+ASSIGN\s+(?:TO\s+)?([A-Z0-9\-]+)",
    re.IGNORECASE,
)


def analyze_cobol_intent(filepath: Path) -> dict:
    """Extracts execution intent and data boundaries from legacy source code."""
    intent: dict[str, Any] = {
        "program_id": "UNKNOWN",
        "files_requested": [],
        "is_cics": False,
        "is_db2": False,
        "cics_calls": 0,
        "sql_calls": 0,
    }

    try:
        raw_content = filepath.read_text(encoding="utf-8", errors="ignore")

        # 1. FORMAT NORMALIZER: Strip legacy margin formatting
        clean_lines = []
        for line in raw_content.splitlines():
            if len(line) > 6 and line[6] in ("*", "/"):
                continue
            clean_lines.append(line[7:] if len(line) > 7 else line)

        monolith_code = " ".join(clean_lines)

        # 2. EXTRACT PROGRAM-ID (With fallback to file name)
        prog_id_match = re.search(r'PROGRAM-ID\.\s+[\'"]?([A-Z0-9\-]+)[\'"]?', monolith_code, re.IGNORECASE)
        if prog_id_match:
            intent["program_id"] = prog_id_match.group(1).strip()
        else:
            intent["program_id"] = filepath.stem.upper()

        # 3. BATCH I/O: Extract all File Assignments
        # #3222: the pattern used to carry the rest of the statement as
        # `[^.]*\.`, which rescans to the next period from every SELECT (the
        # #3205 shape). The terminator is still required -- an ASSIGN with no
        # period after it is not a statement -- but it is now found with
        # str.find, which visits each character once.
        consumed = 0
        for match in _FILE_ASSIGN_ANCHOR.finditer(monolith_code):
            if match.start() < consumed:
                continue
            stop = monolith_code.find(".", match.end())
            if stop == -1:
                continue
            consumed = stop + 1
            internal_name = match.group(1).strip()
            raw_dd = match.group(2).strip()
            clean_dd = re.sub(r"^(?:UT|UR)-S-", "", raw_dd)
            intent["files_requested"].append({"internal": internal_name, "dd_name": clean_dd})

        # 4/5. TRANSACTIONAL + DATABASE I/O: count EXEC CICS / EXEC SQL statements by
        # their opening keywords. Matching a whole `EXEC ... END-EXEC.` body lazily
        # merged every block that ends without a period (inside IF/EVALUATE) into the
        # next one, and ran an unbounded lazy quantifier over the joined file (#3205).
        cics_calls = len(re.findall(r"\bEXEC\s+CICS\b", monolith_code, re.IGNORECASE))
        if cics_calls:
            intent["is_cics"] = True
            intent["cics_calls"] = cics_calls

        sql_calls = len(re.findall(r"\bEXEC\s+SQL\b", monolith_code, re.IGNORECASE))
        if sql_calls:
            intent["is_db2"] = True
            intent["sql_calls"] = sql_calls

    except Exception as e:
        print(f"  [!] Intent Extraction Error on {filepath.name}: {e}")

    return intent


def generate_zero_trust_jcl(
    intent: dict,
    job_name: str,
    account_code: str,
    lineage: Optional[dict] = None,
    corporate_header: str = "",
) -> str:
    """Generates a strict, permission-bounded JCL deployment script."""
    if lineage is None:
        lineage = {"inputs": set(), "outputs": set()}
    prog_name = intent["program_id"]
    jcl = []

    jcl.append(f"//{job_name} JOB ({account_code}),'GITGALAXY GENERATOR',")
    jcl.append("//             CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1),")
    jcl.append("//             USER=HERC01,PASSWORD=CUL8TR,")
    jcl.append("//             TIME=10,REGION=4M")
    jcl.append("//* ==========================================================")
    jcl.append("//* AUTOGENERATED BY GITGALAXY ZERO-TRUST GENERATOR")

    if corporate_header:
        jcl.extend(f"//* {line}" for line in corporate_header.strip().split("\n"))

    arch_flags = []
    if intent["is_cics"]:
        arch_flags.append("CICS")
    if intent["is_db2"]:
        arch_flags.append("DB2")
    if arch_flags:
        jcl.append(f"//* ARCHITECTURE REQUIRES: {' + '.join(arch_flags)}")

    jcl.append("//* ==========================================================")
    jcl.append(f"//STEP01   EXEC PGM={prog_name}")
    jcl.append("//STEPLIB  DD DSN=HERC01.LOADLIB,DISP=SHR")
    jcl.append("//SYSOUT   DD SYSOUT=*")
    jcl.append("//SYSPRINT DD SYSOUT=*")
    jcl.append("//SYSUDUMP DD SYSOUT=*")

    if intent["files_requested"]:
        jcl.append("//* --- EXTRACTED FILE INTENT BOUNDARIES ---")
        for file in intent["files_requested"]:
            raw_dd = file["dd_name"]
            dd = re.sub(r"[^A-Z0-9]", "", raw_dd.upper())
            if len(dd) > 8:
                dd = dd[-8:]

            if raw_dd in lineage.get("outputs", set()):
                disp = "(NEW,CATLG,DELETE)"
            elif raw_dd in lineage.get("inputs", set()):
                disp = "SHR"
            else:
                disp = "SHR"

            jcl.append(f"//{dd.ljust(8)} DD DSN=HERC01.DATA.{dd},")
            if "NEW" in disp:
                jcl.append(f"//             DISP={disp},")
                jcl.append("//             UNIT=SYSDA,")
                jcl.append("//             SPACE=(CYL,(5,1),RLSE),")
                jcl.append("//             DCB=(LRECL=80,RECFM=FB,BLKSIZE=800)")
            else:
                jcl.append(f"//             DISP={disp}")
                # DEFENSIVE DESIGN: Flag datasets missing explicit initialization logic
                if "SHR" in disp and raw_dd not in lineage.get("inputs", set()):
                    jcl.append(f"//* WARNING: NO EXPLICIT OPEN INTENT FOR {dd}")
    jcl.append("//")
    return "\n".join(jcl)


def main():
    from gitgalaxy.licensing import enforce_licensing_guard

    enforce_licensing_guard("Zero-Trust JCL Generator")

    parser = argparse.ArgumentParser(description="GitGalaxy Zero-Trust JCL Generator (v5)")
    parser.add_argument("target", help="Target directory or specific COBOL file")
    parser.add_argument("--job", default="GITGJOB", help="Job name for the generated JCL")
    parser.add_argument("--acct", default="12345", help="Account code for the generated JCL")
    parser.add_argument(
        "--out",
        type=str,
        help="Output directory (default: isolated timestamped folder)",
    )
    args = parser.parse_args()

    target_path = Path(args.target).resolve()

    if target_path.is_dir():
        extensions = ("*.cbl", "*.CBL", "*.cob", "*.COB", "*.ccp", "*.CCP")
        cobol_files = []
        for ext in extensions:
            cobol_files.extend(target_path.rglob(ext))
    else:
        cobol_files = [target_path]

    if not cobol_files:
        print(f"\n[!] ERROR: No COBOL source files found in: {target_path}")
        sys.exit(1)

    # --- ISOLATED OUTPUT ROUTING ---
    if args.out:
        out_dir = Path(args.out).resolve()
    else:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        if target_path.is_dir():
            out_dir = target_path.parent / f"{target_path.name}_generated_{timestamp}"
        else:
            out_dir = target_path.parent / f"generated_jcls_{timestamp}"

    out_dir.mkdir(parents=True, exist_ok=True)

    print("\n==============================================================")
    print(" 🚀 GitGalaxy Tool: Zero-Trust JCL Generator (v5)")
    print("==============================================================")
    print(f" [*] Target Path : {target_path}")
    print(f" [*] Output Dir  : {out_dir}")
    print(f" [*] Files Found : {len(cobol_files)}")
    print("--------------------------------------------------------------")

    success_count = 0
    for file_path in cobol_files:
        intent = analyze_cobol_intent(file_path)
        jcl_output = generate_zero_trust_jcl(intent, args.job[:8].upper(), args.acct)

        # Output strictly locked to the designated isolated folder
        out_path = out_dir / f"{intent['program_id']}.jcl"
        out_path.write_text(jcl_output, encoding="utf-8")

        io_parts = []
        if len(intent["files_requested"]) > 0:
            io_parts.append(f"{len(intent['files_requested'])} Batch I/O")
        if intent["cics_calls"] > 0:
            io_parts.append(f"{intent['cics_calls']} CICS")
        if intent["sql_calls"] > 0:
            io_parts.append(f"{intent['sql_calls']} SQL")

        io_str = f"({', '.join(io_parts)})" if io_parts else "(No I/O)"

        print(f"  [+] Generated: {file_path.name.ljust(15)} -> {out_path.name.ljust(15)} {io_str}")
        success_count += 1

    print("--------------------------------------------------------------")
    print(f" [✓] Done! Successfully generated {success_count} JCL(s).")
    print("==============================================================\n")


if __name__ == "__main__":
    main()
