# ==============================================================================
# GitGalaxy Tool: verified skeleton export (#3614)
#
# PURPOSE:
# Hands what the engine extracted about each program -- its entry transactions,
# calls and their contracts, the CICS / DB2 / MQ / IMS / VSAM resources it
# touches, its screens, records, data moves, units of work and error handlers --
# to the code generators as one JSON file per program, so they build from the
# audited facts instead of re-deriving them from source.
#
#     06_skeleton/<key>_skeleton.json    one per refracted program
#     06_skeleton/estate.json            the estate-wide joins + completeness
#
# Every section names the ground-truth ledger field it comes from and carries
# that field's FIELD-TESTING record (gitgalaxy/standards/fact_channel_confidence.json,
# generated by tests/tools/field_testing.py): `field-tested`, `open` or
# `untested`, with the number of public and private estates it was tested on.
# A consumer reads `open` as "cross-verified on the keyed corpora, still finding
# defects on fresh estates": check it. The export states facts; it never fills
# a gap with a guess, and an empty section means the engine found nothing.
# ==============================================================================
from __future__ import annotations

import json
from dataclasses import asdict, is_dataclass
from importlib import resources
from pathlib import Path
from typing import Any

from gitgalaxy.tools.cobol_to_cobol.galaxy_ir import EngineFile, GalaxyIR

SKELETON_VERSION = 1

# Per-program section -> (the EngineFile channel, the ground-truth ledger field it is checked as).
# data_moves is left out: the data_flows join below carries every move with its resolved byte spans.
FILE_CHANNELS = {
    "units": ("units", "units"),
    "calls": ("calls", "call targets"),
    "entry_points": ("entry_points", "CALL USING"),
    "datasets": ("datasets", "DD names"),
    "records": ("records", "record fields"),
    "transactions": ("transactions", "entry transactions"),
    "sql_tables": ("sql_tables", "DB2 table columns"),
    "sql_statements": ("sql_statements", "DB2 table access"),
    "cics_resources": ("cics_resources", "CICS resources"),
    "cics_tasks": ("cics_tasks", "CICS task control"),
    "job_submits": ("job_submits", "job submissions"),
    "mq_calls": ("mq_calls", "MQ calls"),
    "uow_handlers": ("uow_handlers", "units of work and handlers"),
    "file_control": ("file_control", "file control"),
    "dli_calls": ("dli_calls", "DL/I calls"),
    "web_services": ("web_services", "web services"),
}
# Joins across files, filtered to the rows that name the program -> the ledger field.
PROGRAM_JOINS = {
    "entry_transactions": ("transaction_map", "entry transactions"),
    "navigation": ("navigation", "entry transactions"),
    "commarea_contracts": ("commarea_contracts", "CICS resources"),
    "call_contracts": ("call_contracts", "CALL USING"),
    "dynamic_call_targets": ("dynamic_call_targets", "dynamic call targets"),
    "unresolved_calls": ("unresolved_calls", "call targets"),
    "remote_calls": ("remote_calls", "CICS resources"),
    "screen_bindings": ("screen_bindings", "BMS screen fields"),
    "cics_file_lineage": ("cics_file_lineage", "CICS resources"),
    "tdqueue_lineage": ("tdqueue_lineage", "CICS resources"),
    "async_tasks": ("async_tasks", "CICS task control"),
    "job_submissions": ("job_submissions", "job submissions"),
    "sql_table_access": ("sql_table_access", "DB2 table access"),
    "mq_queues": ("mq_queues", "MQ calls"),
    "units_of_work": ("units_of_work", "units of work and handlers"),
    "error_handlers": ("error_handlers", "units of work and handlers"),
    "unchecked_responses": ("unchecked_responses", "units of work and handlers"),
    "vsam_files": ("vsam_files", "file control"),
    "dataset_lineage": ("dataset_lineage", "JCL resolved DSNs"),
    "dataset_flows": ("dataset_flows", "JCL resolved DSNs"),
    "ims_calls": ("ims_calls", "DL/I calls"),
    "ims_access_check": ("ims_access_check", "IMS access check"),
    "data_flows": ("data_flows", "data moves"),
}
# The program's interface (GalaxyIR.program_interfaces): the layouts are record_data, COPY-expanded.
INTERFACE_FIELD = "record fields"
# The row keys that name a program's file in a join row.
_PROGRAM_KEYS = ("file", "program", "caller", "callee", "from", "to", "resolves_to", "submitter", "writer", "reader")
# Estate-wide joins (no single owning program) written to estate.json.
ESTATE_JOINS = {
    "job_steps": "JCL job flow",
    "job_dataset_flow": "JCL job flow",
    "job_dds": "JCL job flow",  # #3622: each job step's DD statements (PROC steps expanded)
    "csd_resources": "CSD resources",
    "cics_file_datasets": "CSD resources",
    "tdqueue_datasets": "CSD resources",
    "transaction_db2_plans": "CSD resources",
    "tdq_trigger_starts": "TD trigger starts",
    "queue_flows": "CICS resources",
    "container_flows": "CICS resources",
    "mq_flows": "MQ calls",
    "remote_resources": "CICS resources",
    "ims_segment_access": "IMS segment access",
    "vsam_stores": "VSAM defines",  # #3617: each cluster with its CSD files, AIXs and CICS + batch users
    "db2_tables": "DB2 table access",  # #3618: each table's DECLARE + every statement against it
}


def load_confidence() -> dict[str, dict[str, Any]]:
    """Per ledger field, its field-testing record (the shipped fact_channel_confidence.json)."""
    text = resources.files("gitgalaxy.standards").joinpath("fact_channel_confidence.json").read_text(encoding="utf-8")
    return json.loads(text)["fields"]


def _plain(value: Any) -> Any:
    """JSON-ready: dataclasses (EngineScreenField rows inside a join) become dicts."""
    if is_dataclass(value) and not isinstance(value, type):
        return _plain(asdict(value))
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)):
        items = [_plain(v) for v in value]
        return sorted(items, key=str) if isinstance(value, set) else items
    if isinstance(value, Path):
        return value.as_posix()
    return value


def _section(field: str, rows: Any, confidence: dict[str, dict[str, Any]]) -> dict[str, Any]:
    record = confidence.get(field, {})
    return {
        "ledger_field": field,
        "field_testing": record.get("status", "untested"),
        "tested_on_public": record.get("tested_on_public", 0),
        "tested_on_private": record.get("tested_on_private", 0),
        "facts": _plain(rows),
    }


def _names(row: dict[str, Any], path: str) -> bool:
    return any(row.get(key) == path for key in _PROGRAM_KEYS)


class SkeletonExporter:
    """Computes each join once, then slices it per program."""

    def __init__(self, ir: GalaxyIR, confidence: dict[str, dict[str, Any]] | None = None) -> None:
        self.ir = ir
        self.confidence = load_confidence() if confidence is None else confidence
        self._joins = {name: getattr(ir, method)() for name, (method, _) in PROGRAM_JOINS.items()}
        self._interfaces = ir.program_interfaces()

    def program(self, ef: EngineFile) -> dict[str, Any]:
        path = ef.file_path
        sections = {
            name: _section(field, getattr(ef, attr), self.confidence) for name, (attr, field) in FILE_CHANNELS.items()
        }
        for name, (_, field) in PROGRAM_JOINS.items():
            rows = [row for row in self._joins[name] if _names(row, path)]
            sections[name] = _section(field, rows, self.confidence)
        # #3615: the COMMAREA layout the program receives and the containers it reads / writes.
        # One mapping, not rows: `facts` is the program_interfaces() entry.
        interface = self._interfaces.get(path, {"commarea": None, "commarea_gap": None, "containers": []})
        sections["interface"] = _section(INTERFACE_FIELD, interface, self.confidence)
        return {
            "skeleton_version": SKELETON_VERSION,
            "source": {"db": self.ir.db_path.name, "repo": self.ir.repo_name, "commit": self.ir.commit_hash},
            "program": {
                "file": path,
                "language": ef.language,
                "program_ids": list(ef.program_ids),
                "total_loc": ef.total_loc,
                "copybooks": list(ef.copy_deps),
                "program_id_field_testing": self.confidence.get("program_id", {}).get("status", "untested"),
            },
            "sections": sections,
        }

    def estate(self) -> dict[str, Any]:
        sections = {
            name: _section(field, getattr(self.ir, name)(), self.confidence) for name, field in ESTATE_JOINS.items()
        }
        return {
            "skeleton_version": SKELETON_VERSION,
            "source": {"db": self.ir.db_path.name, "repo": self.ir.repo_name, "commit": self.ir.commit_hash},
            "inventory": self.ir.inventory(),
            "completeness": _plain(self.ir.completeness()),
            "api_surface": _plain(self.ir.api_surface()),
            "sections": sections,
        }


def write_skeletons(ir: GalaxyIR, program_keys: dict[str, str], out_dir: Path) -> int:
    """Writes <key>_skeleton.json for each program (repo-relative path -> output key) and
    estate.json; returns the number of program skeletons written."""
    out_dir.mkdir(parents=True, exist_ok=True)
    exporter = SkeletonExporter(ir)
    written = 0
    for rel, key in sorted(program_keys.items()):
        ef = ir.files.get(rel)
        if ef is None:
            continue
        (out_dir / f"{key}_skeleton.json").write_text(
            json.dumps(exporter.program(ef), indent=2, default=str), encoding="utf-8"
        )
        written += 1
    (out_dir / "estate.json").write_text(json.dumps(exporter.estate(), indent=2, default=str), encoding="utf-8")
    return written
