# ==============================================================================
# GitGalaxy
# Copyright (c) 2026 Joe Esquibel
#
# This source code is licensed under the PolyForm Noncommercial License 1.0.0.
# You may not use this file except in compliance with the License.
# A copy of the license can be found in the LICENSE file in the root directory
# of this project, or at https://polyformproject.org/licenses/noncommercial/1.0.0/
# ==============================================================================
# GENERATED by tests/tools/fidelity_table.py from the keyword-rosetta control corpus.
# Do not edit by hand -- rerun the tool; `--check` fails CI when this is stale.
# corpus: keyword-rosetta 6377eb5973b06ce91d35c18659e7bf584f7cef2e | engine_mode: full-precision
# generated: 2026-09-04
"""Per-language, per-signal Fidelity Coefficients: fc = min(1, planted / measured).

Scales the credit a detected hit earns so that identical planted defence earns identical
credit in every language (#2716). 1.0 means the rule reads exactly on plant, under-fires
(a rule to fix, never compensated), or the signal is ledgered n/a for the language.
"""

from __future__ import annotations

FIDELITY_PROVENANCE: dict[str, str] = {
    "corpus": "keyword-rosetta",
    "corpus_sha": "6377eb5973b06ce91d35c18659e7bf584f7cef2e",
    "engine_mode": "full-precision",
    "languages": "46",
    "signals": "19",
}

FIDELITY_SIGNALS: tuple[str, ...] = (
    "args",
    "branch",
    "class_start",
    "cleanup",
    "dead_code",
    "doc",
    "fragile_debt",
    "func_start",
    "globals",
    "high_risk_execution",
    "import",
    "io",
    "ownership",
    "planned_debt",
    "safety",
    "safety_bypasses",
    "state_mutation",
    "telemetry",
    "test",
)

FIDELITY_TABLE: dict[str, dict[str, float]] = {
    "abap": {},
    "ada": {"branch": 0.75},
    "agc_assembly": {"branch": 0.75},
    "apex": {"args": 0.7222, "state_mutation": 0.6667},
    "assembly": {"branch": 0.125, "state_mutation": 0.3333},
    "c": {"io": 0.75, "state_mutation": 0.4, "test": 0.6667},
    "cobol": {"globals": 0.6667},
    "cpp": {"branch": 0.75, "state_mutation": 0.6667},
    "csharp": {"branch": 0.75, "globals": 0.6667},
    "css": {},
    "dart": {},
    "dockerfile": {"func_start": 0.7647, "import": 0.75, "state_mutation": 0.5},
    "embedded_python": {"import": 0.4286, "safety": 0.5, "test": 0.6667},
    "fortran": {"branch": 0.75, "safety_bypasses": 0.6667, "state_mutation": 0.6667},
    "go": {"state_mutation": 0.4},
    "groovy": {"args": 0.6842},
    "haskell": {"args": 0.8667, "func_start": 0.8667, "safety": 0.6667, "safety_bypasses": 0.5, "state_mutation": 0.5},
    "html": {},
    "java": {},
    "javascript": {"io": 0.75},
    "jcl": {},
    "kotlin": {},
    "livecode": {"branch": 0.6, "state_mutation": 0.6667},
    "lua": {"io": 0.75},
    "m4": {"args": 0.7222, "state_mutation": 0.5},
    "makefile": {"branch": 0.75, "cleanup": 0.6667, "func_start": 0.9286},
    "markdown": {},
    "matlab": {"cleanup": 0.5, "state_mutation": 0.5},
    "objective-c": {"args": 0.619, "state_mutation": 0.6667},
    "perl": {"state_mutation": 0.5, "test": 0.6667},
    "php": {},
    "powershell": {"branch": 0.6, "state_mutation": 0.6667},
    "python": {},
    "ruby": {"branch": 0.75},
    "rust": {},
    "scala": {},
    "scheme": {"state_mutation": 0.6667},
    "shell": {"branch": 0.6, "globals": 0.6667},
    "solidity": {"ownership": 0.25, "state_mutation": 0.6667},
    "sqlite": {"branch": 0.6, "io": 0.3333},
    "swift": {"branch": 0.75},
    "tcl": {"branch": 0.75, "io": 0.4286, "state_mutation": 0.6667},
    "typescript": {"args": 0.8667, "safety": 0.6667},
    "yacc": {},
    "yaml": {},
    "zig": {},
}
