# ==============================================================================
# GitGalaxy
# Copyright (c) 2026 Joe Esquibel
#
# This source code is licensed under the PolyForm Noncommercial License 1.0.0.
# You may not use this file except in compliance with the License.
# A copy of the license can be found in the LICENSE file in the root directory
# of this project, or at https://polyformproject.org/licenses/noncommercial/1.0.0/
# ==============================================================================
# GENERATED by tests/tools/fidelity_table.py from the keyword-rosetta control corpus.
# Do not edit by hand -- rerun the tool; `--check` fails CI when this is stale.
# corpus: keyword-rosetta 83fd3487448e2830d473d5caee123e3ed950db60 | engine_mode: full-precision
# generated: 2026-09-18
"""Per-language, per-signal Fidelity Coefficients: fc = min(1, planted / measured).

Scales the credit a detected hit earns so that identical planted defence earns identical
credit in every language (#2716). 1.0 means the rule reads exactly on plant, under-fires
(a rule to fix, never compensated), or the signal is ledgered n/a for the language.
"""

from __future__ import annotations

FIDELITY_PROVENANCE: dict[str, str] = {
    "corpus": "keyword-rosetta",
    "corpus_sha": "83fd3487448e2830d473d5caee123e3ed950db60",
    "engine_mode": "full-precision",
    "languages": "51",
    "signals": "21",
}

FIDELITY_SIGNALS: tuple[str, ...] = (
    "args",
    "branch",
    "class_start",
    "cleanup",
    "dead_code",
    "doc",
    "fragile_debt",
    "func_start",
    "globals",
    "high_risk_execution",
    "import",
    "io",
    "ownership",
    "planned_debt",
    "safety",
    "safety_bypasses",
    "state_mutation",
    "telemetry",
    "test",
    "units_documented",
    "units_public",
)

FIDELITY_TABLE: dict[str, dict[str, float]] = {
    "abap": {"units_public": 0.9231},
    "ada": {"units_public": 0.9231},
    "agc_assembly": {},
    "apex": {},
    "assembly": {},
    "bms": {"units_public": 0.9231},
    "c": {"units_public": 0.9231},
    "cobol": {},
    "cpp": {},
    "csharp": {},
    "css": {"func_start": 0.9286, "units_documented": 0.5},
    "dart": {"units_public": 0.9231},
    "db2_sql": {},
    "dockerfile": {"func_start": 0.7647},
    "embedded_python": {"import": 0.4286, "state_mutation": 0.1333, "units_public": 0.9231},
    "fortran": {"safety_bypasses": 0.6667, "units_public": 0.9231},
    "go": {},
    "groovy": {},
    "haskell": {"args": 0.8667, "func_start": 0.8667, "safety_bypasses": 0.5, "units_documented": 0.5},
    "hlasm": {"units_public": 0.9231},
    "html": {},
    "java": {},
    "javascript": {},
    "jcl": {},
    "kotlin": {},
    "livecode": {"units_public": 0.9231},
    "lua": {"units_public": 0.9231},
    "m4": {"args": 0.65, "units_documented": 0.5},
    "makefile": {"func_start": 0.9286, "units_documented": 0.5, "units_public": 0.9231},
    "markdown": {},
    "matlab": {"units_public": 0.9231},
    "objective-c": {"units_public": 0.9231},
    "perl": {"units_public": 0.9231},
    "php": {},
    "pli": {"units_public": 0.9231},
    "powershell": {},
    "python": {"state_mutation": 0.0952, "units_public": 0.9231},
    "rexx": {},
    "ruby": {"state_mutation": 0.1818},
    "rust": {},
    "scala": {"units_public": 0.9231},
    "scheme": {},
    "shell": {},
    "solidity": {},
    "sqlite": {},
    "swift": {},
    "tcl": {},
    "typescript": {},
    "yacc": {},
    "yaml": {},
    "zig": {},
}
