 INSERT INTO CARDDEMO.TRANSACTION_TYPE
        (TR_TYPE,TR_DESCRIPTION)
 SELECT '01','PURCHASE'      FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '02','PAYMENT'       FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '03','CREDIT'        FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '04','AUTHORIZATION' FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '05','REFUND'        FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '06','REVERAL'       FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '07','ADJUSTMENT'    FROM SYSIBM.SYSDUMMY1

;
 INSERT INTO CARDDEMO.TRANSACTION_TYPE
        (TR_TYPE,TR_DESCRIPTION)
 VALUES ('08','FEE'),
        ('09','INTEREST'),
        ('10','CASH ADVANCE'),
        ('11','BALANCE TRANSFER'),
        ('12','OVERLIMIT FEE')
;
 INSERT INTO CARDDEMO.TRANSACTION_TYPE_CATEGORY
      (TRC_TYPE_CODE    ,
       TRC_TYPE_CATEGORY,
       TRC_CAT_DATA     )
 WITH DMY AS (SELECT * FROM SYSIBM.SYSDUMMY1)
 SELECT '01','0001','REGULAR SALES DRAFT'           FROM DMY UNION ALL
 SELECT '01','0002','REGULAR CASH ADVANCE'          FROM DMY UNION ALL
 SELECT '01','0003','CONVENIENCE CHECK DEBIT'       FROM DMY UNION ALL
 SELECT '01','0004','ATM CASH ADVANCE'              FROM DMY UNION ALL
 SELECT '01','0005','INTEREST AMOUNT'               FROM DMY UNION ALL
 SELECT '02','0001','CASH PAYMENT'                  FROM DMY UNION ALL
 SELECT '02','0002','ELECTRONIC PAYMENT'            FROM DMY UNION ALL
 SELECT '02','0003','CHECK PAYMENT'                 FROM DMY UNION ALL
 SELECT '03','0001','CREDIT TO ACCOUNT'             FROM DMY UNION ALL
 SELECT '03','0002','CREDIT TO PURCHASE BALANCE'    FROM DMY UNION ALL
 SELECT '03','0003','CREDIT TO CASH BALANCE'        FROM DMY UNION ALL
 SELECT '04','0001','ZERO DOLLAR AUTHORIZATION'     FROM DMY UNION ALL
 SELECT '04','0002','ONLINE PURCHASE AUTHORIZATION' FROM DMY UNION ALL
 SELECT '04','0003','TRAVEL BOOKING AUTHORIZATION'  FROM DMY UNION ALL
 SELECT '05','0001','REFUND CREDIT'                 FROM DMY UNION ALL
 SELECT '06','0001','FRAUD REVERSAL'                FROM DMY UNION ALL
 SELECT '06','0002','NON FRAUD REVERSAL'            FROM DMY UNION ALL
 SELECT '07','0001','SALES DRAFT CREDIT ADJUSTMENT' FROM DMY

;
