# ==============================================================================
# GitGalaxy
# Copyright (c) 2026 Joe Esquibel
#
# This source code is licensed under the PolyForm Noncommercial License 1.0.0.
# You may not use this file except in compliance with the License.
# A copy of the license can be found in the LICENSE file in the root directory
# of this project, or at https://polyformproject.org/licenses/noncommercial/1.0.0/
# ==============================================================================
import re
import math
import bisect
from collections import Counter, defaultdict
from typing import Any, Dict, List


class SecurityLens:
    """
    Static Application Security Testing (SAST) Engine.

    Identifies raw structural vulnerabilities (Regex Signatures, Shannon Entropy,
    and Data Flow Taint) and evaluates them against dynamically injected Policy Thresholds
    augmented by Network Centrality metrics.
    """

    def __init__(self, policy=None):

        # DEFENSIVE GUARD: ReDoS Prevention
        # Extracts string literals for entropy scanning. Bounded to 64-1024 chars
        # using a non-greedy matcher to prevent catastrophic backtracking on minified files.
        self.string_extractor = re.compile(r'(["\'])([^\n]{64,1024}?)\1')

        # ---> THE AUTO-GEN SHIELD <---
        # Bypasses strict security/entropy checks on machine-generated files (Swagger, ESLint disables)
        self.auto_gen_shield = re.compile(
            r"(?:/\*\s*eslint-disable\s*\*/|@generated|DO NOT EDIT|Auto-generated by|generated by swagger|machine generated)",
            re.I,
        )

        # ---> BINARY MAGIC BYTE CONSTANTS <---
        # Used by the scan_binary method to verify file extension integrity
        self.MAGIC_BYTES = {
            ".png": b"\x89PNG\r\n\x1a\n",
            ".jpg": b"\xff\xd8\xff",
            ".jpeg": b"\xff\xd8\xff",
            ".xz": b"\xfd7zXZ\x00",
            ".gz": b"\x1f\x8b",
            ".pdf": b"%PDF-",
            ".zip": b"PK\x03\x04",
        }

        self.THREAT_HEADERS = [
            b"\x7fELF",  # Linux Executable
            b"MZ",  # Windows Executable
            b"#!/bin/",  # Shell Script
            b"\x00asm",  # WebAssembly
            b"\xcf\xfa\xed\xfe",  # macOS Mach-O
        ]

        # ------------------------------------------------------------------
        # RAW SENSORS (Vulnerability Signatures)
        # ------------------------------------------------------------------
        self.THREAT_SIGNATURES = {
            # 1. Obfuscation & Encoding Signatures
            "reflection_metaprogramming": re.compile(
                r"\b(?:atob|btoa|base64_decode|base64_encode|gzuncompress|str_rot13)\b|"
                r"\\x[0-9a-fA-F]{2}|\\u[0-9a-fA-F]{4}|"
                r'(?:\w{15,}[ \t]*=[ \t]*["\'][A-Za-z0-9+/]{40,}={0,2}["\'])|'
                r"[\u200B-\u200D\uFEFF\u200E\u200F\u202A-\u202E]",  # Invisible Unicode
                re.I,
            ),
            # 2. Security Control & Safety Bypasses (e.g., Disabling SSL Verification)
            "safety_bypasses": re.compile(
                r"\b(?:atob|btoa|base64_decode|gzinflate|gzuncompress|str_rot13|urldecode)[ \t]*\([ \t]*(?:atob|btoa|base64_decode|gzinflate|gzuncompress|str_rot13|urldecode)\b|"
                r"\b(?:auto_prepend_file|auto_append_file)\b|"
                r'\b(?:ini_set|ini_restore|putenv)[ \t]*\([ \t]*["\'](?:disable_functions|safe_mode|open_basedir|allow_url_fopen)["\'][ \t]*,[ \t]*["\']?(?:0|off|false|)["\']?[ \t]*\)|'
                r'\b(?:disable_functions|safe_mode|open_basedir)\b[ \t]*=[ \t]*(?:off|0|false|""|\'\')|'
                r'process[ \t]*\.[ \t]*env[ \t]*\.[ \t]*NODE_TLS_REJECT_UNAUTHORIZED[ \t]*=[ \t]*["\']?0["\']?|'
                r"\b(?:verify|strictSSL|rejectUnauthorized|CURLOPT_SSL_VERIFYPEER)[ \t]*[=:,][ \t]*(?:False|false|0)\b",
                re.I,
            ),
            # 3. Network & I/O Exfiltration Vectors
            "io": re.compile(
                r"\b(?:fetch|XMLHttpRequest|WebSocket|http\.request|https\.request|requests\.(?:post|put|get)|urllib\.request\.urlopen)\b\s*\(|"
                r"\b(?:curl_exec|fsockopen|pfsockopen|stream_socket_client|file_get_contents)\b\s*\(|"
                r"\b(?:dns_get_record|gethostbyname|socket\.gethostbyname|resolve(?:4|6|Cname|Txt)?)\b\s*\(|"
                r"(?:https?|ftp|tcp|udp|wss?):\/\/(?:(?:\d{1,3}\.){3}\d{1,3}|\[[0-9a-fA-F:]+\]|.*?\.(?:ngrok\.io|ngrok-free\.app|localtunnel\.me|pastebin\.com|workers\.dev|s3\.amazonaws\.com|requestbin\.net|pipedream\.net))",
                re.I | re.X,
            ),
            # 4. Dynamic Code Execution (RCE Vectors)
            "high_risk_execution": re.compile(
                r"\b(?:BPXBATCH|IKJEFT01|IRXJCL)\b|"
                r"\bEXEC\s+CICS\s+(?:START|LINK\s+PROGRAM|XCTL)\b\s*\(\s*[A-Za-z_-]+\s*\)|"
                r'\b(?:eval|Function|setTimeout|setInterval)\b\s*\(\s*(?:atob|base64_decode|gzinflate|\$|_[a-zA-Z]|["\']|`)|'
                r"\b(?:document\.write|location\.replace|assert|create_function|passthru|shell_exec|system)\b|"
                r"child_process\.(?:exec|spawn|fork)|"
                r'(?:window|global|this|globalThis)\[[ \t]*(?:["\'][a-zA-Z]["\'][ \t]*\+[ \t]*){1,15}["\'][a-zA-Z]["\'][ \t]*\][ \t]*\(|'
                r"\$[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*\s*\(\s*\$_(?:POST|GET|COOKIE|REQUEST|HEADERS)|"
                r"getattr\s*\(\s*__import__\s*\(|importlib\.import_module\s*\(|\brequire\s*\(\s*(?!['\"])[a-zA-Z_$]|__builtins__\[|Assembly\.Load\s*\(|"
                r"\$\{\{\s*github\.event\.(?:issue|pull_request|comment|review|push\.commits).*?\}\}",
                re.I | re.X,
            ),
            # 5. Prototype Pollution & Global State Flux
            "state_mutation": re.compile(
                r"\b[A-Za-z0-9_]+[ \t]*\.[ \t]*prototype[ \t]*\.[ \t]*[A-Za-z0-9_]+[ \t]*=|"
                r"\.[ \t]*__proto__[ \t]*=[ \t]*[{a-zA-Z]|"
                r"\b(?:window|global|globalThis|document)[ \t]*\.[ \t]*(?:fetch|eval|setTimeout|setInterval|Promise|console|JSON)[ \t]*=|"
                r"\$(?:GLOBALS|_(?:SERVER|GET|POST|COOKIE|REQUEST|ENV|SESSION))[ \t]*\[[^\]]+\][ \t]*=[ \t]*[^=]|"
                r"\bextract[ \t]*\([ \t]*\$(?:_(?:GET|POST|REQUEST|COOKIE)|GLOBALS)\b|"
                r"\b__builtins__[ \t]*\[[^\]]+\][ \t]*=|"
                r"\bsys[ \t]*\.[ \t]*modules[ \t]*\[[^\]]+\][ \t]*=",
                re.I,
            ),
            # 6. Commented-out Executable Logic (Deprecated Trails)
            "dead_code": re.compile(
                r"(?://|#|--|\*>|^.{6}\*)[^\n]*?\b(?:http|bash|curl|wget|eval|base64|nc\s+-e|/dev/tcp|BPXBATCH)\b|"
                r"/\*(?:(?!\*/).){0,500}?\b(?:http|bash|curl|wget|eval|base64|nc\s+-e|/dev/tcp)\b",
                re.I,
            ),
            # 7. Low-Level Cryptographic & Bitwise Operations
            "bitwise_ops": re.compile(
                r"\b\w+[ \t]*=[ \t]*(?:\w+[ \t]*\^[ \t]*\w+[ \t]*){2,20}|"
                r"(?:\w+\[[^\]\n]{1,50}\][ \t]*\^[ \t]*=?[ \t]*(?:0x[0-9a-fA-F]+|\d+|\w+)[ \t]*;[ \t]*){3,20}",
                re.I,
            ),
            # 8. Steganographic Payload Imports
            "shadow_imports": re.compile(
                r"\b(?:require|include|import|require_once|include_once|source|load|dofile)\b\s*\(?\s*"
                r'["\'][^"\']+\.(?:png|jpg|jpeg|gif|ico|pdf|zip|tar|dat|tmp|log|txt|csv|wav|mp3)["\']',
                re.I,
            ),
            # 9. Unicode Homoglyphs & Typosquatting
            "homoglyphs": re.compile(
                r"\b(?:import|from|require|include|require_once|fetch|XMLHttpRequest)\b"
                r"[^\n]*?(?:[\u0400-\u04FF]|"
                r"[\u0370-\u03FF]|"
                r"[\U0001D400-\U0001D7FF]|"
                r"\u3164)",
                re.I,
            ),
            # 10. Hardcoded Secrets & Credentials
            "hardcoded_secrets": re.compile(
                r"\b(password|secret|token|api[_-]?key|client[_-]?secret|credentials|private[_-]?key|auth[_-]?token)\b[ \t]*(?:[:=]|=>)[ \t]*[\"'][A-Za-z0-9\-_+/=]{16,}[\"']|"
                r"\b(PASSWORD|SECRET|TOKEN|KEY|CREDENTIALS)[A-Za-z0-9_-]*\b[ \t]+(?:IS[ \t]+)?(?:PIC[ \t]+[A-Za-z0-9\-\(\)]+[ \t]+)?VALUE[ \t]+['\"][^'\"]+['\"]|"
                r"-----BEGIN (?:RSA |DSA |EC |OPENSSH |PGP )?(?:PRIVATE KEY|MESSAGE|CERTIFICATE)-----|"
                r"\b(?:sk_live|rk_live)_[0-9a-zA-Z]{24,99}\b|"
                r"\bghp_[0-9a-zA-Z]{36}\b|"
                r"\bxox[baprs]-[0-9a-zA-Z]{10,48}\b|"
                r"\bAIza[0-9A-Za-z\-_]{35}\b|"
                r"\b(?:AKIA|ABIA|ACCA|ASIA)[0-9A-Z]{16}\b|"
                r"ssh-(?:rsa|ed25519)[ \t]+[A-Za-z0-9+/]+[=]{0,2}",
                re.I,
            ),
            # 11. Raw Memory Overrides & Corruption Vectors
            "memory_corruption": re.compile(
                r"\bEXEC\s+CICS\s+(?:GETMAIN|FREEMAIN)\b|"
                r"\bSET\s+ADDRESS\s+OF\b|"
                r"\b(?:malloc|calloc|realloc|free|memcpy|memset|memmove|strcpy|strcat|sprintf)\b\s*\(|"
                r"\b(?:asm|__asm__|__asm)\b\s*[\(\{]",
                re.I,
            ),
            # 12. Agentic RCE & Prompt Injection Boundaries
            "llm_hooks": re.compile(
                r"\b(?:openai|anthropic|cohere|litellm|langchain|llama_index|bedrock|chat\.completions\.create|invoke|generate)\b",
                re.I,
            ),
            # 13. Raw Database Sinks
            "db_hooks": re.compile(
                r"\b(?:execute|query|raw|cursor|execute_sql|executeBatch|query_db)\b\s*\(",
                re.I,
            ),
        }

    def _calculate_shannon_entropy(self, data: str) -> float:
        """
        Calculates the Shannon Entropy of a string to identify base64/encrypted blobs.
        Mathematical Optimization: Refactored the standard formula `math.log2(L) - sum(c * math.log2(c)) / L`
        to execute the division operation completely outside the loop.
        """
        if not data:
            return 0.0

        length = len(data)
        frequencies = Counter(data)

        sum_c_log_c = sum(c * math.log2(c) for c in frequencies.values())
        return math.log2(length) - (sum_c_log_c / length)

    def scan_content(self, content: str, loc: int) -> dict:
        """
        Executes primary regex scanning, entropy calculation, and multi-line data flow taint tracking.
        """
        counts: Dict[str, int] = {}
        snippets: Dict[str, List[str]] = {}

        safe_lines = [line.strip() for line in content.splitlines() if len(line) < 250]
        safe_content = "\n".join(safe_lines)

        # ---> MINIFICATION & OBFUSCATION FALLBACK SCREEN <---
        # If the 250-character anti-ReDoS shield stripped out more than 90% of the file, 
        # it is minified. We perform a blazing fast O(N) literal string search on the 
        # raw buffer to catch blatant execution hooks without triggering regex timeouts.
        if len(safe_content) < (len(content) * 0.1):
            fast_screen = {
                "high_risk_execution": ["eval(", "setTimeout(", "child_process", "shell_exec("],
                "io": ["XMLHttpRequest", "fetch(", "http.request"],
                "safety_bypasses": ["NODE_TLS_REJECT_UNAUTHORIZED", "disable_functions"]
            }
            for key, literals in fast_screen.items():
                for lit in literals:
                    # Use a fast word-boundary regex to prevent substring hallucination
                    # e.g., prevents "fetch(" from matching inside "prefetch("
                    if re.search(rf"\b{re.escape(lit)}", content):
                        counts[key] = counts.get(key, 0) + 1
                        snippets.setdefault(key, []).append(f"[Minified Literal Hit]: {lit}")

        is_auto_gen = bool(self.auto_gen_shield.search(content[:2000]))

        # PERFORMANCE OPTIMIZATION: O(1) Offset Map for Taint Analysis
        # Only tracks lines where an actual threat signature triggered, skipping blank space.
        threat_lines = defaultdict(set)
        # Line positions for the four signals below, keyed the same way
        # detector.py's own threat_locations are (rule_name -> [1-indexed line
        # numbers]) -- exposed via scan_content()'s return so galaxyscope.py can
        # fold them into the shared, persisted ledger (#348). Previously this
        # position data was computed (via threat_lines above) but only ever
        # used internally for this function's own taint check, then discarded.
        positions: Dict[str, List[int]] = defaultdict(list)
        if not is_auto_gen:
            line_starts = [0] + [m.end() for m in re.finditer(r"\n", safe_content)]

        for key, regex in self.THREAT_SIGNATURES.items():
                if is_auto_gen and key == "homoglyphs":
                    counts.setdefault(key, 0)
                    snippets.setdefault(key, [])
                    continue

                # Ensure we add to the fallback screen hits rather than overwriting them.
                # (Applying the safe_content patch here to ensure ReDoS armor remains intact).
                new_hits = regex.findall(safe_content)
                counts[key] = counts.get(key, 0) + len(new_hits)
                snippets.setdefault(key, [])

                if len(new_hits) > 0:
                    for match in regex.finditer(safe_content):
                        snip = match.group(0).strip()
                        if len(snippets[key]) < 3 and snip not in snippets[key]:
                            snippets[key].append(snip)

                        # Map the exact line indexes of critical threats for the Taint Tracker
                        if not is_auto_gen and key in {
                            "io",
                            "high_risk_execution",
                            "llm_hooks",
                            "db_hooks",
                            "hardcoded_secrets",
                        }:
                            line_idx = bisect.bisect_right(line_starts, match.start()) - 1
                            threat_lines[line_idx].add(key)
                            positions[key].append(line_idx + 1)  # 1-indexed, matching detector.py's convention

        # ---> 3. SHANNON ENTROPY (Obfuscation Detection) <---
        entropy_hits = 0
        entropy_snippets: List[str] = []

        if is_auto_gen:
            counts["entropy"] = 0
            snippets["entropy"] = []
        else:
            for match in self.string_extractor.finditer(safe_content):
                extracted_string = match.group(2)
                # Ensure it's dense data, not prose (checking for spaces)
                if extracted_string.count(" ") < 3:
                    entropy = self._calculate_shannon_entropy(extracted_string)
                    if entropy > 4.8:
                        entropy_hits += 1
                        if len(entropy_snippets) < 3:
                            entropy_snippets.append(extracted_string[:60] + "...")

            counts["entropy"] = entropy_hits
            snippets["entropy"] = entropy_snippets

        # ---> 4. DATA FLOW & TAINT TRACKING (O(H) Offset Mapper) <---
        taint_hits = 0
        prompt_injection_hits = 0
        agentic_rce_hits = 0
        taint_snippets: List[str] = []

        has_global_io = counts.get("io", 0) > 0
        has_global_danger = counts.get("high_risk_execution", 0) > 0
        has_global_llm = counts.get("llm_hooks", 0) > 0
        has_global_db = counts.get("db_hooks", 0) > 0

        if (
            (has_global_io or has_global_llm)
            and (has_global_danger or has_global_llm or has_global_db)
            and not is_auto_gen
        ):
            tainted_vars = set()
            llm_tainted_vars = set()
            common_keywords = {
                "const",
                "let",
                "var",
                "def",
                "String",
                "int",
                "val",
                "final",
                "char",
                "bool",
                "auto",
                "global",
                "local",
                "new",
                "await",
            }

            # Only iterate over the specific lines that triggered an initial threat
            for line_idx in sorted(threat_lines.keys()):
                threats = threat_lines[line_idx]
                line = safe_lines[line_idx]

                has_io = "io" in threats
                has_danger = "high_risk_execution" in threats
                has_llm = "llm_hooks" in threats
                has_db = "db_hooks" in threats

                # Scenario A: Same-Line Detonation
                if has_io and (has_danger or has_db):
                    taint_hits += 1
                    if len(taint_snippets) < 3:
                        taint_snippets.append(f"[I/O -> Exec/DB]: {line[:60]}...")
                if has_io and has_llm:
                    prompt_injection_hits += 1
                    if len(taint_snippets) < 3:
                        taint_snippets.append(f"[I/O -> LLM]: {line[:60]}...")
                if has_llm and has_danger:
                    agentic_rce_hits += 1
                    if len(taint_snippets) < 3:
                        taint_snippets.append(f"[LLM -> RCE]: {line[:60]}...")

                # Scenario B: Left-Hand Side (LHS) Assignment Extraction
                if has_io or has_llm:
                    # Prevent splitting on comparison operators (==, ===, !=, !==, <=, >=)
                    if re.search(r"[=!<>]=", line):
                        assign_op = None
                    else:
                        assign_op = ":=" if ":=" in line else "=" if "=" in line else None
                        
                    if assign_op:
                        lhs = line.split(assign_op)[0]
                        possible_vars = re.findall(r"\b[a-zA-Z_]\w*\b", lhs)
                        for v in possible_vars:
                            if v not in common_keywords:
                                if has_io:
                                    tainted_vars.add(v)
                                if has_llm:
                                    llm_tainted_vars.add(v)

                # Scenario C: Downward Flow Scan (Check Execution Sink)
                # Because execution requires a sink, the sink line MUST be in threat_lines!
                if (has_danger or has_db or has_llm) and (tainted_vars or llm_tainted_vars):
                    for t_var in tainted_vars:
                        # O(1) string check before running full regex
                        if t_var in line and re.search(rf"\b{re.escape(t_var)}\b", line):
                            if has_danger or has_db:
                                taint_hits += 1
                                if len(taint_snippets) < 3:
                                    taint_snippets.append(f"[Taint -> Exec/DB]: {line[:60]}...")
                            if has_llm:
                                prompt_injection_hits += 1
                                if len(taint_snippets) < 3:
                                    taint_snippets.append(f"[Taint -> LLM]: {line[:60]}...")

                    for l_var in llm_tainted_vars:
                        if l_var in line and re.search(rf"\b{re.escape(l_var)}\b", line) and has_danger:
                            agentic_rce_hits += 1
                            if len(taint_snippets) < 3:
                                taint_snippets.append(f"[LLM State -> RCE]: {line[:60]}...")

        counts["tainted_injection"] = taint_hits
        counts["prompt_injection"] = prompt_injection_hits
        counts["agentic_rce"] = agentic_rce_hits
        snippets["tainted_injection"] = taint_snippets
        snippets["prompt_injection"] = [s for s in taint_snippets if "LLM" in s]
        snippets["agentic_rce"] = [s for s in taint_snippets if "RCE" in s]

        return {"counts": counts, "snippets": snippets, "positions": dict(positions)}

    def scan_binary(self, raw_bytes: bytes, ext: str) -> dict:
        """
        Binary Magic Byte & Entropy Analyzer.
        Validates compiled chunks against expected magic bytes and scans for
        embedded execution headers or extreme cryptographic entropy indicating packed malware.
        """
        threats: Dict[str, Any] = {}

        if not raw_bytes:
            return threats

        expected_magic = self.MAGIC_BYTES.get(ext.lower())
        if expected_magic:
            if not raw_bytes.startswith(expected_magic):
                threats["sec_extension_mismatch"] = 1
                threats["threat_snippet"] = f"Expected {expected_magic}, found mismatch"

        for header in self.THREAT_HEADERS:
            if header in raw_bytes:
                threats["sec_high_risk_execution"] = 1
                threats["threat_snippet"] = f"Embedded execution header found: {header}"
                break

        try:
            length = len(raw_bytes)
            if length > 256:
                frequencies = Counter(raw_bytes)
                entropy = 0.0
                for count in frequencies.values():
                    probability = count / length
                    entropy -= probability * math.log2(probability)

                if entropy > 7.95:
                    threats["sec_reflection_metaprogramming"] = 1
                    threats["threat_snippet"] = f"Extreme binary entropy detected: {entropy:.2f}"
        except Exception:
            pass

        return threats
