"""#4559: Gate 4.3 matches generator BANNERS, not prose that mentions generation."""

import pytest

from gitgalaxy.core.aperture import ApertureFilter
from gitgalaxy.standards.gitgalaxy_config import APERTURE_CONFIG
from gitgalaxy.standards.language_standards import LANGUAGE_DEFINITIONS


@pytest.fixture
def engine(tmp_path):
    return ApertureFilter(root_dir=tmp_path, language_definitions=LANGUAGE_DEFINITIONS, aperture_config=APERTURE_CONFIG)


def _body(ext: str) -> str:
    """Varied, hand-written-looking code, long enough (>1000 LOC) that intent does not rescue it."""
    if ext == "rs":
        return "".join(f"pub fn handler_{i}(x: u32) -> u32 {{ x.wrapping_mul({i * 7 + 3}) ^ {i} }}\n" for i in range(1100))
    if ext == "go":
        return "".join(f"func handler{i}(x int) int {{ return x*{i * 7 + 3} + {i} }}\n" for i in range(1100))
    return "".join(f"def handler_{i}(x):\n    return x * {i * 7 + 3} + {i}\n" for i in range(600))


def _blocked(engine, tmp_path, name, header):
    path = tmp_path / name
    content = header + _body(name.rsplit(".", 1)[1])
    path.write_text(content, encoding="utf-8")
    return engine.is_in_scope(path, content=content)


PROSE = [
    ("wgpu.rs", "/// `params.x` fill modes; the shader's midpoint thresholds are generated by `surface_wgsl`.\n"),
    ("a.rs", "// The table below is automatically generated at startup, then cached.\n"),
    ("b.py", "# values are auto-generated by the caller before this runs\n"),
    ("c.go", "// Callers must not do not edit the returned slice (it is generated by Foo).\n"),
    ("d.py", "# See the schema; this file is generated nowhere, it is hand-written.\n"),
    # Regression: the old regex admitted these; a narrower-than-old banner must not newly block them.
    ("e.py", "# Generated from `data/PROVENANCE.json` by `tools/generate_sources.py`.\n"),
    ("f.py", "# Generated by: IBM Rational Developer for System z with Java\n"),
]

BANNERS = [
    ("g.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n"),
    ("p.py", "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n"),
    ("m.py", "# Generated by Django 4.2 on 2024-01-01\n"),
    ("at.rs", "// @generated\n"),
    ("ag.rs", "/* @generated by tool */\n"),
    ("au.py", "# <auto-generated>\n"),
    ("tf.py", "# Autogenerated by Thrift Compiler (0.19.0)\n"),
    ("fb.rs", "// automatically generated by the FlatBuffers compiler, do not modify\n"),
    ("sw.py", "# This file was automatically generated by SWIG (https://www.swig.org).\n"),
    ("bi.py", "/* A Bison parser, made by GNU Bison 3.8.2.  */\n"),
    ("fx.py", "/* A lexical scanner generated by flex */\n"),
    ("tg.py", "# This file is generated. Edit the template instead.\n"),
    ("tg2.py", "# This file is automatically generated using codegen.\n"),
    ("de.go", "// DO NOT EDIT\n"),
    ("de2.go", "//    do not edit this file\n"),
]


@pytest.mark.parametrize(("name", "line"), PROSE)
def test_prose_mentioning_generation_is_admitted(engine, tmp_path, name, line):
    result = _blocked(engine, tmp_path, name, line)
    assert result["is_in_scope"] is True, result


@pytest.mark.parametrize(("name", "line"), BANNERS)
def test_real_generator_banners_are_blocked(engine, tmp_path, name, line):
    result = _blocked(engine, tmp_path, name, line)
    assert result["is_in_scope"] is False
    assert "Machine-Generated Source Code Signature" in result["reason"], result
