"""#4365: Gate 4.3 (machine-generated source) excluded a checked-in BMS symbolic-map copybook --
`* SYMBOLIC MAP FOR MAPSET CUSTMS -- GENERATED BY BMS ASSEMBLY` -- so `COPY CUSTMS` lost its record
layout and resolved to the mapset (estate-crucible CUSTMS.cpy / GULFMS.cpy). A COBOL copy member is
text the compiler pastes into a program; its generator comment is how it was made, not noise."""

from gitgalaxy.core.aperture import ApertureFilter
from tests.core_engine.test_aperture import MOCK_CONFIG

SYMBOLIC_MAP = """\
      * SYMBOLIC MAP FOR MAPSET CUSTMS -- GENERATED BY BMS ASSEMBLY
       01  CUSTMAPI.
           02  FILLER                 PIC X(12).
           02  CUSTIDL                PIC S9(4) COMP.
           02  CUSTIDF                PIC X.
           02  CUSTIDI                PIC X(8).
"""


def _gate(tmp_path, name: str, content: str) -> dict:
    registry = {"cobol": {"extensions": [".cbl", ".cpy", ".dcl"], "exact_matches": []},
                "java": {"extensions": [".java"], "exact_matches": []}}  # fmt: skip
    engine = ApertureFilter(root_dir=tmp_path, language_definitions=registry, aperture_config=MOCK_CONFIG)
    path = tmp_path / name
    path.write_text(content, encoding="utf-8")
    return engine.is_in_scope(path, content=content)


def test_a_generated_symbolic_map_copybook_is_source(tmp_path):
    result = _gate(tmp_path, "CUSTMS.cpy", SYMBOLIC_MAP)
    assert result["is_in_scope"] is True, result["reason"]


def test_a_dclgen_member_is_source(tmp_path):
    dcl = "      * DCLGEN TABLE(CUST) ... IS DCLCUST -- GENERATED BY DCLGEN\n" + SYMBOLIC_MAP.split("\n", 1)[1]
    assert _gate(tmp_path, "DCLCUST.dcl", dcl)["is_in_scope"] is True


def test_generated_source_of_other_kinds_is_still_blocked(tmp_path):
    java = "// <auto-generated> do not edit\npublic class X {\n  int a;\n}\n"
    result = _gate(tmp_path, "X.java", java)
    assert result["is_in_scope"] is False and "Machine-Generated Source" in result["reason"]
