# ==============================================================================
# GitGalaxy Tool: porting tickets (#3752)
#
# One ticket per program whose generated service still has business logic to write --
# the migration worklist's business-logic items -- generated by default, so a person or
# an LLM the customer chooses can port that program onto the generated skeleton without
# re-deriving anything. A ticket (ai_agent_jobs/<KEY>_port_ticket.json, with a Markdown
# twin) holds:
#   target       the generated service to fill (its file, its public methods and the TODO
#                ones), the overlay path a port lands on, and the target config (Java /
#                Spring Boot / data classes / database ...) the port must follow;
#   source       the program's and its copybooks' numbered listings (columns 1-72), written
#                once each under ai_agent_jobs/sources/ and referenced, and its paragraphs
#                (name, first line, lines) from the engine's units;
#   facts        the verified skeleton sections that concern it, each with its field-testing
#                status (the #3614 ticket view: bulk data sections stay in the skeleton file);
#   generated    the generated classes it builds on: those the service imports (entities with
#                their record codecs, repositories, DTOs, the batch runtime) and every artifact
#                the traceability manifest ties to this program;
#   worklist     this program's worklist items;
#   rules        the porting rules the #3624 slice proved (storage semantics, behaviour kept);
#   deliverable  what to return and how the port is proven (tests/tools/equivalence.py).
# Deterministic: no timestamps, estate-relative paths, sorted keys.
# ==============================================================================
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from gitgalaxy.tools.cobol_to_java.cobol_to_java_agent_forge import ticket_skeleton
from gitgalaxy.tools.cobol_to_java.cobol_to_java_names import java_class_base

TICKET_VERSION = 1
PORTING_RULES = [
    (
        "Port the PROCEDURE DIVISION into the service's methods, paragraph by paragraph; name the paragraph "
        "each block ports in a comment, so the port can be reviewed against the source."
    ),
    (
        "Keep COBOL's storage semantics: COMPUTE / ADD / SUBTRACT / MULTIPLY / DIVIDE without ROUNDED "
        "truncate decimals; a result too long for its PICTURE loses its high-order digits (ON SIZE ERROR "
        "aside); MOVE to a numeric field aligns on the decimal point and truncates both ends; MOVE to "
        "alphanumeric pads with spaces or truncates on the right. Use BigDecimal with RoundingMode.DOWN, "
        "never double, for PIC 9 / COMP-3 data."
    ),
    (
        "Keep the program's behaviour, including what looks like a defect (an unreachable branch, a field "
        "never reset): the port is proven by comparing its outputs with the original's. Document each such "
        "spot with a comment naming the defect and the one-line fix; fixing it is a business decision, not a "
        "translation."
    ),
    (
        "Use the generated code as it is: entities and their fromRecord / toRecord codecs, repositories, "
        "DTOs, the batch runtime (DatasetResolver, Dd), the other services. Do not edit generated files other"
        " than this service; do not invent calls, files, queues or tables the facts do not name."
    ),
    (
        "An abend (a CALL to CEE3ABD, an unrecoverable file status) becomes an exception; a DISPLAY becomes a"
        " log line; the step's RETURN-CODE is runBatch's return value."
    ),
    (
        "A sequential dataset is fixed-length records (RECFM=FB): write each record's toRecord(...) bytes "
        "back to back, with no line separators, to the file DatasetResolver.path(dd) names; read it the same "
        "way."
    ),
    (
        "Decode and encode a numeric field held in record bytes or a text column (zoned with an overpunched "
        "sign, COMP-3, COMP) only through the generated CobolRecords (zoned / packed / binary and their put "
        "methods) or the entity codecs, never a hand-written decoder."
    ),
    (
        "Read the time only from the generated batch runtime's MainframeClock (now()), never from the "
        "system clock directly: it is how a run is pinned to be compared with the original."
    ),
    (
        "A fact whose field testing is not 'field-tested' is verified on reference estates but still being "
        "field-tested: where the source contradicts it, follow the source and say so in the port's notes."
    ),
]


def _source_text(path: Path) -> list[str]:
    """Numbered source lines, columns 1-72 (the sequence area dropped)."""
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return []
    return [f"{n:5d} | {line[:72].rstrip()}" for n, line in enumerate(lines, 1)]


# The batch-entry stub's javadoc names its porting TODO (cobol_to_java_batch_forge); its body is `return 0;`.
_STUB_DOC = "port the PROCEDURE DIVISION main line"


def _listing(file: str) -> str:
    """Where a source's numbered listing lives, relative to ai_agent_jobs/."""
    return f"sources/{file}.lst"


def _public_methods(java: str) -> list[dict[str, Any]]:
    """The service's public methods: signature, and whether its body is still a TODO."""
    out = []
    for m in re.finditer(r"^    public (?!class)([^=;{}()]+)\(([^)]*)\)\s*\{", java, re.M):
        body_start = m.end()
        depth, i = 1, body_start
        while i < len(java) and depth:
            depth += {"{": 1, "}": -1}.get(java[i], 0)
            i += 1
        body = java[body_start : i - 1]
        doc = java[max(0, java.rfind("/**", 0, m.start())) : m.start()]
        todo = "TODO" in body or (_STUB_DOC in doc and "return 0;" in body)
        out.append({"signature": f"public {m.group(1).strip()}({m.group(2).strip()})", "todo": todo})
    return out


def _imports(java: str, package: str) -> list[str]:
    """The project classes a generated file imports (entities, repositories, DTOs, batch runtime)."""
    return sorted(re.findall(rf"^import ({re.escape(package)}\.[\w.]+);", java, re.M))


def _class_path(fqcn: str) -> str:
    return "src/main/java/" + fqcn.replace(".", "/") + ".java"


def build_ticket(key: str, skeleton: dict[str, Any], java_dir: Path, package: str, source_root: Path | None,
                 manifest: dict[str, Any] | None, items: list[dict[str, Any]], target: dict[str, Any],
                 skeleton_file: str | None) -> dict[str, Any]:  # fmt: skip
    prog = skeleton.get("program", {})
    service = java_class_base(key) + "Service"
    service_rel = _class_path(f"{package}.service.{service}")
    java = (java_dir / service_rel).read_text(encoding="utf-8") if (java_dir / service_rel).is_file() else ""
    # Listings are written once per source (write_port_tickets), not per ticket: an include member is
    # shared by hundreds of programs (DSF). `listing` is relative to ai_agent_jobs/; None when unread.
    readable = source_root is not None and prog.get("file") and (source_root / prog["file"]).is_file()
    source: dict[str, Any] = {
        "program": {"file": prog.get("file"), "listing": _listing(prog["file"]) if readable else None},
        "copybooks": [{"file": c, "listing": _listing(c) if source_root and (source_root / c).is_file() else None}
                      for c in prog.get("copybooks", [])],
    }  # fmt: skip
    units = (skeleton.get("sections", {}).get("units") or {}).get("facts") or []
    paragraphs = [{"name": u.get("name"), "start_line": u.get("start_line"), "lines": u.get("loc")} for u in units]
    tied = sorted({(a["file"], a["symbol"]) for a in (manifest or {}).get("artifacts", [])
                   if any(str(f.get("source") or "").split(":")[0] == prog.get("file") for f in a.get("facts", []))})  # fmt: skip
    generated = {
        "imports": [{"class": c, "file": _class_path(c)} for c in _imports(java, package)],
        "traced_to_this_program": [{"file": f, "symbol": s} for f, s in tied],
    }
    methods = _public_methods(java)
    return {
        "ticket": f"PORT-{key}",
        "version": TICKET_VERSION,
        "status": "open",
        "program": {
            "key": key,
            "program_ids": prog.get("program_ids", []),
            "language": prog.get("language"),
            "file": prog.get("file"),
            "lines": prog.get("total_loc"),
        },
        "target": {
            "service": service,
            "file": service_rel,
            "overlay": f"port/service/{service}.java",
            "methods": methods,
            "methods_to_port": [m["signature"] for m in methods if m["todo"]],
            "config": target,
        },
        "source": source,
        "paragraphs": paragraphs,
        "facts": ticket_skeleton(skeleton, skeleton_file),
        "generated": generated,
        "worklist": [{k: it[k] for k in ("id", "category", "file", "line", "text")} for it in items],
        "rules": PORTING_RULES,
        "deliverable": {
            "return": (
                f"One complete Java file for {service_rel}: the same package, class name and public method "
                "signatures, with the TODO bodies ported (helper methods may be added)."
            ),
            "proof": (
                "The port is laid over the generated project as an overlay and proven by the equivalence "
                "harness (tests/tools/equivalence.py in GitGalaxy): the original runs under GnuCOBOL, the "
                "port on the same inputs, and every output record is compared field by field; a person "
                "approves the port with that report in hand."
            ),
        },
    }


def ticket_markdown(t: dict[str, Any]) -> str:
    p, tg = t["program"], t["target"]
    md = [f"# {t['ticket']}: port {p['key']} ({p['language']}, `{p['file']}`, {p['lines']} lines)", "",
          f"Fill `{tg['file']}` ({tg['service']}); return it as `{tg['overlay']}`.", "",
          "## Methods to port", ""]  # fmt: skip
    md += [f"- `{m}`" for m in tg["methods_to_port"]] or ["- (no method is marked as a TODO; see the worklist)"]
    md += ["", "## Target configuration", "", "```json", json.dumps(tg["config"], indent=2, sort_keys=True), "```"]
    md += ["", "## Porting rules", ""] + [f"{i}. {r}" for i, r in enumerate(t["rules"], 1)]
    md += ["", "## Worklist items for this program", ""]
    md += [f"- **{w['id']}** ({w['category']}) `{w['file']}:{w['line']}`: {w['text']}" for w in t["worklist"]]
    md += ["", "## Generated code it builds on", ""] + [f"- `{g['class']}`" for g in t["generated"]["imports"]]
    md += ["", "## Verified facts", ""]
    for name, sec in sorted(t["facts"].get("sections", {}).items()):
        md.append(f"- **{name}** ({sec.get('field_testing', 'untested')}): {len(sec.get('facts') or [])} facts")
    md += ["", "## Paragraphs", "", "| paragraph | line | lines |", "|---|---:|---:|"]
    md += [f"| {u['name']} | {u['start_line']} | {u['lines']} |" for u in t["paragraphs"]]
    md += ["", "## Deliverable", "", t["deliverable"]["return"], "", t["deliverable"]["proof"]]
    md += ["", "## Source listings (numbered, columns 1-72)", ""]
    for s_ in [t["source"]["program"], *t["source"]["copybooks"]]:
        md.append(f"- `{s_['file']}`: " + (f"[{s_['listing']}]({s_['listing']})" if s_["listing"] else "not read"))
    return "\n".join(md) + "\n"


def write_port_tickets(java_dir: Path, skeletons: dict[str, Path], worklist: dict[str, Any] | None,
                       manifest: dict[str, Any] | None, package: str, target: dict[str, Any],
                       ir_dir: Path | None, clean_room_name: str) -> dict[str, str]:  # fmt: skip
    """Write a ticket per program with business-logic worklist items; {program source: ticket path}."""
    items_by_file: dict[str, list[dict[str, Any]]] = {}
    for it in (worklist or {}).get("items", []):
        if it.get("nature") == "port":
            items_by_file.setdefault(str(it.get("program")), []).append(it)
    out_dir = java_dir / "ai_agent_jobs"
    written: dict[str, str] = {}
    for key, path in sorted(skeletons.items()):
        skeleton = json.loads(path.read_text(encoding="utf-8"))
        file = (skeleton.get("program") or {}).get("file")
        items = [it for f, its in items_by_file.items() if f == file for it in its]
        if not items:
            continue
        source_root = None
        ir_file = ir_dir / f"{key}_ir.json" if ir_dir else None
        if ir_file is not None and ir_file.is_file():
            src = (json.loads(ir_file.read_text(encoding="utf-8")).get("metadata") or {}).get("path")
            if src and file and src.replace("\\", "/").endswith(file):
                source_root = Path(src[: len(src) - len(file)])
        ticket = build_ticket(key, skeleton, java_dir, package, source_root, manifest, items, target,
                              f"{clean_room_name}/06_skeleton/{path.name}")  # fmt: skip
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{key}_port_ticket.json").write_text(json.dumps(ticket, indent=2, sort_keys=True) + "\n",
                                                         encoding="utf-8")  # fmt: skip
        (out_dir / f"{key}_port_ticket.md").write_text(ticket_markdown(ticket), encoding="utf-8")
        for s_ in [ticket["source"]["program"], *ticket["source"]["copybooks"]]:
            listing = out_dir / s_["listing"] if s_["listing"] else None
            if listing is not None and source_root is not None and not listing.exists():
                listing.parent.mkdir(parents=True, exist_ok=True)
                listing.write_text("\n".join(_source_text(source_root / s_["file"])) + "\n", encoding="utf-8")
        written[str(file)] = f"ai_agent_jobs/{key}_port_ticket.md"
    return written
