# ==============================================================================
# GitGalaxy Tool: porting tickets (#3752)
#
# One ticket per program whose generated service still has business logic to write --
# the migration worklist's business-logic items -- generated by default, so a person or
# an LLM the customer chooses can port that program onto the generated skeleton without
# re-deriving anything. A ticket (ai_agent_jobs/<KEY>_port_ticket.json, with a Markdown
# twin) holds:
#   target       the generated service to fill (its file, its public methods and the TODO
#                ones), the overlay path a port lands on, and the target config (Java /
#                Spring Boot / data classes / database ...) the port must follow;
#   source       the program's and its copybooks' numbered listings (columns 1-72), written
#                once each under ai_agent_jobs/sources/ and referenced, and its paragraphs
#                (name, first line, lines) from the engine's units;
#   facts        the verified skeleton sections that concern it, each with its field-testing
#                status (the #3614 ticket view: bulk data sections stay in the skeleton file);
#   generated    the generated classes it builds on: those the service imports (entities with
#                their record codecs, repositories, DTOs, the batch runtime) and every artifact
#                the traceability manifest ties to this program;
#   worklist     this program's worklist items;
#   rules        the porting rules the #3624 slice proved (storage semantics, behaviour kept);
#   compiler_options  the program's CBL / PROCESS card options (#3828), and a rule for each
#                one that changes what it computes (INTDATE(LILIAN), TRUNC(BIN) ...);
#                a program with a LINE SEQUENTIAL file gets a rule naming it (#3833);
#   deliverable  what to return and how the port is proven (tests/tools/equivalence.py).
# Deterministic: no timestamps, estate-relative paths, sorted keys.
# ==============================================================================
from __future__ import annotations

import codecs
import functools
import json
import math
import re
from pathlib import Path
from typing import Any

from gitgalaxy.core.compiler_options import compiler_options, effective
from gitgalaxy.core.data_moves import rounding_facts
from gitgalaxy.core.ebcdic_codecs import register as register_code_pages
from gitgalaxy.core.source_text import read_source
from gitgalaxy.core.special_names import special_names
from gitgalaxy.core.unicode_paths import on_disk
from gitgalaxy.tools.cobol_to_java.cobol_to_java_agent_forge import ticket_skeleton
from gitgalaxy.tools.cobol_to_java.cobol_to_java_names import java_class_base
from gitgalaxy.tools.cobol_to_java.cobol_to_java_transaction_forge import DTO_SUBPACKAGE

TICKET_VERSION = 1
PORTING_RULES = [
    (
        "Deliver the whole port: every paragraph the ported method reaches, every screen field it sets, every "
        "file it reads. A partial port or a sketch is not proven: the equivalence harness compares every output."
    ),
    (
        "Port the PROCEDURE DIVISION into the service's methods, paragraph by paragraph; name the paragraph "
        "each block ports in a comment, so the port can be reviewed against the source."
    ),
    (
        "Keep COBOL's storage semantics: COMPUTE / ADD / SUBTRACT / MULTIPLY / DIVIDE without ROUNDED "
        "truncate decimals; a result too long for its PICTURE loses its high-order digits (ON SIZE ERROR "
        "aside); MOVE to a numeric field aligns on the decimal point and truncates both ends; MOVE to "
        "alphanumeric pads with spaces or truncates on the right. Use BigDecimal with RoundingMode.DOWN, "
        "never double, for PIC 9 / COMP-3 data."
    ),
    (
        "ROUNDED (#3825) rounds half AWAY from zero: setScale(scale, RoundingMode.HALF_UP) -- 2.5 -> 3, "
        "-2.5 -> -3. Never HALF_EVEN (banker's rounding) and never Math.round (-2.5 -> -2). ROUNDED MODE "
        "maps one to one: NEAREST-EVEN HALF_EVEN, AWAY-FROM-ZERO UP, NEAREST-TOWARD-ZERO HALF_DOWN, "
        "TOWARD-GREATER CEILING, TOWARD-LESSER FLOOR, TRUNCATION DOWN. The ticket's `rounding` list names "
        "every rounding or SIZE ERROR statement with the RoundingMode of each target. Round the final result "
        "only: compute intermediates exactly (IBM's ARITH intermediates carry 18 or 31 digits; the "
        "equivalence harness is the oracle when a result differs)."
    ),
    (
        "Keep the program's behaviour, including what looks like a defect (an unreachable branch, a field "
        "never reset): the port is proven by comparing its outputs with the original's. Document each such "
        "spot with a comment naming the defect and the one-line fix; fixing it is a business decision, not a "
        "translation."
    ),
    (
        "Use the generated code as it is: entities and their fromRecord / toRecord codecs, repositories, "
        "DTOs, the batch runtime (DatasetResolver, Dd), the other services. Do not edit generated files other"
        " than this service; do not invent calls, files, queues or tables the facts do not name."
    ),
    (
        "An abend is `throw CobolAbend.user(abcode, why)` (the generated batch runtime; CALL 'CEE3ABD' USING "
        "ABCODE: the step ends ABEND Unnnn) -- never another exception; the step's RETURN-CODE is runBatch's "
        "return value."
    ),
    (
        "A DISPLAY is `Sysout.display(...)` (DISPLAY ... WITH NO ADVANCING: `Sysout.displayNoAdvancing`), never a "
        "log line: SYSOUT is compared line by line with the COBOL's. Its text is exactly what IBM COBOL writes, the "
        "operands concatenated: a literal as written; an alphanumeric or group item as all its bytes, trailing "
        "spaces included (a group's numeric fields as stored: zoned digits, the sign overpunched); a numeric item "
        "-- DISPLAY, COMP or COMP-3, not edited, no SIGN SEPARATE -- as `Sysout.number(value, digits, scale, "
        "signed)`: its PICTURE digits zero-padded, no decimal point, the sign overpunched in the last digit when "
        "signed (PIC S9(3) holding -12 is `01K`); an edited item as its edited text."
    ),
    (
        "Every file I/O statement of a batch program (OPEN, CLOSE, READ, READ NEXT, WRITE, REWRITE, DELETE, "
        "START) is ONE call to the generated CobolFiles, per file (its DD name), in the order the program runs "
        "them. open(dd) / open(dd, path, input) / close(dd[, action]) / write / rewrite / delete(dd, action) / "
        'start(dd, found) return the status String; read(dd, supplier) ("00" or "23") and readNext(dd, '
        'iterator) ("00" or "10") return a CobolFiles.Read<T> -- status() and record(), null unless found. '
        "Take the program's "
        "FILE STATUS logic -- IF <status> = '00', AT END, INVALID KEY, its error paragraphs -- from the status "
        "returned, exactly as the program does; never skip a statement the program runs (a read-ahead, a "
        "CLOSE) or add one it does not. The equivalence harness injects file faults through CobolFiles and "
        "through GnuCOBOL at the same statement, and proves the error paths too. A keyed (VSAM KSDS) file keeps "
        "its mainframe semantics: WRITE is writeKeyed(dd, () -> repo.existsById(key), () -> repo.save(r)) -- "
        '"22" when the key is on file, never save() over it -- and REWRITE is rewriteKeyed(dd, exists, save) '
        '("23" when it is not). A record the program READs INTO its working storage is the program\'s own copy: '
        "keep Entity.fromRecord(read.toRecord(cs), cs), never the repository's managed entity, so a change that is "
        "not REWRITten is never saved; and a READ that fails without INVALID KEY / AT END leaves the previous "
        "record in place, as the program's storage does."
    ),
    (
        "A sequential dataset is fixed-length records (RECFM=FB): write each record's toRecord(...) bytes "
        "back to back, with no line separators, to the file DatasetResolver.path(dd) names; read it the same "
        "way."
    ),
    (
        "Decode and encode a numeric field held in record bytes or a text column (zoned with an overpunched "
        "sign, COMP-3, COMP) only through the generated CobolRecords (zoned / packed / binary and their put "
        "methods) or the entity codecs, never a hand-written decoder."
    ),
    (
        "Record bytes -- every dataset, file and COMMAREA the program reads or writes -- are in the code page "
        "CobolRecords.charset() returns: the migration's declared data.record_charset, a deployment fact. Pass "
        "it wherever a record codec, CobolRecords method or String takes a Charset; never Charset.forName, "
        "StandardCharsets or a guessed EBCDIC page for record data (#4060)."
    ),
    (
        "Read a number from text (a screen field, FUNCTION NUMVAL, a PARM) only through "
        "CobolRecords.numval(text, decimalPoint), with ',' when the program codes DECIMAL-POINT IS COMMA; "
        "never Integer.parseInt or new BigDecimal(String), which accept Arabic-Indic, Devanagari and "
        "full-width digits that COBOL rejects (#3831)."
    ),
    (
        "Format a numeric-edited field (a display string mapped from a number, often for a "
        "screen or print line) only through CobolEdit.format(pic, value, decimalComma, currency), "
        "which honours the COBOL picture (Z, 9, ., ,, -, +, CR/DB, $/currency, B, 0, /, and floating "
        "$ / + / - strings) as the mainframe does; pass the CURRENCY SIGN string (e.g. 'INR ') as "
        "currency, and it replaces the PICTURE SYMBOL (#3933)."
    ),
    (
        "Format and case-map with Locale.ROOT (String.format(Locale.ROOT, ...), toUpperCase(Locale.ROOT)): "
        "the default locale prints other digits (Arabic, Devanagari) and maps case differently (Turkish)."
    ),
    (
        "Order and compare VSAM / DB2 keys by the source code page's bytes, as the mainframe does (lower case "
        "before upper, letters before digits): browse through the generated sort-key finders, and sort in Java "
        "with CobolRecords.sortKey(key, codePage), never by String.compareTo or the database's default "
        "collation (#3822)."
    ),
    (
        "Compare alphanumeric operands (PIC X / A items, group items, alphanumeric literals and figurative "
        "constants) in IF, EVALUATE, PERFORM UNTIL and SEARCH WHEN only through the generated CobolCompare "
        "(compare, eq, gt, ge, lt, le), never String.compareTo or equals: it compares the code page's bytes "
        "as the mainframe does -- lower case before upper, letters before digits, so IF CUST-ID > 'A' is true "
        "for '1001' -- and pads the shorter operand with spaces ('AB' = 'AB  '). HIGH-VALUES / LOW-VALUES are "
        "CobolCompare.highValues(n) / lowValues(n). A numeric comparison stays BigDecimal.compareTo. A program "
        "that declares PROGRAM COLLATING SEQUENCE compares by that alphabet instead: flag it in a TODO (#3986)."
    ),
    (
        "A CICS program is ported into runTask(CicsTask task), one task per call (#3754): EIBCALEN = 0 is "
        "!task.hasCommarea(), EIBCALEN is task.eibcalen() (#4009: null = the whole record), DFHCOMMAREA is "
        "task.commarea(<its DTO>.class), EIBAID is task.aid() (ENTER, CLEAR, PF1-PF24, PA1-PA3), EIBTRMID is "
        "task.termid(), EIBTIME / EIBDATE / ASKTIME are task.now() (the task's dispatch time on the region's "
        "virtual clock, #3989), RECEIVE MAP is "
        "task.receive(map, mapset, <its screen>.class) (empty = MAPFAIL), SEND MAP is task.sendMap(map, mapset, "
        "screen, subfields, options...) (#4001: the screen holds each <f>O; CicsTask.MapSubfields each <f>A / <f>C "
        "/ <f>H as its EBCDIC byte and <f>L = -1 for the cursor), "
        "SEND TEXT / SEND is task.sendText(from, length, options...), RETURN TRANSID COMMAREA LENGTH is "
        "task.returnTransid(transid, commarea, length), XCTL is task.xctl, LINK is task.link, ABEND is task.abend "
        "-- in the order "
        "the program does them, and "
        "the task ends at RETURN / XCTL / ABEND. A file READ is task.read(file, () -> <the service's generated read "
        "method>): its resp() is NORMAL (0), NOTFND (13) when the read finds nothing, or a condition the "
        "equivalence harness injects (NOTOPEN, IOERR, DISABLED, ...), and its resp2(); port every arm of the "
        "program's RESP handling (EVALUATE WS-RESP-CD ... WHEN OTHER) from it (#4023 follow-up). INQUIRE PROGRAM(p) is task.inquireProgram(p): its RESP (NORMAL 0, "
        "PGMIDERR 27). A screen field shows what the symbolic map's O field would hold: text "
        "as moved, an edited PICTURE formatted as COBOL formats it. A COMMAREA is the generated DTO of its "
        "record; an area no generated DTO describes (a plain PIC X(n) item) is passed as a String of its n "
        "characters, or a byte[] of its EBCDIC bytes (#3989)."
    ),
    (
        "CICS condition and abend handling (#3989): HANDLE CONDITION, IGNORE CONDITION, HANDLE AID and RESP are "
        "the program's own control flow -- port each transfer to its label as Java control flow. HANDLE ABEND "
        "LABEL is task.handleAbend(label) (CANCEL, RESET: handleAbendCancel / handleAbendReset), and PUSH / POP "
        "HANDLE are task.pushHandle() / popHandle() besides saving and restoring the program's own handler "
        "state. EXEC CICS ABEND is task.abend(abcode) and a condition that takes CICS's default action is "
        "task.abendOnCondition(condition): CicsTask searches the active abend exits from this program's level "
        "upward, as CICS does, records the ABEND, and returns the label to continue at when this program's own "
        "exit took it -- or null, and the program must then return from runTask at once. After task.link(...) "
        "returns, task.abendExit() is the label of this program's exit when an abend in a program below reached "
        "it (continue there), and task.ended() is true when the task was terminated (stop). Never throw an "
        "exception to model a CICS transfer: the services are @Transactional, so an exception out of one marks "
        "the whole task rollback-only."
    ),
    (
        "Dates and times only through java.time -- LocalDate, LocalDateTime, LocalTime and DateTimeFormatter "
        "with Locale.ROOT, in the ISO chronology -- never Calendar.getInstance(), new GregorianCalendar(), "
        "SimpleDateFormat or WeekFields.of(Locale.getDefault()): a th_TH default locale gives Buddhist-era years "
        "(2569), ja_JP_JP the Japanese imperial calendar, and US week fields start on Sunday. FUNCTION "
        "DAY-OF-WEEK and ACCEPT ... FROM DAY-OF-WEEK are Monday = 1 ... Sunday = 7, which is "
        "DayOfWeek.getValue() (#3833)."
    ),
    (
        "Read the time only from the generated batch runtime's MainframeClock (now() for local, currentDate() for "
        "FUNCTION CURRENT-DATE) -- in a CICS task, from task.now() -- never from the system clock directly or "
        "ZoneId.systemDefault(): it is how a run is pinned to be compared with the original."
    ),
    (
        "A DB2 DATE / TIME / TIMESTAMP fetched into, or bound from, a character host variable (a DCLGEN DATE is "
        "PIC X(10)) is in the DB2 subsystem's format, the target config's culture.db2_date_format -- eur "
        "26.09.2026 and 14.30.05, usa 09/26/2026 and 02:30 PM, iso 2026-09-26 and 14.30.05, jis 2026-09-26 and "
        "14:30:05 -- and a TIMESTAMP is 2026-09-26-14.30.05.000000: convert only through the generated Db2Dates "
        "(date / time / timestamp, parseDate / parseTime / parseTimestamp), never LocalDate.toString() or "
        "LocalDate.parse (#3828)."
    ),
    (
        "FUNCTION INTEGER-OF-DATE / INTEGER-OF-DAY count days from day 1 = 1601-01-01 under INTDATE(ANSI), the "
        "default, but from day 1 = 1582-10-15 under INTDATE(LILIAN) (the same date is 6653 higher); "
        "DATE-OF-INTEGER / DAY-OF-INTEGER invert the same count. Port as ChronoUnit.DAYS.between(dayZero, date) "
        "with dayZero 1600-12-31 (ANSI) or 1582-10-14 (LILIAN). The ticket's compiler_options are the program's "
        "CBL / PROCESS cards; options given by the compile step's PARM or the installation defaults are not seen "
        "there (#3828)."
    ),
    (
        "A fact whose field testing is not 'field-tested' is verified on reference estates but still being "
        "field-tested: where the source contradicts it, follow the source and say so in the port's notes."
    ),
]


# #3828: what each non-default semantic compiler option means for the port, keyed (option, value).
_OPTION_RULES = {
    ("INTDATE", "LILIAN"): (
        "INTDATE(LILIAN): INTEGER-OF-DATE / DATE-OF-INTEGER / INTEGER-OF-DAY / DAY-OF-INTEGER count from "
        "1582-10-15 = day 1 (dayZero 1582-10-14), not 1601-01-01."
    ),
    ("TRUNC", "BIN"): (
        "TRUNC(BIN): a COMP / BINARY item keeps any value its bytes hold (PIC S9(4) COMP holds -32768..32767), "
        "not truncated to its PICTURE's digits."
    ),
    ("TRUNC", "OPT"): (
        "TRUNC(OPT): IBM truncates binary items only as the generated code finds convenient; where a value "
        "can exceed its PICTURE, the equivalence harness is the oracle."
    ),
    ("ARITH", "EXTEND"): "ARITH(EXTEND): numeric items may have 31 digits and intermediates carry 31, not 18.",
    ("NUMPROC", "PFD"): (
        "NUMPROC(PFD): the compiler trusts signs to be preferred (C / D / F) and does not repair them; a "
        "non-preferred sign can compare or move differently than under NOPFD."
    ),
}


def line_sequential_rules(file_control: list[dict[str, Any]]) -> list[str]:
    """#3833: a LINE SEQUENTIAL file (Micro Focus, GnuCOBOL, Windows estates) is one record per line, not the
    RECFM=FB records the sequential rule describes; one rule naming this program's such files."""
    names = sorted({str(f.get("select_name")) for f in file_control
                    if str(f.get("organization") or "").upper() == "LINE SEQUENTIAL"})  # fmt: skip
    if not names:
        return []
    return [
        f"This program's {', '.join(names)} {'is' if len(names) == 1 else 'are'} ORGANIZATION LINE SEQUENTIAL "
        "(see the facts' file_control), not RECFM=FB, so the sequential-dataset rule does not apply to "
        f"{'it' if len(names) == 1 else 'them'}: read one record per line (the line terminator is not data) and "
        "pad a short line with spaces to the record length; on write, strip the record's trailing spaces and end "
        "the line with the platform's terminator -- \\n, or \\r\\n when the estate runs on Windows (#3833)."
    ]


def decimal_point_rules(text: str, culture: dict[str, Any] | None) -> list[str]:
    """#3984: the decimal point this program's numbers use, named in its ticket -- the generic NUMVAL and
    CobolEdit rules leave it to the porter to find DECIMAL-POINT IS COMMA in SPECIAL-NAMES, and a
    `ZZZ.ZZ9,99` formatted with decimalComma = false reads 1.234,50 as 1,234.50. culture.decimal_point
    overrides the program as it does for the entities (_decimal_comma); a program with neither keeps
    today's rules."""
    line = next((sn["line"] for sn in special_names(text) if sn["clause"] == "DECIMAL-POINT"), None)
    declared = str((culture or {}).get("decimal_point") or "auto")
    if declared == "period" and line is not None:
        return [
            f"This program codes DECIMAL-POINT IS COMMA (SPECIAL-NAMES, line {line}), but this migration declares "
            "culture.decimal_point: period: pass '.' to CobolRecords.numval and decimalComma = false to "
            "CobolEdit.format, as the generated entities do (#3984)."
        ]
    if declared == "comma" or (declared == "auto" and line is not None):
        where = (f"codes DECIMAL-POINT IS COMMA (SPECIAL-NAMES, line {line})" if line is not None
                 else "is ported with culture.decimal_point: comma")  # fmt: skip
        return [
            f"This program {where}: in its PICTUREs and numeric literals `,` is the decimal point and `.` an "
            "insertion character (PIC 9(6),99 has 2 decimals; VALUE 12,50 is 12.5). Pass ',' to "
            "CobolRecords.numval and decimalComma = true to CobolEdit.format for every one of its fields; a "
            'Java literal is still written with `.` (new BigDecimal("12.50")) (#3984).'
        ]
    return []


def collation_rules(culture: dict[str, Any] | None) -> list[str]:
    """#3986: CobolCompare always follows the code page's bytes, as the program did; under a key_collation
    other than ebcdic the generated repositories browse in another order, so a program that compares the
    keys it browses can see them out of its own order. Said once, where it applies."""
    collation = str((culture or {}).get("key_collation") or "ebcdic")
    if collation == "ebcdic":
        return []
    order = "UTF-8 byte order" if collation == "binary" else "the database's default collation"
    return [
        f"This migration declares culture.key_collation: {collation}: repository browses return keys in "
        f"{order}, while CobolCompare compares as the mainframe did. Where the program compares a key it "
        "browsed with another (a READNEXT loop ending on a limit, a control break), the two orders can "
        "disagree: flag it in a TODO rather than switching the comparison (#3986)."
    ]


def multibyte_rules(data: dict[str, Any] | None) -> list[str]:
    """#3985: under a multi-byte code page a PIC X field's width is bytes, not characters -- a mixed EBCDIC
    page (cp930 / cp939 / cp933 / cp935 / cp937) wraps each double-byte run in Shift-Out / Shift-In, and an
    ASCII DBCS page (shift_jis, cp932) takes two bytes per Kanji -- so String.length() and substring() stop
    matching the record. Said only where the code page can encode a CJK character; a single-byte estate keeps
    today's rules."""
    code_page = str((data or {}).get("code_page") or "cp037")
    register_code_pages()
    try:
        codecs.lookup(code_page)
        "\u65e5".encode(code_page)
    except (LookupError, UnicodeError):
        return []
    return [
        f"This migration's code page ({code_page}) is multi-byte: a PIC X field's width is BYTES, not characters "
        "(`AB日本C` is 5 characters and, in a mixed EBCDIC page, 9 bytes: Shift-Out and Shift-In count). "
        "Measure a field with CobolRecords.width(value, text) and cut or pad it with CobolRecords.fit(value, "
        "width, text), which keeps whole characters; never String.length(), substring() or String.format "
        "widths for fixed-width logic. A reference modification (X(3:5)) of such a field can split a "
        "double-byte run: flag it in a TODO (#3985)."
    ]


def option_rules(options: list[dict[str, Any]]) -> list[str]:
    """#3828: one rule per CBL / PROCESS option that changes what the program computes."""
    line_of = {str(o.get("option")): o.get("line") for o in options}
    out: list[str] = []
    now = effective(options)
    for (option, value), text in _OPTION_RULES.items():
        if str(now.get(option) or "").upper() == value:
            out.append(f"This program's CBL / PROCESS card (line {line_of.get(option)}) sets {text}")
    return out


# #3863: COACTVWC's 268 KB prompt came back empty. A ticket over this many tokens is trimmed (trim_ticket).
TICKET_TOKEN_BUDGET = 64000


@functools.lru_cache(maxsize=1)
def _tiktoken_encoding() -> Any:
    """#3863: tiktoken's o200k_base, loaded once -- or None. It is an optional dependency, and its first
    use downloads the encoding, so offline (CI, an air-gapped site) it fails: count bytes then."""
    try:
        import tiktoken

        return tiktoken.get_encoding("o200k_base")
    except Exception:  # not installed, offline, or broken: the caller falls back to bytes / 4
        return None


def count_tokens(text: str) -> tuple[int, int, str]:
    """#3863: (bytes, tokens, how counted): tiktoken's o200k_base when it loads, else bytes / 4."""
    b = len(text.encode("utf-8"))
    encoding = _tiktoken_encoding()
    tokens = None
    if encoding is not None:
        try:
            tokens = len(encoding.encode(text))
        except Exception:  # a broken tokenizer must not stop a ticket: count bytes instead
            tokens = None
    if tokens is not None:
        return b, tokens, "tiktoken(o200k_base)"
    return b, math.ceil(b / 4), "bytes/4"


# #3930: what a generated contract class (cobol_to_java_transaction_forge) says of a record: its Javadoc names it
# (`COBOL record DFHCOMMAREA (cbl/ACCTVIEW.cbl), 30 bytes, ...`) and each named field has a comment
# (`// CC-ACCT-ID: PIC 9(11), offset 0, 11 bytes (cpy/CARDCOMM.cpy)`, _field_lines).
_CONTRACT_FIELD = re.compile(r"^    // (\S+): (.*?), offset (\d+)(?: bit \d+)?, (\d+) (?:bytes|bits) \((.*)\)$", re.M)


def _contract_classes(java_dir: Path, package: str) -> dict[str, str]:
    """{project-relative path: Java source} of the generated COMMAREA / container contract classes."""
    rel_dir = _class_path(f"{package}.{DTO_SUBPACKAGE}.X").rsplit("/", 1)[0]
    folder = java_dir / rel_dir
    if not folder.is_dir():
        return {}
    return {f"{rel_dir}/{p.name}": p.read_text(encoding="utf-8") for p in sorted(folder.glob("*.java"))}


def _carrying_class(record: Any, file: Any, fields: list[Any], classes: dict[str, str]) -> str | None:
    """#3930: the contract class that carries every named field of `record` (declared in `file`) -- name, PIC,
    usage, offset, width and copybook, in order -- or None. FILLERs have no field (their bytes stay in the
    offsets); anything else missing or different means the class is not the whole story, and the layout stays
    in the ticket."""
    if not record or not file:
        return None
    head = re.compile(
        rf"^ \* (?:COBOL record|PL/I structure) {re.escape(str(record))} \({re.escape(str(file))}\), ", re.M
    )
    want = [
        (f.get("name"), f.get("pic"), f.get("usage"), f.get("offset"), f.get("bits", f.get("bytes")), f.get("file"))
        for f in fields
        if isinstance(f, dict) and f.get("name") and str(f["name"]).upper() != "FILLER"
    ]
    for path, java in classes.items():
        if not head.search(java):
            continue
        got = _CONTRACT_FIELD.findall(java)
        if len(got) != len(want):
            continue
        if all(
            name == g_name
            and int(offset) == int(g_off)
            and int(width) == int(g_width)
            and file_ == g_file
            and (pic is None or f"PIC {pic}" in g_pic or f"PIC '{pic}'" in g_pic)
            and (usage is None or pic is None or str(usage) in g_pic)
            for (name, pic, usage, offset, width, file_), (g_name, g_pic, g_off, g_width, g_file) in zip(want, got)
            if offset is not None and width is not None
        ) and all(w[3] is not None and w[4] is not None for w in want):
            return path
    return None


def reference_generated(ticket: dict[str, Any], java_dir: Path, package: str) -> None:
    """#3930: a record layout the generated code already carries is referenced, not inlined -- always, not
    only over budget (#3863's item 2). The COMMAREA and each container layout of `facts.interface` become
    "Reference: <class> (<n> fields) ...", the fact's other keys kept, once the contract class is checked to
    carry every field (`_carrying_class`); the ticket records each in `referenced`, with its bytes before and
    after (bytes only: a token count depends on whether tiktoken loads, and would make tickets differ by
    environment).

    Left inline, by design: an unpacked COMMAREA (`basis: unpack`, one DTO per record the program unpacks,
    not one layout); `facts.cics_file_lineage`, whose CSD facts (key length, group, the lines of each access)
    no generated class carries; and record layouts, which `records` -- a bulk section -- never put in a
    ticket (the generated *Record entities carry them)."""
    iface = ((ticket.get("facts") or {}).get("sections") or {}).get("interface") or {}
    facts = iface.get("facts") or {}
    if not isinstance(facts, dict):
        return
    program_file = (ticket.get("program") or {}).get("file")
    layouts: list[tuple[str, dict[str, Any], Any, Any]] = []
    commarea = facts.get("commarea")
    if isinstance(commarea, dict) and commarea.get("basis") != "unpack" and isinstance(commarea.get("fields"), list):
        layouts.append(("commarea", commarea, commarea.get("record"), commarea.get("file")))
    for i, c in enumerate(facts.get("containers") or []):
        layout = c.get("layout") if isinstance(c, dict) else None
        if isinstance(layout, dict) and isinstance(layout.get("fields"), list):
            layouts.append((f"containers[{i}].layout", layout, c.get("record"), program_file))
    if not layouts:
        return
    classes = _contract_classes(java_dir, package)
    referenced = []
    for item, layout, record, file in layouts:
        path = _carrying_class(record, file, layout["fields"], classes)
        if path is None:
            continue
        before = len(json.dumps(layout["fields"], indent=2, sort_keys=True).encode("utf-8"))
        n = sum(1 for f in layout["fields"] if f.get("name") and str(f["name"]).upper() != "FILLER")
        name = path.rsplit("/", 1)[1][: -len(".java")]
        layout["fields"] = (
            f"Reference: {name} ({n} fields: name, PIC, usage, offset, bytes, copybook) in {path}; "
            "level numbers are in the copybook listings"
        )
        after = len(json.dumps(layout["fields"], indent=2, sort_keys=True).encode("utf-8"))
        referenced.append(
            {
                "section": "facts.interface",
                "item": item,
                "class": path,
                "fields": n,
                "bytes_before": before,
                "bytes_after": after,
            }
        )
    if referenced:
        ticket["referenced"] = referenced


def trim_ticket(ticket: dict[str, Any], budget: int) -> None:
    """#3863: bring a ticket over `budget` tokens down, never silently: the BMS field inventories go
    first (the generated screen classes already carry them), each replaced by a reference, and the
    ticket records what was trimmed and its sizes after. A ticket within budget is left byte-identical."""
    serialized = json.dumps(ticket, indent=2, sort_keys=True)
    _, t_before, _ = count_tokens(serialized)

    if t_before <= budget:
        return

    trimmed = []

    # 1. facts.screen_bindings
    facts_sec = ticket.get("facts", {}).get("sections", {})
    screen_sec = facts_sec.get("screen_bindings")
    if screen_sec and "facts" in screen_sec:
        old_bytes, old_tokens, _ = count_tokens(json.dumps(screen_sec, indent=2, sort_keys=True))

        for fact in screen_sec.get("facts", []):
            if "fields" in fact:
                num_fields = len(fact["fields"])
                map_name = fact.get("map", "")
                # the screen forge's name (cobol_to_java_screen_forge._plan), unless a clash renamed it
                class_name = java_class_base(map_name) + "Screen" if map_name else "Screen"
                fact["fields"] = f"Reference: {class_name} ({num_fields} fields)"

        new_bytes, new_tokens, _ = count_tokens(json.dumps(screen_sec, indent=2, sort_keys=True))
        if new_bytes < old_bytes:
            trimmed.append(
                {
                    "section": "facts.screen_bindings",
                    "bytes_before": old_bytes,
                    "tokens_before": old_tokens,
                    "bytes_after": new_bytes,
                    "tokens_after": new_tokens,
                    "reason": "trimmed screen_bindings fields to references",
                }
            )

    if trimmed:
        ticket["trimmed"] = trimmed
        sizes = {}
        for sec_name, sec_val in ticket.items():
            if sec_name == "facts":
                for f_sec, f_val in sec_val.get("sections", {}).items():
                    b, t, _ = count_tokens(json.dumps(f_val, indent=2, sort_keys=True))
                    sizes[f"facts.{f_sec}"] = {"bytes": b, "tokens": t}
            else:
                b, t, _ = count_tokens(json.dumps(sec_val, indent=2, sort_keys=True))
                sizes[sec_name] = {"bytes": b, "tokens": t}
        ticket["sizes"] = sizes
    _, t_after, _ = count_tokens(json.dumps(ticket, indent=2, sort_keys=True))
    if t_after > budget:  # nothing more may go (the rules never do): say so rather than pretend
        ticket["over_budget"] = {"budget": budget, "tokens": t_after}


def _source_text(path: Path, declared: str | None = None) -> list[str]:
    """Numbered source lines, columns 1-72 (the sequence area dropped). #3909: `declared` is the code
    page the refractor read the program in (its IR dump's metadata.source_encoding)."""
    try:
        lines = read_source(path, declared=declared).text.splitlines()
    except OSError:
        return []
    return [f"{n:5d} | {line[:72].rstrip()}" for n, line in enumerate(lines, 1)]


# The batch-entry stub's javadoc names its porting TODO (cobol_to_java_batch_forge); its body is `return 0;`.
_STUB_DOC = "port the PROCEDURE DIVISION main line"


def _listing(file: str) -> str:
    """Where a source's numbered listing lives, relative to ai_agent_jobs/."""
    return f"sources/{file}.lst"


def _public_methods(java: str) -> list[dict[str, Any]]:
    """The service's public methods: signature, and whether its body is still a TODO."""
    out = []
    for m in re.finditer(r"^    public (?!class)([^=;{}()]+)\(([^)]*)\)\s*\{", java, re.M):
        body_start = m.end()
        depth, i = 1, body_start
        while i < len(java) and depth:
            depth += {"{": 1, "}": -1}.get(java[i], 0)
            i += 1
        body = java[body_start : i - 1]
        doc = java[max(0, java.rfind("/**", 0, m.start())) : m.start()]
        todo = "TODO" in body or (_STUB_DOC in doc and "return 0;" in body)
        out.append({"signature": f"public {m.group(1).strip()}({m.group(2).strip()})", "todo": todo})
    return out


def _imports(java: str, package: str) -> list[str]:
    """The project classes a generated file imports (entities, repositories, DTOs, batch runtime)."""
    return sorted(re.findall(rf"^import ({re.escape(package)}\.[\w.]+);", java, re.M))


def _class_path(fqcn: str) -> str:
    return "src/main/java/" + fqcn.replace(".", "/") + ".java"


def build_ticket(key: str, skeleton: dict[str, Any], java_dir: Path, package: str, source_root: Path | None,
                 manifest: dict[str, Any] | None, items: list[dict[str, Any]], target: dict[str, Any],
                 skeleton_file: str | None, declared: str | None = None) -> dict[str, Any]:  # fmt: skip
    """#3909: `declared` is the code page the program was decoded in (None: read unaided)."""
    prog = skeleton.get("program", {})
    service = java_class_base(key) + "Service"
    service_rel = _class_path(f"{package}.service.{service}")
    java = (java_dir / service_rel).read_text(encoding="utf-8") if (java_dir / service_rel).is_file() else ""
    # Listings are written once per source (write_port_tickets), not per ticket: an include member is
    # shared by hundreds of programs (DSF). `listing` is relative to ai_agent_jobs/; None when unread.
    # #3815: a stored path is NFC; on_disk finds the file where the checkout spelled its name NFD
    readable = source_root is not None and prog.get("file") and on_disk(source_root, prog["file"]).is_file()
    source: dict[str, Any] = {
        "program": {"file": prog.get("file"), "listing": _listing(prog["file"]) if readable else None},
        "copybooks": [{"file": c, "listing": _listing(c) if source_root and on_disk(source_root, c).is_file() else None}
                      for c in prog.get("copybooks", [])],
    }  # fmt: skip
    units = (skeleton.get("sections", {}).get("units") or {}).get("facts") or []
    paragraphs = [{"name": u.get("name"), "start_line": u.get("start_line"), "lines": u.get("loc")} for u in units]
    tied = sorted({(a["file"], a["symbol"]) for a in (manifest or {}).get("artifacts", [])
                   if any(str(f.get("source") or "").split(":")[0] == prog.get("file") for f in a.get("facts", []))})  # fmt: skip
    generated = {
        "imports": [{"class": c, "file": _class_path(c)} for c in _imports(java, package)],
        "traced_to_this_program": [{"file": f, "symbol": s} for f, s in tied],
    }
    methods = _public_methods(java)
    text = read_source(on_disk(source_root, prog["file"]), declared=declared).text if readable and source_root else ""
    rounding = rounding_facts(text) if readable else []  # #3825
    options = compiler_options(text)  # #3828
    file_control = (skeleton.get("sections", {}).get("file_control") or {}).get("facts") or []
    rules = list(PORTING_RULES) + option_rules(options) + line_sequential_rules(file_control)  # #3833
    rules += decimal_point_rules(text, target.get("culture"))  # #3984
    rules += collation_rules(target.get("culture"))  # #3986
    rules += multibyte_rules(target.get("data"))  # #3985
    if (target.get("culture") or {}).get("rounding") == "half_even":  # #3819: a declared deviation
        rules.append(
            "This migration declares culture.rounding: half_even (a deviation from COBOL): a plain ROUNDED "
            "uses RoundingMode.HALF_EVEN; an explicit ROUNDED MODE keeps its own mapping."
        )
    return {
        "ticket": f"PORT-{key}",
        "version": TICKET_VERSION,
        "status": "open",
        "program": {
            "key": key,
            "program_ids": prog.get("program_ids", []),
            "language": prog.get("language"),
            "file": prog.get("file"),
            "lines": prog.get("total_loc"),
        },
        "target": {
            "service": service,
            "file": service_rel,
            "overlay": f"port/service/{service}.java",
            "methods": methods,
            "methods_to_port": [m["signature"] for m in methods if m["todo"]],
            "config": target,
        },
        "source": source,
        "paragraphs": paragraphs,
        "facts": ticket_skeleton(skeleton, skeleton_file),
        "generated": generated,
        "worklist": [{k: it[k] for k in ("id", "category", "file", "line", "text")} for it in items],
        "rounding": rounding,
        "compiler_options": options,
        "rules": rules,
        "deliverable": {
            "return": (
                f"One complete Java file for {service_rel}: the same package, class name and public method "
                "signatures, with the TODO bodies ported (helper methods may be added)."
            ),
            "proof": (
                "The port is laid over the generated project as an overlay and proven by the equivalence "
                "harness (tests/tools/equivalence.py in GitGalaxy): the original runs under GnuCOBOL, the "
                "port on the same inputs, and every output record is compared field by field; a person "
                "approves the port with that report in hand."
            ),
        },
    }


def ticket_markdown(t: dict[str, Any]) -> str:
    p, tg = t["program"], t["target"]
    md = [f"# {t['ticket']}: port {p['key']} ({p['language']}, `{p['file']}`, {p['lines']} lines)", ""]
    if t.get("priority"):
        pr = t["priority"]
        md += [f"**Port order {pr['rank']} of {pr['of']}** -- {pr['callers']} program(s) and job(s) call it, blast radius "
               f"{pr['blast_radius']} ([port_order.md](port_order.md)).", ""]  # fmt: skip
    md += [f"Fill `{tg['file']}` ({tg['service']}); return it as `{tg['overlay']}`.", "",
          "## Methods to port", ""]  # fmt: skip
    md += [f"- `{m}`" for m in tg["methods_to_port"]] or ["- (no method is marked as a TODO; see the worklist)"]
    md += ["", "## Target configuration", "", "```json", json.dumps(tg["config"], indent=2, sort_keys=True), "```"]
    md += ["", "## Porting rules", ""] + [f"{i}. {r}" for i, r in enumerate(t["rules"], 1)]
    if t.get("rounding"):  # #3825: every statement whose rounding or SIZE ERROR the port must keep
        md += ["", "## Rounding and SIZE ERROR statements", "", "| line | verb | target: RoundingMode | ON SIZE ERROR |",
               "|---:|---|---|---|"]  # fmt: skip
        for r in t["rounding"]:
            tgts = ", ".join(f"`{x['target']}`: {x['java']} ({x['mode']})" for x in r["targets"]) or "(truncates)"
            md.append(f"| {r['line']} | {r['verb']} | {tgts} | {'yes' if r['size_error'] else ''} |")
    if t.get("compiler_options"):  # #3828: the program's CBL / PROCESS cards
        md += ["", "## Compiler options (CBL / PROCESS cards)", "", "| line | option | as written |", "|---:|---|---|"]
        md += [f"| {o['line']} | {o['option']}{'(' + o['value'] + ')' if o.get('value') else ''} | `{o['written']}` |"
               for o in t["compiler_options"]]  # fmt: skip
    fc = ((t["facts"].get("sections") or {}).get("file_control") or {}).get("facts") or []
    if any(str(f.get("organization") or "").upper() == "LINE SEQUENTIAL" for f in fc):
        # #3833: which files are LINE SEQUENTIAL (one record per line) and which are fixed-length records
        md += ["", "## Files (FILE-CONTROL)", "", "| line | file | ASSIGN | organization |", "|---:|---|---|---|"]
        md += [f"| {f.get('line')} | {f.get('select_name')} | {f.get('assign') or ''} | "
               f"{f.get('organization') or 'SEQUENTIAL (default)'} |" for f in fc]  # fmt: skip
    md += ["", "## Worklist items for this program", ""]
    md += [f"- **{w['id']}** ({w['category']}) `{w['file']}:{w['line']}`: {w['text']}" for w in t["worklist"]]
    md += ["", "## Generated code it builds on", ""] + [f"- `{g['class']}`" for g in t["generated"]["imports"]]
    md += ["", "## Verified facts", ""]
    for name, sec in sorted(t["facts"].get("sections", {}).items()):
        md.append(f"- **{name}** ({sec.get('field_testing', 'untested')}): {len(sec.get('facts') or [])} facts")
    md += ["", "## Paragraphs", "", "| paragraph | line | lines |", "|---|---:|---:|"]
    md += [f"| {u['name']} | {u['start_line']} | {u['lines']} |" for u in t["paragraphs"]]
    md += ["", "## Deliverable", "", t["deliverable"]["return"], "", t["deliverable"]["proof"]]
    md += ["", "## Source listings (numbered, columns 1-72)", ""]
    for s_ in [t["source"]["program"], *t["source"]["copybooks"]]:
        md.append(f"- `{s_['file']}`: " + (f"[{s_['listing']}]({s_['listing']})" if s_["listing"] else "not read"))
    return "\n".join(md) + "\n"


def graph_metrics(clean_room: Path | None) -> dict[str, dict[str, Any]]:
    """#3237: {file: callers, calls, blast radius}, which the refractor writes to
    04_ir_state_dumps/graph_metrics.json when it ran with --scan / --galaxy-db. Empty
    without one -- the tickets then keep their name order."""
    f = clean_room / "04_ir_state_dumps" / "graph_metrics.json" if clean_room else None
    return json.loads(f.read_text(encoding="utf-8")) if f is not None and f.is_file() else {}


def _order_key(key: str, metrics: dict[str, Any] | None) -> tuple:
    """Port the programs the most depend on first: direct callers, then blast radius (transitive:
    PageRank also flows in from well-linked callers, e.g. a web layer, so it breaks ties rather
    than leading -- on CBSA it would put a one-caller program above INQCUST's four)."""
    m = metrics or {}
    return (-m.get("callers", 0), -m.get("blast_radius", 0.0), key)


def write_port_order(out_dir: Path, order: list[dict[str, Any]]) -> None:
    """ai_agent_jobs/port_order.json / .md: the tickets in the order to port them."""
    (out_dir / "port_order.json").write_text(json.dumps(order, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md = ["# Port order", "",
          ("The porting tickets in the order to take them: the programs the most other code depends on first -- "
           "a shared service or error handler is ported, proven and approved before the programs that call it. "
           "Ordered by callers (the programs and JCL steps that CALL / LINK / XCTL / EXEC it), then by blast "
           "radius (its weight in the dependency graph, PageRank x 1000, which counts callers of callers)."), "",
          "| order | program | callers | blast radius | ticket |", "|---:|---|---:|---:|---|"]  # fmt: skip
    md += [f"| {o['rank']} | `{o['file']}` | {o['callers']} | {o['blast_radius']} | [{o['ticket']}]({o['ticket']}) |"
           for o in order]  # fmt: skip
    (out_dir / "port_order.md").write_text("\n".join(md) + "\n", encoding="utf-8")


def write_port_tickets(java_dir: Path, skeletons: dict[str, Path], worklist: dict[str, Any] | None,
                       manifest: dict[str, Any] | None, package: str, target: dict[str, Any],
                       ir_dir: Path | None, clean_room_name: str,
                       clean_room: Path | None = None, budget: int = TICKET_TOKEN_BUDGET) -> dict[str, str]:  # fmt: skip
    """Write a ticket per program with business-logic worklist items; {program source: ticket path}.
    With the engine's DB in `clean_room` (#3237) each ticket carries its port order, and
    port_order.json / .md list them most-depended-on first."""
    metrics = graph_metrics(clean_room)
    candidates = []
    items_by_file: dict[str, list[dict[str, Any]]] = {}
    for it in (worklist or {}).get("items", []):
        if it.get("nature") == "port":
            items_by_file.setdefault(str(it.get("program")), []).append(it)
    out_dir = java_dir / "ai_agent_jobs"
    written: dict[str, str] = {}
    for key, path in sorted(skeletons.items()):
        skeleton = json.loads(path.read_text(encoding="utf-8"))
        file = (skeleton.get("program") or {}).get("file")
        items = [it for f, its in items_by_file.items() if f == file for it in its]
        if items:
            candidates.append((key, path, skeleton, file, items))
    candidates.sort(key=lambda c: _order_key(c[0], metrics.get(str(c[3]))))
    order: list[dict[str, Any]] = []
    for rank, (key, path, skeleton, file, items) in enumerate(candidates, 1):
        source_root: Path | None = None
        declared: str | None = None
        ir_file = ir_dir / f"{key}_ir.json" if ir_dir else None
        if ir_file is not None and ir_file.is_file():
            meta = json.loads(ir_file.read_text(encoding="utf-8")).get("metadata") or {}
            src = meta.get("path")
            if src and file and src.replace("\\", "/").endswith(file):
                source_root = Path(src[: len(src) - len(file)])
            # #3909: the page the refractor read the program in; its COPY members compile in it too
            declared = meta.get("source_encoding")
        ticket = build_ticket(key, skeleton, java_dir, package, source_root, manifest, items, target,
                              f"{clean_room_name}/06_skeleton/{path.name}", declared)  # fmt: skip
        reference_generated(ticket, java_dir, package)  # #3930: always, before any budget trim
        if budget > 0:
            trim_ticket(ticket, budget)
        m = metrics.get(str(file))
        if m is not None:
            ticket["priority"] = {"rank": rank, "of": len(candidates), **m}
            order.append({"rank": rank, "key": key, "file": file, "ticket": f"{key}_port_ticket.md", **m})
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{key}_port_ticket.json").write_text(json.dumps(ticket, indent=2, sort_keys=True) + "\n",
                                                         encoding="utf-8")  # fmt: skip
        (out_dir / f"{key}_port_ticket.md").write_text(ticket_markdown(ticket), encoding="utf-8")
        for s_ in [ticket["source"]["program"], *ticket["source"]["copybooks"]]:
            listing = out_dir / s_["listing"] if s_["listing"] else None
            if listing is not None and source_root is not None and not listing.exists():
                listing.parent.mkdir(parents=True, exist_ok=True)
                lines = _source_text(on_disk(source_root, s_["file"]), declared)
                listing.write_text("\n".join(lines) + "\n", encoding="utf-8")
        written[str(file)] = f"ai_agent_jobs/{key}_port_ticket.md"
    if order:
        write_port_order(out_dir, order)
    return written
