#!/usr/bin/env python3
# ==============================================================================
# GitGalaxy Tool: Java Spring Test Generator
#
# PURPOSE:
# Auto-generates JUnit 5 and Spring Boot integration tests to mathematically 
# prove the translated architecture compiles, boots, and routes correctly.
#
# ARCHITECTURAL DECISION:
# AI agents are notoriously unreliable at configuring Spring's ApplicationContext 
# or properly mocking external dependencies. By statically generating the `@SpringBootTest` 
# and `@WebMvcTest` suites *before* the AI touches the business logic, we establish 
# a strict Test-Driven Development (TDD) boundary. The agent is forced to write code 
# that satisfies the rigid architectural contract, immediately exposing hallucinated 
# dependencies or broken Dependency Injection (DI) chains during CI/CD compilation.
# ==============================================================================

# galaxyscope:ignore sec_hardcoded_secrets, secrets_risk


import argparse
import sys
import json
from pathlib import Path


def generate_context_test(package_name: str, class_name: str) -> str:
    """Generates a @SpringBootTest to ensure the entire dependency injection context loads."""
    return f"""package {package_name};

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class {class_name}ApplicationTests {{

    @Test
    void contextLoads() {{
        // =====================================================================
        // DEFENSIVE DESIGN (CONTEXT VALIDATION):
        // If the application.yml is broken, a database driver is missing, or 
        // the AI hallucinates a @Service dependency without implementing it, 
        // this test will fail immediately upon context initialization, catching 
        // architectural regressions before runtime.
        // =====================================================================
    }}
}}
"""


def generate_controller_test(package_name: str, class_name: str, endpoint_path: str) -> str:
    """Generates a @WebMvcTest to verify REST API mappings without booting the full server."""
    service_var = class_name[0].lower() + class_name[1:]

    return f"""package {package_name}.controller;

import {package_name}.service.{class_name}Service;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest({class_name}Controller.class)
class {class_name}ControllerTest {{

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private {class_name}Service {service_var}Service;

    @Test
    void testEndpointRouting() throws Exception {{
        // Verifies the @RequestMapping and @PostMapping generated by the API Contract script
        mockMvc.perform(post("/api/v1/{endpoint_path}/execute")
                .contentType("application/json")
                .content("{{}}")) // Empty JSON payload for structural routing test
               .andExpect(status().isOk()); // Or isNoContent() based on defined data outputs
    }}
}}
"""


def main():
    from gitgalaxy.licensing import enforce_licensing_guard

    enforce_licensing_guard("Java Test Generator")

    parser = argparse.ArgumentParser(description="GitGalaxy Java Test Generator")
    parser.add_argument("ir_file", help="Path to the GitGalaxy _ir.json state dump")
    parser.add_argument("--pkg", default="com.gitgalaxy.modernized", help="Base Java package name")
    args = parser.parse_args()

    ir_path = Path(args.ir_file).resolve()
    if not ir_path.exists():
        sys.exit(1)

    try:
        ir_state = json.loads(ir_path.read_text(encoding="utf-8"))

        # Determine class names
        prog_id = ir_state.get("metadata", {}).get("file_name", "Unknown").split(".")[0]
        class_name = "".join(word.capitalize() for word in prog_id.split("-"))
        endpoint_path = prog_id.lower()

        # Target output directories (Assuming standard Maven layout)
        test_dir = ir_path.parent / "src" / "test" / "java" / args.pkg.replace(".", "/")
        test_dir.mkdir(parents=True, exist_ok=True)

        # 1. Generate Context Test
        context_code = generate_context_test(args.pkg, class_name)
        (test_dir / f"{class_name}ApplicationTests.java").write_text(context_code, encoding="utf-8")

        # 2. Generate Controller Test
        controller_test_dir = test_dir / "controller"
        controller_test_dir.mkdir(exist_ok=True)
        controller_code = generate_controller_test(args.pkg, class_name, endpoint_path)
        (controller_test_dir / f"{class_name}ControllerTest.java").write_text(controller_code, encoding="utf-8")

        print(f"🧪 Spring Boot Test Suite Generated for {class_name}")

    except Exception as e:
        print(f"Error generating Java tests: {e}")


if __name__ == "__main__":
    main()