 INSERT INTO CARDDEMO.TRANSACTION_TYPE
        (TR_TYPE,TR_DESCRIPTION)
 SELECT '01','PURCHASE'      FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '02','PAYMENT'       FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '03','CREDIT'        FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '04','AUTHORIZATION' FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '05','REFUND'        FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '06','REVERAL'       FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '07','ADJUSTMENT'    FROM SYSIBM.SYSDUMMY1

;
