CREATE TABLE PARM_BUFFER (
    WS_ACCOUNT_OPENED_DAY          DECIMAL(2, 0),
    WS_ACCOUNT_OPENED_MONTH        DECIMAL(2, 0),
    WS_ACCOUNT_OPENED_YEAR         DECIMAL(4, 0),
    HV_ACCOUNT_EYECATCHER          VARCHAR(4),
    HV_ACCOUNT_CUST_NO             VARCHAR(10),
    HV_ACCOUNT_SORT_CODE           VARCHAR(6),
    HV_ACCOUNT_NUMBER              VARCHAR(8),
    HV_ACCOUNT_TYPE                VARCHAR(8),
    HV_ACCOUNT_INTEREST_RATE       DECIMAL(6, 2) -- Legacy: COMP-3 (Packed Decimal),
    HV_ACCOUNT_OPENED              VARCHAR(10),
    HV_ACCOUNT_OPENED_DAY          VARCHAR(2),
    HV_ACCOUNT_OPENED_DELIM1       VARCHAR(1),
    HV_ACCOUNT_OPENED_MONTH        VARCHAR(2),
    HV_ACCOUNT_OPENED_DELIM2       VARCHAR(1),
    HV_ACCOUNT_OPENED_YEAR         VARCHAR(4),
    HV_ACCOUNT_OVERDRAFT_LIMIT     INTEGER,
    HV_ACCOUNT_LAST_STMT_DATE      VARCHAR(10),
    HV_ACCOUNT_LAST_STMT_DAY       VARCHAR(2),
    HV_ACCOUNT_LAST_STMT_DELIM1    VARCHAR(1),
    HV_ACCOUNT_LAST_STMT_MONTH     VARCHAR(2),
    HV_ACCOUNT_LAST_STMT_DELIM2    VARCHAR(1),
    HV_ACCOUNT_LAST_STMT_YEAR      VARCHAR(4),
    HV_ACCOUNT_NEXT_STMT_DATE      VARCHAR(10),
    HV_ACCOUNT_NEXT_STMT_DAY       VARCHAR(2),
    HV_ACCOUNT_NEXT_STMT_DELIM1    VARCHAR(1),
    HV_ACCOUNT_NEXT_STMT_MONTH     VARCHAR(2),
    HV_ACCOUNT_NEXT_STMT_DELIM2    VARCHAR(1),
    HV_ACCOUNT_NEXT_STMT_YEAR      VARCHAR(4),
    HV_ACCOUNT_AVAILABLE_BALANCE   DECIMAL(12, 2) -- Legacy: COMP-3 (Packed Decimal),
    HV_ACCOUNT_ACTUAL_BALANCE      DECIMAL(12, 2) -- Legacy: COMP-3 (Packed Decimal),
    DISP_SIGN                      VARCHAR(1),
    DISP_SQLCD                     DECIMAL(4, 0),
    DISP_REASON_CODE               VARCHAR(18),
    START_KEY                      BIGINT,
    END_KEY                        BIGINT,
    STEP_KEY                       BIGINT,
    NEXT_KEY                       BIGINT,
    FORENAME                       VARCHAR(20),
    FORENAMES_CNT                  INTEGER,
    FORENAMES_PTR                  INTEGER,
    STREET_NAME_TREE               VARCHAR(20),
    STREET_NAME_T_CNT              INTEGER,
    STREET_NAME_T_PTR              INTEGER,
    STREET_NAME_ROAD               VARCHAR(20),
    STREET_NAME_R_CNT              INTEGER,
    STREET_NAME_R_PTR              INTEGER,
    TOWN                           VARCHAR(20),
    TOWN_COUNT                     INTEGER,
    TOWN_PTR                       INTEGER,
    INITIAL_CHARACTER              VARCHAR(1),
    INITIALS_CNT                   INTEGER,
    INITIALS_PTR                   INTEGER,
    TITLE_NUMBER                   INTEGER,
    HOUSE_NUMBER                   DECIMAL(2, 0),
    SURNAME                        VARCHAR(20),
    SURNAMES_CNT                   INTEGER,
    SURNAMES_PTR                   INTEGER,
    RDATE                          VARCHAR(21),
    RANDOM_SEED                    VARCHAR(16),
    WS_CNT                         SMALLINT,
    WS_ACCOUNT_NUMBER              INTEGER,
    WS_ACCOUNT_TYPE                VARCHAR(8),
    ACCOUNT_TYPES_COUNT            INTEGER,
    ACCOUNT_TYPES_PTR              INTEGER,
    WS_ACCOUNT_INT_RATE            DECIMAL(6, 2),
    ACCOUNT_INT_RATES_COUNT        INTEGER,
    WS_ACCOUNT_OVERDRAFT_LIM       INTEGER,
    ACCOUNT_OVERDRAFT_COUNT        INTEGER,
    NO_OF_ACCOUNTS                 INTEGER,
    WS_OVERDRAFT_CONVERSION        INTEGER,
    WS_SQLCODE_DISPLAY             INTEGER,
    OPENED_DATE_ATTEMPTS           INTEGER,
    OPENED_DATE_VALID              VARCHAR(1),
    COMMIT_COUNT                   INTEGER,
    PERIOD_NEXT_F                  DECIMAL(14, 0),
    GMT_LILIAN                     INTEGER,
    FC                             VARCHAR(12),
    DATM_CONV                      VARCHAR(80),
    DATM_LENGTH                    SMALLINT,
    DATM_FORMAT                    VARCHAR(14),
    TIMESTAMP_FUNCTION             VARCHAR(40),
    WS_CURRENT_YYYY                DECIMAL(4, 0),
    WS_CURRENT_MM                  DECIMAL(2, 0),
    WS_CURRENT_DD                  DECIMAL(2, 0),
    WS_CURRENT_HOURS               DECIMAL(2, 0),
    WS_CURRENT_MINS                DECIMAL(2, 0),
    WS_CURRENT_SECS                DECIMAL(2, 0),
    WS_CURRENT_MILLI               DECIMAL(2, 0),
    WS_CURRENT_DATE_9              INTEGER,
    WS_TODAY_INT                   INTEGER,
    WS_REVIEW_DATE_ADD             SMALLINT,
    WS_NEW_REVIEW_DATE_INT         INTEGER,
    WS_NEW_REVIEW_YYYYMMDD         INTEGER,
    HV_CONTROL_NAME                VARCHAR(32),
    HV_CONTROL_VALUE_NUM           INTEGER,
    HV_CONTROL_VALUE_STR           VARCHAR(40),
    WS_WEEKDAYS                    VARCHAR(63),
    WS_WEEKDAY                     VARCHAR(9),
    WS_DT                          INTEGER,
    WS_DT_REM                      INTEGER,
    WS_DAY_OF_WEEK_VAL             SMALLINT,
    WS_DAY_TODAY                   VARCHAR(9),
    SQLCODE_DISPLAY                INTEGER,
    PARM_LENGTH                    SMALLINT,
    PARM                           VARCHAR(256)
);