CREATE TABLE DFHCOMMAREA (
    WS_CICS_RESP                   INTEGER,
    WS_CICS_RESP2                  INTEGER,
    WS_CICS_FAIL_MSG               VARCHAR(70),
    WS_CICS_RESP_DISP              BIGINT,
    WS_CICS_RESP2_DISP             BIGINT,
    VALID_DATA_SW                  VARCHAR(1),
    END_OF_SESSION_MESSAGE         VARCHAR(13),
    WS_NUM_COUNT_TOTAL             INTEGER,
    WS_NUM_COUNT_POINT             INTEGER,
    WS_NUM_COUNT_SPACE             INTEGER,
    WS_NUM_COUNT_MINUS             INTEGER,
    WS_AMOUNT_UNSTR                VARCHAR(13),
    WS_AMOUNT_UNSTR_L              INTEGER,
    WS_AMOUNT_UNSTR_REVERSE        VARCHAR(13),
    WS_CONVERT_PIC1_1ST            VARCHAR(10),
    WS_CONVERT_PIC1_POINT          VARCHAR(1),
    WS_CONVERT_PIC1_2ND            VARCHAR(2),
    WS_CONVERT_DEC                 DECIMAL(10, 0),
    WS_CONVERT_POINT               VARCHAR(1),
    WS_CONVERT_REMAIN              DECIMAL(2, 0),
    SUBPGM_FACCNO                  DECIMAL(8, 0),
    SUBPGM_FSCODE                  DECIMAL(6, 0),
    SUBPGM_TACCNO                  DECIMAL(8, 0),
    SUBPGM_TSCODE                  DECIMAL(6, 0),
    SUBPGM_AMT                     DECIMAL(12, 2),
    SUBPGM_FAVBAL                  DECIMAL(12, 2),
    SUBPGM_FACTBAL                 DECIMAL(12, 2),
    SUBPGM_TAVBAL                  DECIMAL(12, 2),
    SUBPGM_TACTBAL                 DECIMAL(12, 2),
    SUBPGM_FAIL_CODE               VARCHAR(1),
    SUBPGM_SUCCESS                 VARCHAR(1),
    WS_U_TIME                      BIGINT -- Legacy: COMP-3 (Packed Decimal),
    WS_ORIG_DATE                   VARCHAR(10),
    WS_TIME_NOW                    DECIMAL(6, 0),
    WS_TIME_NOW_GRP_HH             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_MM             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_SS             DECIMAL(2, 0),
    WS_ABEND_PGM                   VARCHAR(8)
);