CREATE TABLE DFHCOMMAREA (
    WS_UCTRANS                     INTEGER,
    STORED_UCTRANS                 INTEGER,
    WS_CICS_RESP                   INTEGER,
    WS_CICS_RESP2                  INTEGER,
    WS_CICS_FAIL_MSG               VARCHAR(70),
    WS_CICS_RESP_DISP              BIGINT,
    WS_CICS_RESP2_DISP             BIGINT,
    VALID_DATA_SW                  VARCHAR(1),
    END_OF_SESSION_MESSAGE         VARCHAR(13),
    WS_COMM_TERM                   INTEGER,
    DOBDDI_CHAR                    VARCHAR(2),
    DOBDDI_NUM                     DECIMAL(2, 0),
    DOBMMI_CHAR                    VARCHAR(2),
    DOBMMI_NUM                     DECIMAL(2, 0),
    DOBYYI_NUM                     DECIMAL(2, 0),
    WS_ABCODE                      VARCHAR(4),
    WS_ADDR_SPLIT1                 VARCHAR(60),
    WS_ADDR_SPLIT2                 VARCHAR(60),
    WS_ADDR_SPLIT3                 VARCHAR(40),
    SUBPGM_EYECATCHER              VARCHAR(4),
    SUBPGM_SORTCODE                INTEGER,
    SUBPGM_NUMBER                  BIGINT,
    SUBPGM_NAME                    VARCHAR(60),
    SUBPGM_ADDRESS                 VARCHAR(160),
    SUBPGM_BIRTH_DAY               DECIMAL(2, 0),
    SUBPGM_BIRTH_MONTH             DECIMAL(2, 0),
    SUBPGM_BIRTH_YEAR              DECIMAL(4, 0),
    SUBPGM_CREDIT_SCORE            DECIMAL(3, 0),
    SUBPGM_CS_REVIEW_DATE          DECIMAL(8, 0),
    SUBPGM_SUCCESS                 VARCHAR(1),
    SUBPGM_FAIL_CODE               VARCHAR(1),
    WS_U_TIME                      BIGINT -- Legacy: COMP-3 (Packed Decimal),
    WS_ORIG_DATE                   VARCHAR(10),
    WS_TIME_NOW                    DECIMAL(6, 0),
    WS_TIME_NOW_GRP_HH             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_MM             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_SS             DECIMAL(2, 0),
    WS_ABEND_PGM                   VARCHAR(8)
);