CREATE TABLE DFHCOMMAREA (
    WS_CICS_RESP                   INTEGER,
    WS_CICS_RESP2                  INTEGER,
    WS_CICS_FAIL_MSG               VARCHAR(70),
    WS_CICS_RESP_DISP              BIGINT,
    WS_CICS_RESP2_DISP             BIGINT,
    VALID_DATA_SW                  VARCHAR(1),
    END_OF_SESSION_MESSAGE         VARCHAR(13),
    WS_COMM_AV_BAL_UNSIGN          DECIMAL(12, 0),
    WS_LSTMTDDI                    DECIMAL(2, 0),
    WS_LSTMTMMI                    DECIMAL(2, 0),
    WS_LSTMTYYI                    DECIMAL(4, 0),
    WS_NSTMTDDI                    DECIMAL(2, 0),
    WS_NSTMTMMI                    DECIMAL(2, 0),
    WS_NSTMTYYI                    DECIMAL(4, 0),
    WS_DATE_SPLIT_DD               DECIMAL(2, 0),
    WS_DATE_SPLIT_MM               DECIMAL(2, 0),
    WS_DATE_SPLIT_YY               DECIMAL(4, 0),
    WS_CONVERT_PICX                VARCHAR(14),
    WS_CONVERT_SIGN                VARCHAR(1),
    WS_CONVERT_DEC                 DECIMAL(10, 0),
    WS_CONVERT_POINT               VARCHAR(1),
    WS_CONVERT_REMAIN              DECIMAL(2, 0),
    WS_CONVERTED_VAL1              DECIMAL(12, 2),
    WS_CONVERTED_VAL2              DECIMAL(12, 2),
    WS_CONVERTED_VAL3              DECIMAL(12, 2),
    WS_CONVERTED_VAL4              DECIMAL(12, 2),
    INT_RT_9                       DECIMAL(6, 2),
    WS_COMM_EYE                    VARCHAR(4),
    WS_COMM_CUSTNO                 VARCHAR(10),
    WS_COMM_SCODE                  VARCHAR(6),
    WS_COMM_ACCNO                  DECIMAL(8, 0),
    WS_COMM_ACC_TYPE               VARCHAR(8),
    WS_COMM_INT_RATE               DECIMAL(6, 2),
    WS_COMM_OPENED                 DECIMAL(8, 0),
    WS_COMM_OVERDRAFT              DECIMAL(8, 0),
    WS_COMM_LAST_STMT_DT           DECIMAL(8, 0),
    WS_COMM_NEXT_STMT_DT           DECIMAL(8, 0),
    WS_COMM_AVAIL_BAL              DECIMAL(12, 2),
    WS_COMM_ACTUAL_BAL             DECIMAL(12, 2),
    INTRT_PIC9                     DECIMAL(6, 2),
    WS_NUM_COUNT_POINT             INTEGER,
    WS_NUM_COUNT_TOTAL             INTEGER,
    WS_U_TIME                      BIGINT -- Legacy: COMP-3 (Packed Decimal),
    WS_ORIG_DATE                   VARCHAR(10),
    WS_TIME_NOW                    DECIMAL(6, 0),
    WS_TIME_NOW_GRP_HH             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_MM             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_SS             DECIMAL(2, 0),
    WS_ABEND_PGM                   VARCHAR(8),
    COMM_EYE                       VARCHAR(4),
    COMM_CUSTNO                    VARCHAR(10),
    COMM_SCODE                     VARCHAR(6),
    COMM_ACCNO                     DECIMAL(8, 0),
    COMM_ACC_TYPE                  VARCHAR(8),
    COMM_INT_RATE                  DECIMAL(6, 2),
    COMM_OPENED                    DECIMAL(8, 0),
    COMM_OVERDRAFT                 DECIMAL(8, 0),
    COMM_LAST_STMT_DT              DECIMAL(8, 0),
    COMM_NEXT_STMT_DT              DECIMAL(8, 0),
    COMM_AVAIL_BAL                 DECIMAL(12, 2),
    COMM_ACTUAL_BAL                DECIMAL(12, 2),
    COMM_SUCCESS                   VARCHAR(1)
);