CREATE TABLE ABNDINFO_REC (
    HV_ACCOUNT_EYECATCHER          VARCHAR(4),
    HV_ACCOUNT_CUST_NO             VARCHAR(10),
    HV_ACCOUNT_SORTCODE            VARCHAR(6),
    HV_ACCOUNT_ACC_NO              VARCHAR(8),
    HV_ACCOUNT_ACC_TYPE            VARCHAR(8),
    HV_ACCOUNT_INT_RATE            DECIMAL(6, 2) -- Legacy: COMP-3 (Packed Decimal),
    HV_ACCOUNT_OPENED              VARCHAR(10),
    HV_ACCOUNT_OVERDRAFT_LIM       INTEGER,
    HV_ACCOUNT_LAST_STMT           VARCHAR(10),
    HV_ACCOUNT_NEXT_STMT           VARCHAR(10),
    HV_ACCOUNT_AVAIL_BAL           DECIMAL(12, 2) -- Legacy: COMP-3 (Packed Decimal),
    HV_ACCOUNT_ACTUAL_BAL          DECIMAL(12, 2) -- Legacy: COMP-3 (Packed Decimal),
    WS_CICS_RESP                   INTEGER,
    WS_CICS_RESP2                  INTEGER,
    RETURNED_SORT_CODE             DECIMAL(6, 0),
    RETURNED_NUMBER                DECIMAL(8, 0),
    DB2_DATE_REF_YR                DECIMAL(4, 0),
    DB2_DATE_REF_MNTH              DECIMAL(2, 0),
    DB2_DATE_REF_DAY               DECIMAL(2, 0),
    REQUIRED_SORT_CODE             INTEGER,
    MY_ABEND_CODE                  VARCHAR(4),
    WS_STORM_DRAIN                 VARCHAR(1),
    STORM_DRAIN_CONDITION          VARCHAR(20),
    SQLCODE_DISPLAY                INTEGER,
    NCS_ACC_NO_ACT_NAME            VARCHAR(8),
    NCS_ACC_NO_TEST_SORT           VARCHAR(6),
    NCS_ACC_NO_FILL                VARCHAR(2),
    NCS_ACC_NO_VALUE               BIGINT,
    REQUIRED_ACC_NUMBER2           INTEGER,
    WS_U_TIME                      BIGINT -- Legacy: COMP-3 (Packed Decimal),
    WS_ORIG_DATE                   VARCHAR(10),
    WS_TIME_NOW                    DECIMAL(6, 0),
    WS_TIME_NOW_GRP_HH             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_MM             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_SS             DECIMAL(2, 0),
    WS_ABEND_PGM                   VARCHAR(8)
);