CREATE TABLE DFHCOMMAREA (
    SYSIDERR_RETRY                 DECIMAL(3, 0),
    INQCUST_RETRY                  DECIMAL(4, 0),
    WS_CICS_RESP                   INTEGER,
    WS_CICS_RESP2                  INTEGER,
    REQUIRED_SORT_CODE             INTEGER,
    REQUIRED_CUST_NUMBER           BIGINT,
    REQUIRED_CUST_NUMBER2          BIGINT,
    RANDOM_CUSTOMER                BIGINT,
    EXIT_VSAM_READ                 VARCHAR(1),
    EXIT_DB2_READ                  VARCHAR(1),
    WS_V_RETRIED                   VARCHAR(1),
    WS_D_RETRIED                   VARCHAR(1),
    NCS_CUST_NO_ACT_NAME           VARCHAR(8),
    NCS_CUST_NO_TEST_SORT          VARCHAR(6),
    NCS_CUST_NO_FILL               VARCHAR(2),
    NCS_CUST_NO_VALUE              BIGINT,
    WS_CUSTOMER_RANGE_TOP          VARCHAR(1),
    WS_CUSTOMER_RANGE_MIDDLE       VARCHAR(1),
    WS_CUSTOMER_RANGE_BOTTOM       VARCHAR(1),
    REMIX_SCODE_NUM                DECIMAL(6, 0),
    REMIX2_CREDIT_SCR_NUM          DECIMAL(3, 0),
    MY_ABEND_CODE                  VARCHAR(4),
    WS_STORM_DRAIN                 VARCHAR(1),
    WS_U_TIME                      BIGINT -- Legacy: COMP-3 (Packed Decimal),
    WS_ORIG_DATE                   VARCHAR(10),
    WS_TIME_NOW                    DECIMAL(6, 0),
    WS_TIME_NOW_GRP_HH             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_MM             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_SS             DECIMAL(2, 0),
    WS_ABEND_PGM                   VARCHAR(8)
);