CREATE TABLE DFHCOMMAREA (
    HV_ACCOUNT_EYECATCHER          VARCHAR(4),
    HV_ACCOUNT_CUST_NO             VARCHAR(10),
    HV_ACCOUNT_SORTCODE            VARCHAR(6),
    HV_ACCOUNT_ACC_NO              VARCHAR(8),
    HV_ACCOUNT_ACC_TYPE            VARCHAR(8),
    HV_ACCOUNT_INT_RATE            DECIMAL(6, 2) -- Legacy: COMP-3 (Packed Decimal),
    HV_ACCOUNT_OPENED              VARCHAR(10),
    HV_ACCOUNT_OVERDRAFT_LIM       INTEGER,
    HV_ACCOUNT_LAST_STMT           VARCHAR(10),
    HV_ACCOUNT_NEXT_STMT           VARCHAR(10),
    HV_ACCOUNT_AVAIL_BAL           DECIMAL(12, 2) -- Legacy: COMP-3 (Packed Decimal),
    HV_ACCOUNT_ACTUAL_BAL          DECIMAL(12, 2) -- Legacy: COMP-3 (Packed Decimal),
    SQLCODE_DISPLAY                INTEGER,
    DB2_DATE_REF_YR                DECIMAL(4, 0),
    DB2_DATE_REF_MNTH              DECIMAL(2, 0),
    DB2_DATE_REF_DAY               DECIMAL(2, 0),
    DESIRED_SORT_CODE              DECIMAL(6, 0),
    DESIRED_ACC_NO                 DECIMAL(8, 0),
    WS_U_TIME                      BIGINT -- Legacy: COMP-3 (Packed Decimal),
    WS_ORIG_DATE                   VARCHAR(10),
    WS_TIME_NOW                    DECIMAL(6, 0),
    WS_TIME_NOW_GRP_HH             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_MM             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_SS             DECIMAL(2, 0)
);