CREATE TABLE DFHCOMMAREA (
    HV_ACCOUNT_EYECATCHER          VARCHAR(4),
    HV_ACCOUNT_CUST_NO             VARCHAR(10),
    HV_ACCOUNT_SORTCODE            VARCHAR(6),
    HV_ACCOUNT_ACC_NO              VARCHAR(8),
    HV_ACCOUNT_ACC_TYPE            VARCHAR(8),
    HV_ACCOUNT_INT_RATE            DECIMAL(6, 2) -- Legacy: COMP-3 (Packed Decimal),
    HV_ACCOUNT_OPENED              VARCHAR(10),
    HV_ACCOUNT_OVERDRAFT_LIM       INTEGER,
    HV_ACCOUNT_LAST_STMT           VARCHAR(10),
    HV_ACCOUNT_NEXT_STMT           VARCHAR(10),
    HV_ACCOUNT_AVAIL_BAL           DECIMAL(12, 2) -- Legacy: COMP-3 (Packed Decimal),
    HV_ACCOUNT_ACTUAL_BAL          DECIMAL(12, 2) -- Legacy: COMP-3 (Packed Decimal),
    HV_PROCTRAN_EYECATCHER         VARCHAR(4),
    HV_PROCTRAN_SORT_CODE          VARCHAR(6),
    HV_PROCTRAN_ACC_NUMBER         VARCHAR(8),
    HV_PROCTRAN_DATE               VARCHAR(10),
    HV_PROCTRAN_TIME               VARCHAR(6),
    HV_PROCTRAN_REF                VARCHAR(12),
    HV_PROCTRAN_TYPE               VARCHAR(3),
    HV_PROCTRAN_DESC               VARCHAR(40),
    HV_PROCTRAN_AMOUNT             DECIMAL(12, 2) -- Legacy: COMP-3 (Packed Decimal),
    WS_CICS_RESP                   INTEGER,
    WS_CICS_RESP2                  INTEGER,
    DB2_DEADLOCK_RETRY             DECIMAL(3, 0),
    WS_EIBTASKN12                  BIGINT,
    WS_SQLCODE_DISP                INTEGER,
    DESIRED_SORT_CODE              DECIMAL(6, 0),
    DESIRED_ACC_NO                 DECIMAL(8, 0),
    WS_U_TIME                      BIGINT -- Legacy: COMP-3 (Packed Decimal),
    WS_ORIG_DATE                   VARCHAR(10),
    WS_CUSTOMER_RANGE_TOP          VARCHAR(1),
    MY_ABEND_CODE                  VARCHAR(4),
    WS_STORM_DRAIN                 VARCHAR(1),
    STORM_DRAIN_CONDITION          VARCHAR(20),
    SQLCODE_DISPLAY                INTEGER,
    WS_TIME_NOW                    DECIMAL(6, 0),
    WS_TIME_NOW_GRP_HH             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_MM             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_SS             DECIMAL(2, 0),
    WS_ABEND_PGM                   VARCHAR(8)
);