CREATE TABLE DFHCOMMAREA (
    WS_CICS_RESP                   INTEGER,
    WS_CICS_RESP2                  INTEGER,
    WS_CICS_FAIL_MSG               VARCHAR(70),
    WS_CICS_RESP_DISP              BIGINT,
    WS_CICS_RESP2_DISP             BIGINT,
    VALID_DATA_SW                  VARCHAR(1),
    END_OF_SESSION_MESSAGE         VARCHAR(13),
    WS_COMM_CUSTNO                 DECIMAL(10, 0),
    WS_COMM_ACCTYPE                VARCHAR(8),
    WS_COMM_INTRT                  DECIMAL(6, 2),
    WS_COMM_OVERDR                 DECIMAL(8, 0),
    NSTMTDD_NUM                    DECIMAL(2, 0),
    NSTMTMMI_NUM                   DECIMAL(2, 0),
    NSTMTYYI_NUM                   DECIMAL(2, 0),
    NST_NUM                        DECIMAL(8, 0),
    INTRT_PIC9                     DECIMAL(6, 2),
    WS_NUM_COUNT_POINT             INTEGER,
    WS_NUM_COUNT_TOTAL             INTEGER,
    WS_REVERSE                     VARCHAR(8),
    SUBPGM_EYECATCHER              VARCHAR(4),
    SUBPGM_CUSTNO                  DECIMAL(10, 0),
    SUBPGM_SORTCODE                INTEGER,
    SUBPGM_NUMBER                  INTEGER,
    SUBPGM_ACC_TYPE                VARCHAR(8),
    SUBPGM_INT_RT                  DECIMAL(6, 2),
    SUBPGM_OPENED                  DECIMAL(8, 0),
    SUBPGM_OVERDR_LIM              DECIMAL(8, 0),
    SUBPGM_LAST_STMT_DT            DECIMAL(8, 0),
    SUBPGM_NEXT_STMT_DT            DECIMAL(8, 0),
    SUBPGM_AVAIL_BAL               DECIMAL(12, 2),
    SUBPGM_ACT_BAL                 DECIMAL(12, 2),
    SUBPGM_SUCCESS                 VARCHAR(1),
    SUBPGM_FAIL_CODE               VARCHAR(1),
    WS_U_TIME                      BIGINT -- Legacy: COMP-3 (Packed Decimal),
    WS_ORIG_DATE                   VARCHAR(10),
    WS_TIME_NOW                    DECIMAL(6, 0),
    WS_TIME_NOW_GRP_HH             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_MM             DECIMAL(2, 0),
    WS_TIME_NOW_GRP_SS             DECIMAL(2, 0),
    WS_ABEND_PGM                   VARCHAR(8),
    COMM_CUSTNO                    DECIMAL(10, 0),
    COMM_ACCTYPE                   VARCHAR(8),
    COMM_INTRT                     DECIMAL(6, 2),
    COMM_OVERDR                    DECIMAL(8, 0)
);