# ==============================================================================
# GitGalaxy
# Copyright (c) 2026 Joe Esquibel
#
# This source code is licensed under the PolyForm Noncommercial License 1.0.0.
# You may not use this file except in compliance with the License.
# A copy of the license can be found in the LICENSE file in the root directory
# of this project, or at https://polyformproject.org/licenses/noncommercial/1.0.0/
# ==============================================================================

# galaxyscope:ignore sec_hardcoded_secrets, secrets_risk

"""
language_standards.py
Phase 2 & 3: The Lexical Registry & Syntax Dictionaries.

This file contains the compiled regular expressions, mechanical delimiters,
and language-specific rules used to physically slice, parse, and identify
source code across the repository.

## Tree-sitter Accuracy Audit Summary
This data is automatically generated by `tests/tools/tree_sitter_accuracy_audit.py --summary-table`
from the committed `tests/tree_sitter_accuracy_baseline_<lang>.json` files -- do not hand-edit the
table below, regenerate it instead (a stale table fails the tree-sitter-accuracy-audit CI check).
The script analyzes the GitGalaxy regex engine's performance against the empirical AST
ground truth provided by `tree_sitter_language_pack`, using the `language-crucible` corpus.
Recall is calculated as (found / real). Precision is calculated as (found / (found + extra)).
A language only appears once it has a committed baseline -- see docs/self_scan/tree_sitter_accuracy_history.csv
for the same metrics tracked over time across pushes to main.

<!-- TREE_SITTER_ACCURACY_TABLE:BEGIN -->
| Language | Func Recall | Func Precision | Class Recall | Class Precision |
| -------- | ----------- | -------------- | ------------ | --------------- |
| Apex | 100.0% | 100.0% | 100.0% | 100.0% |
| C | 100.0% | 99.5% | 100.0% | 100.0% |
| Cpp | 100.0% | 100.0% | 100.0% | 100.0% |
| Csharp | 100.0% | 100.0% | 100.0% | 100.0% |
| Css | 100.0% | 100.0% | N/A | N/A |
| Dart | 100.0% | 100.0% | 100.0% | 100.0% |
| Fortran | 100.0% | 100.0% | 100.0% | 100.0% |
| Go | 100.0% | 100.0% | 100.0% | 100.0% |
| Groovy | N/A | 0.0% | N/A | N/A |
| Haskell | 100.0% | 99.3% | 100.0% | 100.0% |
| Html | 100.0% | 100.0% | N/A | N/A |
| Java | 100.0% | 100.0% | 100.0% | 100.0% |
| Javascript | 100.0% | 98.0% | 100.0% | 100.0% |
| Kotlin | 100.0% | 100.0% | 100.0% | 100.0% |
| Lua | 100.0% | 100.0% | N/A | 0.0% |
| Makefile | 100.0% | 100.0% | N/A | N/A |
| Matlab | 100.0% | 100.0% | N/A | N/A |
| Objective-C | 100.0% | 99.4% | 100.0% | 100.0% |
| Perl | 100.0% | 100.0% | 100.0% | 100.0% |
| Php | 100.0% | 99.9% | 100.0% | 100.0% |
| Powershell | 100.0% | 100.0% | 100.0% | 100.0% |
| Python | 100.0% | 99.6% | 100.0% | 100.0% |
| Ruby | 100.0% | 100.0% | 100.0% | 100.0% |
| Rust | 100.0% | 100.0% | 100.0% | 100.0% |
| Scala | 100.0% | 100.0% | 100.0% | 100.0% |
| Shell | 99.8% | 97.0% | N/A | N/A |
| Solidity | 100.0% | 94.3% | 100.0% | 100.0% |
| Swift | 100.0% | 99.2% | 100.0% | 100.0% |
| Tcl | 100.0% | 99.1% | N/A | N/A |
| Typescript | 100.0% | 100.0% | 100.0% | 100.0% |
| Zig | 100.0% | 100.0% | 100.0% | 100.0% |
<!-- TREE_SITTER_ACCURACY_TABLE:END -->
"""

from typing import Any

from ._lens_config import LENS_CONFIG, LensConfig
from ._overrides import PROJECT_OVERRIDES
from ._prism_config import PRISM_CONFIG, PrismConfigSchema
from ._shared_patterns import HTML_NONEXECUTABLE_SCRIPT_TAG
from .languages import abap as _abap
from .languages import ada as _ada
from .languages import agc_assembly as _agc_assembly
from .languages import apex as _apex
from .languages import assembly as _assembly
from .languages import batch as _batch
from .languages import blp as _blp
from .languages import c as _c
from .languages import cobol as _cobol
from .languages import cpp as _cpp
from .languages import csharp as _csharp
from .languages import css as _css
from .languages import csv as _csv
from .languages import dart as _dart
from .languages import dockerfile as _dockerfile
from .languages import embedded_python as _embedded_python
from .languages import fortran as _fortran
from .languages import glsl as _glsl
from .languages import go as _go
from .languages import groovy as _groovy
from .languages import haskell as _haskell
from .languages import hlo as _hlo
from .languages import html as _html
from .languages import java as _java
from .languages import javascript as _javascript
from .languages import jcl as _jcl
from .languages import json as _json
from .languages import kotlin as _kotlin
from .languages import livecode as _livecode
from .languages import lua as _lua
from .languages import m4 as _m4
from .languages import makefile as _makefile
from .languages import markdown as _markdown
from .languages import matlab as _matlab
from .languages import mlir as _mlir
from .languages import nix as _nix
from .languages import objectivec as _objectivec
from .languages import pbtxt as _pbtxt
from .languages import perl as _perl
from .languages import php as _php
from .languages import plaintext as _plaintext
from .languages import powershell as _powershell
from .languages import proto as _proto
from .languages import python as _python
from .languages import ruby as _ruby
from .languages import rust as _rust
from .languages import scala as _scala
from .languages import scheme as _scheme
from .languages import shell as _shell
from .languages import solidity as _solidity
from .languages import sqlite as _sqlite
from .languages import swift as _swift
from .languages import tcl as _tcl
from .languages import td as _td
from .languages import typescript as _typescript
from .languages import xml as _xml
from .languages import yacc as _yacc
from .languages import yaml as _yaml
from .languages import zig as _zig

__all__ = [
    "HTML_NONEXECUTABLE_SCRIPT_TAG",
    "LANGUAGE_DEFINITIONS",
    "LENS_CONFIG",
    "PRISM_CONFIG",
    "PROJECT_OVERRIDES",
    "LensConfig",
    "PrismConfigSchema",
]

LANGUAGE_DEFINITIONS: dict[str, Any] = {
    "python": _python.DEFINITION,
    "javascript": _javascript.DEFINITION,
    "typescript": _typescript.DEFINITION,
    "java": _java.DEFINITION,
    "csharp": _csharp.DEFINITION,
    "go": _go.DEFINITION,
    "rust": _rust.DEFINITION,
    "cpp": _cpp.DEFINITION,
    "c": _c.DEFINITION,
    "php": _php.DEFINITION,
    "powershell": _powershell.DEFINITION,
    "shell": _shell.DEFINITION,
    "ruby": _ruby.DEFINITION,
    "swift": _swift.DEFINITION,
    "kotlin": _kotlin.DEFINITION,
    "sqlite": _sqlite.DEFINITION,
    "html": _html.DEFINITION,
    "css": _css.DEFINITION,
    "fortran": _fortran.DEFINITION,
    "assembly": _assembly.DEFINITION,
    "agc_assembly": _agc_assembly.DEFINITION,
    "lua": _lua.DEFINITION,
    "perl": _perl.DEFINITION,
    "haskell": _haskell.DEFINITION,
    "embedded_python": _embedded_python.DEFINITION,
    "cobol": _cobol.DEFINITION,
    "zig": _zig.DEFINITION,
    "apex": _apex.DEFINITION,
    "dart": _dart.DEFINITION,
    "scala": _scala.DEFINITION,
    "dockerfile": _dockerfile.DEFINITION,
    "matlab": _matlab.DEFINITION,
    "livecode": _livecode.DEFINITION,
    "solidity": _solidity.DEFINITION,
    "objective-c": _objectivec.DEFINITION,
    "makefile": _makefile.DEFINITION,
    "abap": _abap.DEFINITION,
    "xml": _xml.DEFINITION,
    "markdown": _markdown.DEFINITION,
    "csv": _csv.DEFINITION,
    "yaml": _yaml.DEFINITION,
    "pbtxt": _pbtxt.DEFINITION,
    "yacc": _yacc.DEFINITION,
    "m4": _m4.DEFINITION,
    "scheme": _scheme.DEFINITION,
    "mlir": _mlir.DEFINITION,
    "proto": _proto.DEFINITION,
    "hlo": _hlo.DEFINITION,
    "td": _td.DEFINITION,
    "plaintext": _plaintext.DEFINITION,
    "tcl": _tcl.DEFINITION,
    "groovy": _groovy.DEFINITION,
    "json": _json.DEFINITION,
    "glsl": _glsl.DEFINITION,
    "nix": _nix.DEFINITION,
    "blp": _blp.DEFINITION,
    "batch": _batch.DEFINITION,
    "jcl": _jcl.DEFINITION,
    "ada": _ada.DEFINITION,
}
